includes/class-coblocks-notices.php
=> Added notice if Gutenberg is not installed.

src/extensions/advanced-controls/index.js, src/extensions/advanced-controls/styles/editor.scss
For : https://github.com/thatplugincompany/coblocks/issues/58
=> Add coBlocksSpacing support to a few core blocks

src/blocks/media-card/components/edit.js, src/components/dimensions-control/index.js, src/styles/style/_margin.scss, src/styles/style/_padding.scss
=> Fixes for Media Card Padding and Structure

src/extensions/advanced-controls/index.js, src/extensions/advanced-controls/styles/editor.scss
=> Update the data-no-top-margin and data-no-bottom-margin attributes

src/extensions/advanced-controls/index.js
=> Improve text of the "No top spacing" and "No bottom spacing" ToggleControls 

src/blocks/highlight/styles/editor.scss
=> Custom background color for the Highlight block does not work properly

src/blocks/media-card/styles/editor.scss
=> Remove Media Card Styles Preview 

src/extensions/typography/index.js, src/extensions/typography/styles/editor.scss
Makes it easier for block/theme developers to know what's going on.
=> Change data-custom-fontfamily to data-coblocks-font

src/blocks/pricing-table/pricing-table-item/components/inspector.js
=> Open Pricing Table Item color settings

src/blocks/pricing-table/styles/editor.scss
=> Fixes #117

src/extensions/colors/index.js
Makes it less confusing to change the heading color.
=> Remove Heading Block background color

src/blocks/media-card/components/inspector.js
=> Remove withFallbackStyles from Media Card

src/components/typography-controls/index.js
=> Adjust line height step per #129

gulpfile.js
=> Adds proper support for the admin modal js file #67

includes/class-coblocks-accordion-ie-support.php, package-lock.json, package.json
=> Fixes : PHP warning returning on 404 #156

src/blocks/media-card/styles/style.scss
=> Styles may be too specific in the Media Card block #142

src/components/background/controls.js, src/components/background/dropzone.js, src/components/background/index.js
Also added support for features, feature, row and column to auto-add Medium padding, if an image is added.
=> Update BackgroundImage component to easily auto-add padding

src/blocks/row/components/inspector.js
=> Adding a backgroundColor should set the padding to medium on the Row Block

src/blocks/layout/components/edit.js, src/blocks/layout/styles/editor.scss
Just merging into the sidebar branch because of the modal enhancements we baked in.
=> Layout UI Tweaks

src/components/dimensions-control/index.js, src/components/dimensions-control/styles/editor.scss, src/components/orientation/styles/editor.scss
=> Fix Gutenberg 5.0 ResponsiveBaseControl and OrientationControl

package-lock.json, src/blocks/map/components/edit.js, src/blocks/map/index.js
=> Map block fixes master

package.json
Now that we've pushed all those fixes for 5.1, we're good to update the tested up to value.
=> Update tested up to value to 5.1

readme.txt, src/extensions/attributes/index.js
=> ID filter fix for #290

src/blocks/row/components/controls.js
=> Fix the BackgroundImageToolbarControls issue from the singular column Row block

src/blocks/row/components/edit.js
=> Remove the extraneous dropzone from the Row block

src/blocks/row/styles/style.scss
=> Column image overlay fixes

src/blocks/social/styles/editor.scss, src/blocks/social/styles/style.scss
Removes any ::before content if a theme applies it globally to list items
=> Social block li::before fix

src/blocks/buttons/styles/style.scss
=> Buttons block fixes

src/blocks/buttons/styles/style.scss
=> Fix empty buttons within the stacked Buttons block

src/extensions/list-styles/index.js, src/extensions/list-styles/styles/style.scss
=> No style list

src/blocks.js, src/extensions/button-controls/index.js, src/extensions/button-controls/styles/editor.scss, src/extensions/button-controls/styles/style.scss
=> Button fullwidth

src/blocks/features/styles/style.scss
=> Fixes #391

src/blocks/icon/styles/editor.scss
=> Fixes the Icon Block search function that broke in Gutenberg 5.3 

src/blocks/icon/components/inspector.js
=> Rename RangeControl to Size from Custom Size

src/blocks/hero/index.js
=> Tweak the Hero block default background color

src/blocks/hero/components/icons.js
Improves upon the icon previously added in #388
=> Add improved layout icon for the Hero Block

src/formats/uppercase/icons.js
=> Fix format icon for "Uppercase" formatting

src/components/background/index.js, src/styles/style/_background-overlay.scss
To resemble how the Cover block within core functions.
=> Set max to 100 for Background Opacity

src/blocks/pricing-table/pricing-table-item/styles/editor.scss, src/blocks/pricing-table/styles/editor.scss, src/blocks/pricing-table/styles/style.scss
Changes the tables so that all three/four columns display across - if the table is set to a wide or full alignment. Otherwise, the table performs as before. 
Closes #279
=> Update pricing table positioning for wide/full alignment

src/components/visual-dropdown/styles/editor.scss
=> Fix Map styles dropdown component #426

src/blocks/shape-divider/components/edit.js, src/blocks/shape-divider/styles/editor.scss, src/components/inline-color-picker/index.js, src/components/inline-color-picker/styles/editor.scss
=> Introduce new InlineColorPicker component to add back the custom color picker 

src/components/inline-color-picker/index.js
=> Fix TypeError: this.activateMode is not a function #434

src/blocks/row/components/edit.js
=> Add additional class to the editor on the Row block

includes/admin/class-coblocks-getting-started-page.php
=> [tiny] Prevent redirection in WP-CLI and show log message for those users

src/blocks/row/components/deprecations.js, src/blocks/row/components/edit.js, src/blocks/row/components/save.js, src/blocks/row/index.js
- Fixed deprecation issues and moved into own file
- Moved save function to own file
- Fixed lint issue
- Removed unused variables
Resolve #483
=> Video Background + Background Opacity

src/blocks/hero/styles/editor.scss
=> [tiny] Fix hero block resizableBox issue

src/blocks/map/components/inspector.js, src/blocks/map/styles/editor.scss
https://github.com/godaddy/coblocks/issues/491
=> Added Remove button for API Key

src/blocks/map/components/inspector.js
https://github.com/godaddy/coblocks/issues/491
=> Check if the API key is saved before calling API on remove

src/blocks/gist/components/edit.js, src/blocks/gist/styles/editor.scss
Resolves #502.
Example: https://cloudup.com/cQaRjQT3j1X
=> Update gist block with a proper UI for Gutenberg 5.5+

src/components/inline-color-picker/index.js, src/components/inline-color-picker/styles/editor.scss
=> Fix overlap of resize handle and color picker

src/blocks/row/column/components/edit.js, src/blocks/row/styles/editor.scss
=> Fix row row handles

src/blocks/media-card/styles/editor.scss
- Resize handle would go below the card
- Adjusted top positioning
=> Media card resize handle fix

class-coblocks.php, includes/admin/class-coblocks-action-links.php, includes/admin/class-coblocks-admin-footer.php, includes/admin/class-coblocks-feedback.php, includes/admin/class-coblocks-getting-started-page.php, includes/admin/class-coblocks-install.php, includes/admin/class-coblocks-url-generator.php, includes/class-coblocks-accordion-ie-support.php, includes/class-coblocks-block-assets.php, includes/class-coblocks-body-classes.php, includes/class-coblocks-font-loader.php, includes/class-coblocks-generated-styles.php, includes/class-coblocks-google-map.php, includes/class-coblocks-post-meta.php, includes/class-coblocks-register-blocks.php, includes/class-coblocks-settings.php, includes/get-dynamic-blocks.php, src/blocks/social/index.php
This PR cleans up the file headers, removing extraneous information.
=> Tweak file headers

LICENSE, readme.txt
This PR changes the plugin license from GPL-3 to GPL-2.
=> Update license to GPL-2

class-coblocks.php, src/styles/admin/_dashboard-widget.scss
We don't need pro functions anymore.
=> Remove unused is_pro and has_pro functions

languages/coblocks.pot, package-lock.json, src/blocks/map/components/edit.js, src/blocks/map/components/inspector.js
=> Update map block placeholder string

readme.txt
This PR adds recent contributors to the WordPress.org readme.txt file.
=> Add recent contributors 🎉

languages/coblocks.pot, src/blocks/dynamic-separator/index.js, src/blocks/icon/index.js, src/blocks/shape-divider/index.js, src/blocks/social/index.js
This PR adds context to the block style names for easier translation.
=> Add context to block style names for improved translatable strings

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Enhancement.md, .github/ISSUE_TEMPLATE/Feature_request.md
Tweak language of our issue templates
=> Tweak language of our issue templates

src/blocks/map/components/edit.js
Resolves #594 
Double clicking on the map inside of the map block displays the location editor
=> Double clicking the rendered map brings up the location editor

includes/class-coblocks-google-map-block.php, src/js/coblocks-google-maps.js
Resolves #608 
Fix duplicate Google map script being loaded in the editor
=> Fix duplicate Google map script enqueued in editor

src/blocks/map/components/edit.js
https://cloudup.com/cVgf9eD7x7O
=> Fix map block erroring on initial add without an address

src/blocks/food-and-drinks/block.json, src/blocks/food-and-drinks/edit.js, src/blocks/food-and-drinks/food-item/styles/editor.scss, src/blocks/food-and-drinks/food-item/styles/style.scss, src/blocks/food-and-drinks/index.js, src/blocks/food-and-drinks/inspector.js, src/blocks/food-and-drinks/save.js, src/blocks/food-and-drinks/styles/editor.scss
This PR adds support for columns to the Food and Drinks block.
=> Add support for three columns to the Food and Drinks block

src/blocks/gallery-carousel/icons.js, src/blocks/gallery-stacked/icons.js
Pull closes https://github.com/godaddy/coblocks/issues/623 and closes https://github.com/godaddy/coblocks/issues/624.
=> Update Icons For Carousel and Stacked Gallery blocks

languages/coblocks.pot, src/blocks/share/inspector.js
-Swap out title from 'Social Settings' to 'Icon Settings'.
=> Update Panel Title to 'Icon Settings'. #621

src/blocks/features/components/edit.js, src/blocks/features/components/inspector.js, src/blocks/features/feature/components/edit.js, src/blocks/features/feature/components/icons.js, src/blocks/features/styles/editor.scss, src/blocks/food-and-drinks/edit.js, src/blocks/icon/components/inspector.js, src/blocks/pricing-table/pricing-table-item/index.js, src/components/background/styles.js, src/extensions/advanced-controls/index.js, src/sidebars/block-manager/components/modal.js
This PR resolves a few deprecation and console warnings.
=> Fix minor console errors and deprecation notices

src/blocks/dynamic-separator/styles/style.scss
=> Fix Dynamic HR block with TwentyNineteen

src/blocks/hero/styles/editor.scss
=> Fix Hero block z-index issue on wide and full width

src/extensions/advanced-controls/index.js
=> Add core/group block to blocksWithSpacingSupport

src/blocks/buttons/styles/editor.scss, src/blocks/buttons/styles/style.scss
=> Fix issue with inline link in Buttons block

README.md, readme.txt
Bump license version to match **License URI** in readme.txt
https://github.com/godaddy/coblocks/blob/master/readme.txt#L11
=> Bump GPL to v3

src/blocks/services/index.js, src/blocks/services/service/index.js
=> Add descriptions to Services and Service blocks

languages/coblocks.pot, src/blocks/accordion/accordion-item/index.js, src/blocks/accordion/index.js, src/blocks/alert/index.js, src/blocks/author/index.js, src/blocks/buttons/index.js, src/blocks/click-to-tweet/index.js, src/blocks/dynamic-separator/index.js, src/blocks/features/index.js, src/blocks/gif/edit.js, src/blocks/gif/index.js, src/blocks/gist/index.js, src/blocks/highlight/index.js, src/blocks/icon/index.js, src/blocks/media-card/index.js, src/blocks/pricing-table/index.js, src/blocks/pricing-table/pricing-table-item/edit.js, src/blocks/pricing-table/pricing-table-item/index.js, src/blocks/row/layouts.js, src/blocks/services/edit.js, src/blocks/shape-divider/index.js, src/blocks/share/index.js
- Remove 'hr'
- Remove 'svg'
- Remove Ratios/Integers (50/50, 80/20, 4:3, 99 etc.)
- Remove 'coblocks'
- Remove 'gif'
- Remove 'github'
- Remove 'gist'
=> Remove i18n strings, clean up .pot file

changelog.txt, readme.txt
Updating the Readme and Changelog for the 1.13.0 release.
=> Updating the readme for 1.13.0

src/components/crop-settings/crop-control.js, src/components/crop-settings/index.js
After merging #749, CircleCi build started failing due to eslint issues.
https://circleci.com/gh/godaddy/coblocks/3537#tests/containers/0
This PR resolves all issues that were returned when running `npx grunt eslint` in the project.
=> Resolves ESLint issues introduced with the new Crop Control component.

src/components/responsive-tabs-control/styles/editor.scss
- Closes #819
**Icons in FF after fix**
**Icons in Edge after fix**
**Icons in Chrome after fix (no visible change)**
=> Center SVGs for responsive-tabs-control component

src/components/background/dropzone.js
=> Fix background image upload error

src/blocks/social-profiles/index.php
Just a minor tweak for continuity between blocks, in support of #850.
=> Minor text align class tweak

src/blocks/gallery-masonry/styles/style.scss
This PR applies suggested styling to resolve #837.
=> Add auto height and max-width to masonry block images

src/blocks/services/icon.js, src/blocks/services/service/icon.js
=> Update Services block icons

src/blocks/map/edit.js
=> Add disabled attribute to apply button

changelog.txt, readme.txt
Updating the Readme and Changelog for the 1.15.0 release.
=> Updating the readme for 1.15.0

src/blocks/map/edit.js
=> Add icon to Map block placeholder

gruntfile.js
Also fixes eslint error in `Gruntfile.js`
=> Remove development source files from the plugin

includes/class-coblocks-form.php
=> Add the Reply-To header to emails sent from the Form block

.circleci/config.yml, .dev/tests/jest/helpers.js, package.json, src/blocks/alert/test/deprecated.spec.js, src/blocks/author/test/deprecated.spec.js, src/blocks/buttons/test/deprecated.spec.js, src/blocks/click-to-tweet/test/deprecated.spec.js, src/blocks/gallery-carousel/test/deprecated.spec.js, src/blocks/gallery-masonry/test/deprecated.spec.js, src/blocks/gallery-stacked/test/deprecated.spec.js, src/blocks/hero/test/deprecated.spec.js, src/extensions/colors/apply-style.js, src/extensions/typography/apply-style.js, src/extensions/typography/apply-style.spec.js
**Ensure we're testing all the utilized attributes**
Adds an additional test to ensure we have variations available to test for an attribute the block has registered.
**We want to see exactly which variation value we're testing**
Stringify each variation's value in the test name to better expose what is being tested.
**Ensure we test attributes coming from filters**
We didn't have this ability until now. With filters being a great way to add new functionality to a block, we need to make sure ours do not break block validation.
**Display helpful information through a Jest test failure**
Currently, we check that all block objects returned from [`parse()`](https://github.com/WordPress/gutenberg/blob/359858da0675943d8a759a0a7c03e7b3846536f5/packages/blocks/src/api/parser.js#L388) have an …
=> Improve deprecation tests by exposing actionable information.

src/components/font-family/index.js
=> Stop system fonts from attempting to load from Google Fonts

src/blocks/accordion/styles/editor.scss, src/blocks/post-carousel/styles/style.scss, src/blocks/posts/styles/style.scss, src/blocks/social-profiles/styles/editor.scss, src/components/block-gallery/styles/style/_core-themes.scss, src/components/block-gallery/styles/style/_lightbox.scss
This PR simply adds proper SCSS variables in place where we should have already used them.
=> Use proper SCSS variables in block styles

src/blocks/accordion/accordion-item/edit.js
=> Improve placeholder text in the Accordion block

src/styles/editor.scss, src/styles/style/_columns.scss
This PR ensures that our columns classes do not override core or WooCommerce styling.
=> Ensure columns styling do not override core/WooCommerce styling

changelog.txt, readme.txt
Updating the readme and changelog for the 1.16.1 release.
=> Updating the readme for 1.16.1

src/blocks/share/block.json, src/blocks/share/index.js, src/blocks/share/index.php, src/blocks/share/test/save.spec.js
This block did not have deprecations. Instead I added a basic test on the save function to detect when we need to write a deprecation. Closes #875.
```
Tests:       9 passed, 9 total
Time:        2.287s
```
=> Improve Share block stability through block validation testing

src/blocks/social-profiles/block.json, src/blocks/social-profiles/index.js, src/blocks/social-profiles/index.php, src/blocks/social-profiles/test/save.spec.js
This block did not have deprecations. Instead I added a basic test on the save function to detect when we need to write a deprecation. Related to #876.
```
Tests:       9 passed, 9 total
Time:        3.34s
```
=> Improve Social Profiles block stability through block validation testing

.circleci/config.yml, .dev/tests/phpunit/src/blocks/post-carousel/test-index.php, .dev/tests/phpunit/src/blocks/social/test-index.php, package-lock.json, src/blocks/post-carousel/block.json, src/blocks/post-carousel/index.js, src/blocks/post-carousel/index.php
This block did not have deprecations. Instead I added basic PHP tests on the server rendered function. Related to #1030.
=> Improve Post Carousel block stability through block validation testing

.dev/tests/phpunit/src/blocks/posts/test-index.php, .dev/tests/phpunit/src/blocks/social/test-index.php, src/blocks/posts/block.json, src/blocks/posts/icons.js, src/blocks/posts/index.js, src/blocks/posts/index.php
This block did not have deprecations. Instead I added basic PHP tests on the server rendered function. Related to #1029.
=> Improve Posts block stability through block validation testing

src/components/dimensions-control/index.js, src/components/dimensions-control/styles/editor.scss
=> Enhance DimensionsControls with vw and vh units

src/blocks/gallery-collage/index.js
=> Add block preview for Collage Gallery block

src/components/visual-dropdown/styles/editor.scss
This PR tweaks the VisualDropdown just a tad to support 5.3 better.
=> Tweak VisualDropdown component for 5.3+

src/blocks/post-carousel/inspector.js, src/blocks/posts/inspector.js
=> Improve the column control of the Posts and Post Carousel blocks

changelog.txt, readme.txt
Updating the readme and changelog for the 1.17.0 release.
=> Updating the readme for 1.17.0

changelog.txt, readme.txt
Updating the readme and changelog for the 1.17.1 release.
No approval necessary, just recording this merge.
=> Updating the readme for 1.17.1

.dev/tests/phpunit/includes/test-coblocks-accordion-ie-support.php, src/blocks/accordion/accordion-item/edit.js, src/blocks/alert/edit.js, src/blocks/click-to-tweet/edit.js, src/blocks/features/feature/edit.js, src/blocks/food-and-drinks/edit.js, src/blocks/food-and-drinks/food-item/edit.js, src/blocks/gallery-collage/edit.js, src/blocks/gist/edit.js, src/blocks/highlight/edit.js, src/blocks/media-card/edit.js, src/blocks/services/service/edit.js
This PR adapts the existing `...` with the horizontal ellipsis `…` character in placeholders, following core Gutenberg's pattern.
=> Replace ... with horizontal ellipsis (…)

changelog.txt, readme.txt
Updating the readme and changelog for the 1.17.2 release.
No approval necessary, just recording this merge.
=> Updating the readme for 1.17.2

includes/class-coblocks-block-assets.php, src/blocks/gallery-collage/edit.js, src/blocks/gallery-collage/inspector.js, src/blocks/gallery-collage/save.js, src/blocks/gallery-collage/styles/style.scss, src/blocks/gallery-masonry/styles/style.scss, src/components/block-gallery/styles/style/_lightbox.scss
This enhancement will add a Lightbox toggle, script and cursor styles to the Collage block.
=> Add lightbox support to Collage block

changelog.txt, readme.txt
Updating the readme and changelog for the 1.17.3 release.
=> Updating the readme for 1.17.3

.circleci/config.yml, gruntfile.js
Generate CoBlocks translation files in `i18n` job on CircleCI and upload them to the artifacts for the build when any changes to `master` are detected. This includes any PRs merged into `master`, or any hot fixes pushed directly to `master`.
https://circleci.com/gh/godaddy-wordpress/coblocks/6319#artifacts/containers/0
=> Generate translation files on master changes

.circleci/config.yml
#1174 didn't seem to merge properly so this PR is to fix that.
=> Add a skip i18n flag on translation commits

.circleci/config.yml
Conditionally deploy the translations based on the commit message. `skip i18n` in the commit message will _not_ deploy the translations back to github.
=> Skip i18n conditional deployment

changelog.txt, readme.txt
Updating the readme and changelog for the 1.18.0 release.
=> Updating readme for 1.18.0

src/blocks/gallery-carousel/styles/style.scss
Closes #1199 
Resolves the issue with Safari, Edge, and IE11. Still functional in Chrome and FireFox.
=> Fix display issue with Flickity navigation buttons

changelog.txt, readme.txt
Updating the readme and changelog for the 1.19.0 release.
=> Updating readme for 1.19.0

src/blocks/row/column/block.json, src/blocks/row/column/edit.js
Refreshed #555 by branching off master and applying a similar changeset.
=> Use the new InnerBlocks renderAppender on the Row block

.dev/bin/deploy-plugin.sh
Adds the latest change log notes from `readme.txt` into the `Release Notes` here on Github.
=> Add change log contents to GitHub release notes

changelog.txt, readme.txt
Updating the readme and changelog for the 1.19.2 release.
=> Updating readme for 1.19.2

src/blocks/icon/deprecated/svgs.js, src/blocks/icon/svgs.js
Related to #1225 
This PR finishes ordering icon keywords alphabetically as was started in #1225.
=> Alphabetize icon block keywords

src/blocks/icon/deprecated/svgs.js, src/blocks/icon/svgs.js
The i18n team found a few mistakes in our icon block keywords.
=> Fix icon block keyword typos

README.md, changelog.txt, readme.txt
Updating the readme and changelog for the 1.20.0 release.
=> Updating readme for 1.20.0

src/blocks/buttons/test/buttons.cypress.js
New E2E tests for the Buttons block
=> Improve Buttons block stability through E2E testing

src/blocks/click-to-tweet/test/click-to-tweet.cypress.js
New E2E tests for the Click to Tweet block
=> Improve Click to Tweet block stability through E2E testing

src/blocks/form/test/form.cypress.js
New E2E tests for the Form block
=> Improve Form block stability through E2E testing

src/blocks/icon/test/icon.cypress.js
New E2E tests for the Icon block
=> Improve Icon block stability through E2E testing

src/blocks/share/test/share.cypress.js
New E2E tests for the share block
=> Improve Share block stability through E2E testing

src/blocks/social-profiles/test/social-profiles.cypress.js
New E2E tests for the social profiles block
=> Improve Social Profiles block stability through E2E testing

.dev/tests/cypress/helpers.js, src/blocks/accordion/test/accordion.cypress.js, src/blocks/features/block.json, src/blocks/features/edit.js, src/blocks/features/feature/block.json, src/blocks/features/feature/edit.js, src/blocks/features/inspector.js, src/blocks/features/test/features.cypress.js, src/blocks/services/inspector.js, src/components/heading-toolbar/index.js
This PR adds the headings control functionality/behavior that exists in the Services block to the Features block.
=> Control Feature block headings from the parent Features block

README.md
This PR adds our new plugin banner to the repo README:
=> Use new banner on the README

includes/class-coblocks-generated-styles.php
=> Skip empty values in generated styles from the DimensionsControl

.circleci/config.yml, changelog.txt, readme.txt
Updating the readme and changelog for the 1.20.1 release.
=> Updating the readme for 1.21.0

readme.txt
Swapped Tabor theme for Go as recommended, updated some various other copy.  Added callout for Go as companion theme.
**For action:** Recommend auditing block lists in plugin description--I noticed the menu block missing, not sure about others.
=> Misc updates to readme

src/blocks/form/edit.js
Code-quality related changes which improve the readability of the code and makes variable names contextually more appropriate.
Update variables names for code readability.
Tested in the editor with no issues. No change in functionality.
=> Update Form block variable names

package-lock.json
Regenerate package-lock.json file so Jest tests run/pass
Bug fix in the build process (non-breaking change which fixes an issue)
=> Regenerate package-lock.json file so Jest tests run/pass

class-coblocks.php, package.json, readme.txt
With the testing and changes from https://github.com/godaddy-wordpress/coblocks/pull/1380 CoBlocks is now tested with WP 5.4 RC2. 
Documentation changes. 
Tested in https://github.com/godaddy-wordpress/coblocks/pull/1380
=> Updated tested to value for to 5.4

src/blocks/author/styles/editor.scss, src/blocks/click-to-tweet/styles/style.scss, src/blocks/features/styles/editor.scss, src/blocks/form/styles/editor.scss, src/blocks/form/styles/theme.scss, src/blocks/gif/styles/editor.scss, src/blocks/gif/styles/style.scss, src/blocks/logos/styles/style.scss, src/blocks/posts/styles/editor.scss, src/blocks/pricing-table/styles/editor.scss
Cleans up excessive styling to make overriding our styles easier. 
Style changes. No breaking changes.
=> Minor style specificity clean-up

.dev/config/webpack.config.js, includes/class-coblocks-block-assets.php, package-lock.json, package.json, src/blocks/media-card/styles/editor.scss, src/blocks/media-card/styles/style.scss
Add RTL support for CoBlocks.
Fix Media Card block placeholder bug.
**Media Card - Before**
**Media Card - After**
New package added to CoBlocks [rtlcss-webpack-plugin](https://www.npmjs.com/package/rtlcss-webpack-plugin)
WP 5.5beta with and without the Gutenberg plugin.
WP 5.3.2 with and without the Gutenberg plugin.
=> Introduce RTL support

changelog.txt, readme.txt
Updating the changelog and readme for the 1.23.0 release.
=> 1.23.0 changelog and readme updates

.circleci/config.yml
Refactor the canary release so that deployments to the staging site are successful
=> Update canary release CircleCI deploy

src/blocks/events/index.php
=> Fix variable type in coblocks_render_events_block

CONTRIBUTORS.md
Simply adding @passatgt as a contributor for the #1461 PR 👏
=> Add passatgt as a contributor 🎉

.circleci/config.yml
Ensures that canary builds are available on WPNUX for testing.
=> Deploy canary build to wpnux

src/styles/style.scss
This PR closes #1488 by adding back the styles associated with custom formats.
=> Apply styles for formats

CONTRIBUTORS.md
Added some names from recent Pull Requests and Issues posted on GitHub.
=> Add some names to contributros.md

src/blocks/services/service/styles/editor.scss, src/blocks/services/styles/editor.scss
Update the services block selected state.
=> Update the services block selected state

docs/contributors/release.md
Adding documentation on our process for deploying new releases.
=> Documentation for new releases

README.md
Change npm install to yarn install to make sure we are using yarn.lock
=> Update Development Readme section

class-coblocks.php, package.json, readme.txt
With the changes from https://github.com/godaddy-wordpress/coblocks/pull/1608 https://github.com/godaddy-wordpress/coblocks/pull/1609 https://github.com/godaddy-wordpress/coblocks/pull/1610 and https://github.com/godaddy-wordpress/coblocks/pull/1602 CoBlocks has now been tested for compatiblity up to 5.5.
Update tested to value across CoBlocks
=> Update tested to value to 5.5

CONTRIBUTORS.md, readme.txt
Add fjarrett as a contributor and move appropriate contributors to the proper CONTRIBUTORS.md file.
=> Move appropriate contributors to the CONTRIBUTORS file (and add fjarrett) 

src/blocks/gallery-masonry/styles/editor.scss, src/extensions/lightbox-controls/styles/editor.scss
Fix the cursor hover state on offset and collage blocks.
Resolves #1644 
New style (non-breaking change which adds functionality)
Manually tested in the editor.
=> Fix cursor hover state on offset/collage blocks

CONTRIBUTORS.md
For efforts on https://github.com/godaddy-wordpress/coblocks/pull/1671
Thanks!
=> Add @WunderBart as a contributor 🎉

CONTRIBUTORS.md
=> Add Jon Surrell as a contributor 🎉

includes/class-coblocks-form.php, src/components/form-label-colors/label-color-wrapper.php
Resolved a number of errors reported by PHPCS.
Minor PHP tweaks.
Manually within the editor and front-end. E2E.
=> Resolve PHPCS errors on main

.github/labels.yml
name: "Hacktoberfest"
color: "ff8ae2"
description: "Issues/PRs related to Hacktoberfest: https://hacktoberfest.digitalocean.com"
=> Add Hacktoberfest label

src/blocks/map/edit.js, src/blocks/map/styles/editor.scss, src/blocks/map/test/map.cypress.js
The Map block placeholder has been updated with updated styles for a more consistent experience across blocks.
New experience.
Non breaking changes to SCSS and JavaScript.
Tested manually within the editor.
=> Enhance Map block placeholder with new styles

src/extensions/animation/controls.js
Using sentence case for the Remove Animation link
=> Animation to animation

src/extensions/animation/animation-types.js, src/extensions/animation/controls.js, src/extensions/animation/styles/editor.scss
=> Add icons for animations UI

src/blocks/alert/test/alert.cypress.js, src/blocks/author/test/author.cypress.js
The main branch had 2 failing tests. 
https://dashboard.cypress.io/projects/sovnn2/runs/1042/failures
This PR will address the two remaining test failures in the CI pipeline.
=> Fix failing tests for Author and Alert blocks

.circleci/config.yml
Leverage commands to reduce code duplication and to improve the readability of CI config. 
Changes are related to code readability and code quality. These changes make it easier to read and understand the Circle Ci config that we use for CoBlocks.
Tested by running config through the CI pipeline.
=> Improve Circle Ci configuration file readability

.stylelintrc.json, package.json, src/blocks/gallery-offset/styles/style.scss, src/blocks/icon/styles/editor.scss, src/blocks/media-card/styles/editor.scss, src/blocks/posts/styles/style.scss, src/blocks/pricing-table/styles/editor.scss, src/blocks/pricing-table/styles/style.scss, src/blocks/services/styles/legacy.scss, src/blocks/share/styles/style.scss, src/components/block-gallery/styles/editor/_core-themes.scss, src/components/block-gallery/styles/style/_carousel.scss, src/components/block-gallery/styles/style/_grid.scss, src/components/block-gallery/styles/style/_margin-bottom.scss, src/components/block-gallery/styles/style/_margin-left-negative.scss, src/components/block-gallery/styles/style/_margin-left.scss, src/components/block-gallery/styles/style/_margin-right-negative.scss, src/components/block-gallery/styles/style/_margin-right.scss, src/components/block-gallery/styles/style/_margin-top.scss, src/components/block-gallery/styles/style/_padding.scss, src/components/block-gallery/styles/style/gutter.scss, src/extensions/media-text-styles/styles/style.scss, src/styles/editor/columns.scss, src/styles/mixins.scss, src/styles/style/columns.scss, yarn.lock
Unifying CSS linting across projects
=> WPEX-923 Unifying CSS linting across projects

.circleci/config.yml, .dev/tests/jest/jest.config.js, package.json, yarn.lock
=> Enable coverage comments

src/extensions/animation/index.js
Add animation to core/media-text
=> WPEX-848 Add animation to core/media-text

class-coblocks.php, package.json, readme.txt
Bump tested up to version to 5.6.
=> Bump tested up to version to 5.6

docs/contributors/release.md
Minor changes to release process document. Made corrections to the standard release day and command used to release a new version.
Text.
=> Updates to release process document

src/extensions/layout-selector/editor.scss, src/extensions/layout-selector/layout-selector-results.js, src/extensions/layout-selector/test/layout-preview.spec.js
Fix flickering issue. Temporary fix until we have access to `<BlockPreview __experimentalOnReady>`
=> WPEX-990 Fix loading layouts visual

cypress.json, package.json, yarn.lock
Using new settings and versions to try for more consistent results.
=> Try Cypress Changes

CONTRIBUTORS.md, src/blocks/gist/gist.js
Fixes: #1801 
The PR will resolve the problem of console error.
It is non-breakable changes
Tested on my local development environment.
=> Fix console warning message to block

.circleci/config.yml
Adding DockerHub auth when pulling images.
=> Use DockerHub auth

src/blocks/services/edit.js, src/blocks/services/service/block.json, src/blocks/services/service/edit.js, src/blocks/services/service/save.js, src/blocks/services/service/styles/style.scss
Add Link to images within Service Item blocks
=> Add Link to images within Service Item blocks

.circleci/config.yml
Experimental PR to add a 7.4 unit testing job in CircleCI. Also confirmed outside of this experiment is compatibility with JS Jest tests.
The new job runs in CircleCi to test against PHP@7.4.15
Env variable XDEBUG_MODE=coverage must be set for the docker image for proper compatibility.
=> Try using PHP 7.4

class-coblocks.php, package.json, readme.txt
Bump tested to version for CoBlocks to WordPress 5.7
=> Bump tested to version of CoBlocks to 5.7

README.md
Removing old social links that are no longer relevant. Closes #1861
=> Remove social links from readme

src/blocks/gist/edit.js, src/blocks/gist/gist.js
This is a suggestion for a refactor of the Gist component to hooks. I think that it will allow to make a cleaner fix for #1331 after that.
Open to comments/improvements.
Refactoring
All the tests still pass.
=> Refactor Gist component to hooks

src/blocks/services/styles/editor.scss
Fix services block selected state box shadow.
Manually.
=> Fix services block selected state box shadow

docs/contributors/getting-started.md
Switch from `npm` to `yarn` in the doc
Documentation
=> Change npm to yarn in the doc

package.json, src/blocks/events/event-item/icon.js, src/blocks/events/event-item/index.js, yarn.lock
Change the icon of the event item.
Before : 
After : 
Visual change
=> Update Event Item icon

src/blocks/author/controls.js, src/blocks/author/edit.js, src/blocks/author/inspector.js
=> Convert Author block to React hooks

src/blocks/author/controls.js, src/blocks/click-to-tweet/controls.js, src/blocks/click-to-tweet/edit.js, src/blocks/click-to-tweet/inspector.js
=> Convert ClickToTweet block to React hooks

src/extensions/typography/styles/style.scss
=> ISBAT to edit text color within quote block within editor

src/blocks/social-profiles/controls.js, src/blocks/social-profiles/edit.js, src/blocks/social-profiles/inspector.js
This PR refactors the social blocks and associated components to use react hooks
=> refactor Social Profiles block to use hooks

src/blocks/alert/controls.js, src/blocks/alert/edit.js, src/blocks/alert/inspector.js
This PR refactors the alert block and related components to use react hooks
=> Refactor alert block and related components to use react hooks

src/blocks/dynamic-separator/edit.js, src/blocks/dynamic-separator/inspector.js
This PR refactors the dynamic separator blocks and related components to use react hooks
code refactor
=> refactor dynamic separator block to use hooks

README.md, readme.txt
Add OpenTable block to listing in the README.md and readme.txt.
Text change
=> Add OpenTable block to README

src/blocks/accordion/accordion-item/controls.js, src/blocks/accordion/accordion-item/edit.js, src/blocks/accordion/edit.js, src/blocks/accordion/inspector.js
Refactoring the following blocks to use a react hooks architecture:
- Accordion
=> refactor Accordion block to use hooks

src/blocks/share/controls.js, src/blocks/share/edit.js, src/blocks/share/inspector.js
This PR refactors the share block and its related components to use react hooks architecture.
=> refactor share block and related components to use react hooks

src/blocks/events/edit.js, src/blocks/events/event-item/edit.js
This PR refactors the events block and its related components to use a react hooks architecture.
=> refactor events block and related components to use react hooks

src/blocks/shape-divider/controls.js, src/blocks/shape-divider/edit.js, src/blocks/shape-divider/inspector.js
This PR refactors the shape divider block and its related components to use react hooks
=> refactor shape divider block and related components to use react hooks

.circleci/config.yml
- Update the Docker image to Node 14
- Remove dependencies and rebuild before executing the tests (not multithreaded, that was causing some of the issues).
Probably not the cleanest way to do it, but it works ;)
=> Fix build pipeline

src/blocks/map/edit.js, src/blocks/map/inspector.js, src/blocks/share/inspector.js
This PR converts the map block to a component using React hooks
code refactor
=> convert the map block to react hooks

src/blocks/logos/controls.js, src/blocks/logos/logos.js
This PR refactors the Logos block to implement React hooks architecture
Code refactor
Visually
=> refactor logos block to use react hooks

src/blocks/gif/controls.js, src/blocks/gif/edit.js, src/blocks/gif/inspector.js, src/blocks/gif/size.js
This PR refactors the gif block to use react hooks
code refactor
visually
=> Refactor gif block to use react hooks

src/blocks/icon/controls.js, src/blocks/icon/edit.js, src/blocks/icon/icon-size-select.js, src/blocks/icon/inspector.js
This PR refactors the Icon block to use React hooks
Code Refactor
Visually
=> refactor icon block to use react hooks

src/blocks/gallery-masonry/controls.js, src/blocks/gallery-masonry/edit.js, src/blocks/gallery-masonry/inspector.js
This PR refactors the gallery masonry block to use a React hooks architecture.
code refactor
visually
=> Refactor gallery masonry block to use react hooks

languages/fr_FR.json, src/blocks/gallery-offset/controls.js, src/blocks/gallery-offset/edit.js, src/blocks/gallery-offset/inspector.js
This PR refactors the gallery offset block to use React hooks
code refactor
visually
=> Refactor gallery offset block to use react hooks

.circleci/config.yml, .dev/performance/index.js
Modifications here allow incoming PRs to compare performance differences with the master branch. CI will detect with another branch is incoming and run the tests in CI. So far CI will report on performance and give us a percentage of change between the two branches.
In the future, we can explore a bot posting in the pull request with results as well as making performance results a required step with hard limits to prevent degradation.
=> Test incoming performance changes

src/blocks/share/styles/style.scss, src/blocks/social-profiles/edit.js, src/blocks/social-profiles/styles/editor.scss
- Fix style when Icon + label
- Add a confirm button for the URL
- Refactor code to simplify things
Visual fixes, UX improvements and code refactor
=> Social block improvements

src/blocks/accordion/index.js
Minor change to index.js for the accordion block. 
Minor JS change.
=> Add Accordion block example

src/blocks/services/example.js, src/blocks/services/index.js
Introduce an example for the services block.
=> Add services block example

src/blocks/social-profiles/edit.js, src/blocks/social-profiles/styles/editor.scss
Can submit social URL on Enter. Using same icon as the social-link component.
Visual changes and UX improvment
=> Improve Social Profiles url component

src/blocks/events/event-item/test/__snapshots__/save.spec.js.snap, src/blocks/events/event-item/test/save.spec.js, src/blocks/events/test/save.spec.js, src/blocks/events/test/transforms.spec.js
Adding tests for the Event and Event item blocks
Tests
Tested with tests
=> Add tests for Event block

package.json, src/blocks/faq/index.js, yarn.lock
=> Add new FAQ icon

src/blocks/faq/faq-item/test/__snapshots__/save.spec.js.snap
=> Update FAQ snapshots

.circleci/config.yml, phpcs.xml
This should decrease `phpcs` runs in CI builds.
=> Enable PHPCS cache

.dev/tests/cypress/support/commands.js, package.json, yarn.lock
Heavily inspired by @AnthonyLedesma 's PR #2043, upgrade Cypress end-to-end tests to Cypress 9.0
=> Upgrade to Cypress 9

.circleci/config.yml
Fix branch name variable, and shift version introduced in https://github.com/godaddy-wordpress/coblocks/pull/2154
=> Fix branch name

README.md
I think there's just a word missing here.
=> Add missing "is" to description in README

.dev/tests/cypress/helpers.js, src/extensions/layout-selector/test/layout-selector.cypress.js
Properly enter into the iframe to make sure it is loaded. Needed to make the test pass in WP 5.9
=> Fix layout test for WP 5.9

src/components/slider-panel/index.js
Update simple string used in the slider component for clarity.
Apply minor ESLint fixes to that same file.
=> update translation strings & ESLint fix

src/blocks/faq/edit.js, src/blocks/faq/index.js
Change FAQ block title and remove block when empty
=> Change FAQ block title and remove block when empty

src/blocks/faq/edit.js
Co-authored-by: Jason Lemay <jlemay@godaddy.com>
Checks if we have innerBlocks and compare with previous list. If there is no inner blocks remove completely.
=> Remove FAQ block when there is no child block

src/blocks/form/styles/editor.scss
=> Prevent "jumping" Form block layout within editor.

includes/class-coblocks-block-assets.php
Missing Dom Ready dependencies for Counter block.
=> Enqueue deps for counter block

src/utils/helper.js
Some blocks are not including icons, this introduce the check for that.
=> Verify icon before overriding

readme.txt
=> Fix some formatting to allow proper dom element hierarchy

src/blocks/icon/svgs-generated.js
Fix typoe: speach -> speech
Typo, string update.
=> Fix speech typo

package.json, src/blocks/gallery-collage/styles/style.scss, yarn.lock
Following the work in https://github.com/godaddy-wordpress/stylelint-config/pull/3 , update the stylelint-config version.
=> Fix css build step

includes/ical-parser/class-coblocks-ical.php, phpcs.xml
Resolve PHPCS/WPCS errors and warnings in the iCal parser class.
PHPCS was throwing a number of warnings and errors inside of the iCal parser class.
=> Fix iCal WPCS errors/warnings

includes/class-coblocks-block-assets.php
Update coblocks assets php file syntax.
=> Update block assets PHP syntax

includes/class-coblocks-block-assets.php, includes/class-coblocks-form.php
These are some sanitation and escape fixes that are needed to properly handle our data.
=> Sanitize email and properly escape URI

package.json, yarn.lock
Resolutions to remove the problems that `yarn audit` show.
=> Resolutions of dependencies : minimist, node-forge and simple-git

src/blocks/accordion/test/accordion.cypress.js, src/blocks/alert/test/alert.cypress.js, src/blocks/events/event-item/test/event-item.cypress.js, src/blocks/events/test/events.cypress.js, src/blocks/faq/test/faq.cypress.js, src/blocks/food-and-drinks/food-item/test/food-item.cypress.js, src/blocks/highlight/test/highlight.cypress.js, src/blocks/logos/test/logos.cypress.js, src/blocks/map/test/map.cypress.js, src/blocks/pricing-table/pricing-table-item/test/pricing-table-item.cypress.js, src/blocks/pricing-table/test/pricing-table.cypress.js, src/blocks/row/column/test/column.cypress.js, src/blocks/row/test/row.cypress.js, src/blocks/shape-divider/test/shape-divider.cypress.js
A few test fixes that prevent error messages.
=> Fix failing tests in WP 6.0 RC3

.github/CODEOWNERS
=> Remove code owners file

package.json, yarn.lock
Update `got` dependency and `@wordpress/scripts` dependencies
=> Update `got` and `@wordpress/scripts` dependencies

.dev/bin/install-wp-tests.sh, package.json, yarn.lock
Update `simple-git` dependency that we needed to update
=> Update simple-git dependencies

yarn.lock
Just updated up the `caniuse-lite` db in the lock file, since this letting us know this should be updated whenever we run `start` or `build`.
=> Update caniuse-lite db in lock file

src/extensions/site-design/color-palette-preview.js, src/extensions/site-design/data/actions.js
Fix when CoBlocks labs design styles/palette or custom colors are changed the editor should also update those values.
https://user-images.githubusercontent.com/5321364/211055354-0cae8cd9-5105-419f-ad0e-52ca527399f6.mp4
Manually.
ISBAT update a style using the CoBlocks labs design style and the editor styles should also update.
=> Fix editor styles not updating when a design style/palette or custom color is changed

src/blocks/dynamic-separator/block.json, src/blocks/dynamic-separator/index.js, src/blocks/dynamic-separator/inspector.js, src/blocks/dynamic-separator/test/dynamic-separator.cypress.js
Rename Dynamic HR to Dynamic Separator
Fixes #2462 
Block name change
=> Rename Dynamic HR to Dynamic Separator

src/extensions/site-content/index.js, src/extensions/site-content/test/post-menu-actions.spec.js, src/extensions/site-content/test/site-content.spec.js, src/extensions/site-design/test/color-palette-preview.spec.js, src/extensions/site-design/test/design-preview.spec.js, src/extensions/site-design/test/index.spec.js
=> convert initial files from enzyme to RTL

.github/workflows/deploy-create-release.yml, changelog.txt, readme.txt
Changes for 3.0.1 release and 6.2 compat.
=> bump readme

includes/class-coblocks-block-assets.php
Refactor one line to use `FILTER_SANITIZE_SPECIAL_CHARS` instead of `htmlspecialchars()`.
=> Refactor to use FILTER_SANITIZE_SPECIAL_CHARS

changelog.txt, readme.txt
=> Bump readme change logs

changelog.txt, readme.txt
Update the `changelog.txt` and `readme.txt` file with notes about what changed in 3.0.3.
=> Update changelog and readme with updated changelog

changelog.txt, readme.txt
Updates for 3.1.0 release for WP 6.3.
=> Update readme with new changelogs

changelog.txt, readme.txt
=> Bump changelog and readme for 3.1.2

includes/class-coblocks-form.php
Check that `$data` is an array before continuing.
=> Check that data is an array in the form block

src/blocks/counter/index.php, src/utils/duplicate-pattern.cypress.js
=> WPEX-3610 - add category for Coblocks patterns

.dev/tests/cypress/helpers.js, .github/workflows/test-wp-next.yml
=> Fix tests for WP 6.5 RC2

.github/workflows/deploy-create-artifact.yml, .github/workflows/deploy-create-release.yml, .github/workflows/deploy-wordpress-tags.yml, .github/workflows/deploy-wordpress.yml, .github/workflows/test-e2e-cypress.yml, .github/workflows/test-javascript.yml, .github/workflows/test-php-unit.yml, .github/workflows/test-php.yml, .github/workflows/test-wp-next.yml, .github/workflows/translation-localization.yml, .github/workflows/validation-coding-standards.yml
=> WP 6.5 RC4

changelog.txt, readme.txt
Update readme for `3.1.12` release.
=> Update readme and changelog for 3.1.12 release

changelog.txt, readme.txt
Update the changelog for the 3.1.14 release.
=> Update changelog for 3.1.14 release

changelog.txt, readme.txt
Update changelog and readme with 3.1.15 release notes.
=> Add changelog and readme updates for 3.1.15 release

src/components/common-action-modal/index.js
https://godaddy-corp.atlassian.net/browse/WPEX-3957
=> [WPEX-3957] Use URLSearchParams for query string generation
