godaddy-wordpress/coblocks

src/blocks/accordion/accordion-item/components/edit.js, src/blocks/author/components/edit.js, src/blocks/author/index.js, src/blocks/media-card/components/edit.js, src/blocks/pricing-table/pricing-table-item/components/edit.js, src/blocks/row/components/edit.js
Makes sure that when we insert an InnerBlocks block, the parent block gets selected instead of its child getting the selection right away.
=> Template inserter selection fixes, where innerBlocks are not selected when a block is added

src/extensions/advanced-controls/styles/editor.scss
But keeps it high enough to keep the resizable handle visible.
=> Lowers the z-index so that the block is not over the top toolbar

src/styles/editor/_icons.scss
I think it's better for our custom block icon UI to be removed in places like this, so that they fit into the UI better.
=> Fix the icon color within the transforms UI

includes/admin/class-coblocks-admin-footer.php
**Replace:**
`Thank you for using <a href="%1$s" target="_blank">%2$s</a>! Please <a href="%3$s" target="_blank">rate us on WordPress.org</a>.`
**With:**
`Thank you for using %1$s! Please <a href="%2$s" target="_blank">rate us on WordPress.org</a>.`
**Reason:**
Same as WordPress core, the plugin should avoid using unneeded HTML tags in translations strings.
The HTML tag was not removed, it was just got out of the translation string.
Why? Because this way the translator won't be able accidentally change the HTML tag while translating the string. In addition, it is much easier to translate strings without HTML tags, especially in RTL languages like Hebrew.
=> i18n: simplify the translation string

class-coblocks.php
You don't want your users to see bad review. Show them only 5 star review to encourage them to leave another 5 star review.
=> COBLOCKS_REVIEW_URL: link only to 5 star review

src/components/grid-control/index.js, src/components/grid-control/styles/editor.scss
=> Tweak UI for the Hero block CSS grid toolbar control

includes/admin/class-coblocks-feedback.php, src/blocks.js, src/common.scss
To prep for the 2.0 release. Closes #261.
Screenshot:
=> Update colors for the admin feedback notice and block icons

src/blocks/hero/components/controls.js, src/blocks/hero/components/icons.js, src/blocks/hero/components/inspector.js
Replaces the old "style" icon for an icon that is more representative of layouts. 
Screenshot (_between the align and text align toolbars_):
Closes #388
=> Add new layout icon for the Hero block

src/blocks/features/components/edit.js, src/blocks/features/feature/components/edit.js, src/blocks/hero/components/edit.js, src/blocks/media-card/components/edit.js, src/blocks/row/column/components/edit.js, src/blocks/row/components/edit.js, src/components/background/dropzone.js, src/components/background/index.js
Renames `BackgroundImageDropZone` to `BackgroundDropZone` and provides better labels for the drop zones, which used to reference image-only backgrounds. Closes #429
=> Rename BackgroundDropZone and tweak labels

includes/class-coblocks-accordion-ie-support.php, includes/class-coblocks-google-map.php
This PR adds support for has_block, instead of how we were originally checking for blocks. 
Closes #423.
=> Use has_block() to determine whether a $post contains specific blocks

src/blocks/features/components/controls.js, src/blocks/features/components/edit.js, src/blocks/features/components/inspector.js, src/blocks/features/feature/components/controls.js, src/blocks/features/feature/components/edit.js, src/blocks/features/feature/components/inspector.js, src/blocks/features/feature/index.js, src/blocks/features/index.js, src/blocks/hero/components/controls.js, src/blocks/hero/components/edit.js, src/blocks/hero/components/inspector.js, src/blocks/hero/index.js, src/blocks/media-card/components/controls.js, src/blocks/media-card/components/edit.js, src/blocks/media-card/components/inspector.js, src/blocks/media-card/index.js, src/blocks/row/column/components/controls.js, src/blocks/row/column/components/edit.js, src/blocks/row/column/components/inspector.js, src/blocks/row/column/index.js, src/blocks/row/components/controls.js, src/blocks/row/components/edit.js, src/blocks/row/components/inspector.js, src/blocks/row/index.js, src/components/background/controls.js, src/components/background/index.js, src/components/background/transforms.js
This PR tweaks a few component names so that they are not "image" specific, now that we support background videos globally.
=> Update background component names

package.json, readme.txt
Fix: Add proper escaping method for the Map block API key
=> Update Readme for v1.9.4

includes/admin/class-coblocks-getting-started-page.php
In preparation of the PHPCS implementation (#485) this PR checks the security nonce before redirecting the user to the welcome screen. This ensures that Coblocks was the activated plugin and the nonce security check passes.
Where possible we should avoid ignoring PHPCS warnings/errors (ie: `// phpcs:ignore`)
- Single quotes instead of double
- Spacing tweaks
- Returning early under certain conditions (eg: Nonce security check does not pass, `$activate_multi` is true, the plugin was activated via `WP_CLI` etc.)
=> Coblocks should validate the activate_plugin nonce before redirecting to the welcome screen

src/styles/style/_background-parallax.scss
Removes the appearance of scrolling based on OS-level animation preferences when the .has-parallax class is added to a block. Closes #499
=> [tiny] Fixes #499

includes/class-coblocks-accordion-ie-support.php
Hey awesome people!
Just wanted to let you know that in some edge cases like the 404.php templates there is a PHP warning since there is no `global $post` set. Here's a screenshot with the Twentynineteen theme:
A simple "check and quit early if" can avoid that, and there is no side effect since these pages won't need the custom style anyway.
I love the plugin, I hope I can contribute more soon.
=> Check if posts exists before trying to get the meta

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, class-coblocks.php, readme.txt
This PR replaces CoBlocks as the plugin author, updates the associated email addresses with GoDaddy's, and cleans up unnecessary bits in the readmes.
=> Update plugin information

includes/admin/class-coblocks-action-links.php
The PR removes the "Go Pro" action link (which was not actually rendering), and the action link pointing to the CoBlocks website (not necessary).
=> Remove extraneous plugin action links

src/blocks/pricing-table/styles/editor.scss
This PR resolves an issue where the pricing table is-selected outlines are not properly displaying, due to additional styling Gutenberg 5.7+ adds to every block.
=> Resolve Pricing Table outlines issue in Gutenberg 5.7+

src/blocks/hero/styles/style.scss
This PR resolves an issue where the Hero block content would not properly center, as reported via this [WordPress.org support ticket](https://wordpress.org/support/topic/hero-content-not-center/#post-11562250).
=> Resolve Hero block layout positioning issue

src/components/typography-controls/index.js
This PR closes #516 by setting the default value of the text transform SelectControl to `initial` instead of `normal`.
=> Fix text transform normal issue

src/blocks/media-card/styles/editor.scss
This PR removes the block mover from the card within the Media Card block (which is a Row block). There's only one top-level block nested, so displaying the mover is not necessary (as it doesn't move). 
**Before:** 
**After:**
=> Remove the block mover from the Media Card row block

src/blocks/map/components/inspector.js
This PR moves the Marker Size RangeControl to below the Height control, to ensure consistency in the UI when a Google Maps API key is added.
=> Move the Marker Size RangeControl below Height

src/extensions/advanced-controls/styles/editor.scss
This PR closes #567 by appropriately removing the auto-applied styles in Gutenberg 5.8+.
=> Fix extra top and bottom spacing in Gutenberg 5.8

src/blocks/row/components/inspector.js
This PR changes the "Layout" label of the Row block PanelBody component to "Style", which abides by the design patterns set by core. 
**Screenshot:**
=> Change the Row block layout panelBody label from "Layout" to "Style" 

includes/admin/class-coblocks-getting-started-page.php
Resolves #603 
Introduce a new filter, `coblocks_getting_started_submenu_parent_slug `, which allows the CoBlocks Getting Started page to be nested in a parent menu item, if the user chooses.
```php
/**
* Nest the CoBlocks Getting Started page inside the Tools admin menu
*
*
*/
function nest_coblocks_getting_started_menu_item( $parent_slug ) {
return 'tools.php';
}
add_filter( 'coblocks_getting_started_submenu_parent_slug', 'nest_coblocks_getting_started_menu_item' );
```
=> Introduce filter to nest Getting Started page in a parent menu item

src/blocks/food-and-drinks/inspector.js
There's a good bit of heavy lifting still needed on the css side of things, but now the framework is in place to add columns support in the future without deprecating the block.
=> Remove columns control for the Food & Drinks

.github/ISSUE_TEMPLATE/Bug_report.md
This PR tweaks the bug report template, adding separate sections for the WordPress version and Gutenberg version information requests.
=> Tweak the bug report issue template

src/blocks/features/index.js, src/blocks/share/index.js
The blocks already appear for their own names and I could not think of any other keywords to use that would not seem excessive. What are your thoughts?
=> Removed Icon Keyword From Share and Features Blocks

src/blocks/form/edit.js
Handles https://github.com/godaddy/coblocks/issues/618 & https://github.com/godaddy/coblocks/issues/619
Added options to `supports` object to disable `html` and `reusable` properties.
=> Disable reusable and editable HTML support for Form > Field blocks

.dev/bin/deploy-plugin.sh
Resolves the issue where removed files here on Github are not removed from the WordPress.org SVG repo during the deployment.
=> Deleted removed files from SVN during WordPress.org deployment

includes/class-coblocks-google-map-block.php, src/js/coblocks-google-maps.js
Appropriately rename `baAtts` to `coblocksGoogleMaps`in `wp_localize_script()`.
=> Update Google Maps localization script

src/blocks/pricing-table/components/edit.js, src/blocks/pricing-table/pricing-table-item/components/edit.js, src/blocks/pricing-table/pricing-table-item/index.js, src/components/background/styles.js
=> Add placeholder and ascending plan titles to the Pricing Table block

src/blocks/shape-divider/deprecated.js, src/blocks/shape-divider/edit.js, src/blocks/shape-divider/index.js, src/blocks/shape-divider/save.js, src/blocks/shape-divider/utils.js
Resolves an issue with multiple exports within the `index.js` file for the Shape Divider block. This was causing block validation errors in the editor and preventing the block from rendering on the front-end.
=> Move getDividerFromStyle to a new utils.js file

src/blocks/social-profiles/styles/editor.scss
This PR adds back the missing styles to the inline form we're using in the Social Profiles popover component, that were removed in Gutenberg 6.3. 
Closes #779
=> Add missing styles for <Gutenberg 6.3 inline form

src/blocks/icon/icon-size-select.js
This PR fixes #813, where the `height` attribute was not being saved when a size is applied.
=> Fix issue where icon sizes were not saved

src/blocks/icon/inspector.js
This PR updates the existing advanced/custom size controls for the Icon block, bringing it more inline with core settings. 
Also worth noting that I've changed the "Advanced" label to simply "Custom" which indicates what that button toggles (custom size) - "Advanced" does not imply anything concrete.
Before: 
This PR:
=> Improve Icon block custom size UI 

src/blocks/features/edit.js, src/blocks/features/feature/edit.js, src/blocks/features/feature/save.js, src/blocks/features/save.js, src/blocks/hero/deprecated.js, src/blocks/hero/edit.js, src/blocks/hero/save.js, src/blocks/media-card/edit.js, src/blocks/media-card/save.js, src/blocks/row/column/edit.js, src/blocks/row/column/save.js, src/blocks/row/edit.js, src/blocks/row/save.js, src/blocks/shape-divider/edit.js, src/blocks/shape-divider/save.js
- Closes #822
- The issue seemed to have been a JavaScript error. 
* `coblocks` attribute was coming into deprecated function as undefined.
* By handling the `coblocks` attribute, the deprecation continues to run which allows typical access to editor.
* Upon page update the hero block works as expected. 
**Editing + Updating a page after fix in place**
=> Fix Hero white-screen when deprecating

src/blocks/alert/edit.js, src/blocks/alert/index.js, src/blocks/alert/styles/editor.scss, src/blocks/alert/styles/style.scss, src/common.scss
Related: #781 
The above PR was merged in before a deprecation was available. This PR resolves any issues with the `className` switch for the alert block styles. The conversion happens within the `componentDidMount` method of the Alert block's `Edit` component.
Because this is a `className` change and the removed attribute did not effect the rendered HTML, a block validation error is not thrown. An attempt was made to force a failure using the `isEligible` check within the deprecation, which worked except that we could not replace the old `is-{type}-alert` class with the new `is-style-{type}`. I believe this is because the `customClassName` block support hooks into the `edit` function of the block.
Existing deprecations were tested and passed without issues.
In my opinion, the behavior of …
=> Convert Alert class is-{type}-alert to is-style-{type}

src/blocks/pricing-table/styles/style.scss
Closes #843
Before: 
After: 
After, with two tables:
=> Add proper support for singular pricing tables

includes/class-coblocks-form.php
Introduce a new filter (`coblocks_form_disable_emails`) which allows users to short circuit the form submission and prevent `wp_mail()` from firing.
Additionally introduced a new action (`coblocks_before_form_submit`) that allows users to catch the form data before the emails are disabled. The thought here is that users can disable the email functionality, but still hook in and capture/utilize the submitted form data as they need.
```php
/**
* Disable form submission emails
*/
add_filter( 'coblocks_form_disable_emails', '__return_true' );
/**
* Set a custom success message to mimic a successful form submission
*
* @return string Form submission success message
*/
function coblocks_form_sent_message() {
return __( 'Your message was sent.', 'textdomain' );
}
add_filter( …
```
=> Introduce a filter to prevent wp_mail from firing in the form block

src/blocks/features/styles/style.scss
Previously, the last paragraph would have it's margin bottom removed. This PR makes the last "anything" have its margin bottom removed. For example, if a user adds a button to the Feature block, it'll now also have it's margin removed.
=> Remove margin bottom on the last item within the Feature block

src/blocks/hero/styles/editor.scss
- Closes #826.
- I found that z-index of 60 was the minimum index that works in this case. 
- Tested block as user and found no negative side effect.
=> Change z-index to 60 for hero block controls.

changelog.txt, gruntfile.js, languages/coblocks.pot, readme.txt
Updating the Readme and Changelog for the 1.14.0 release.
Also using a slightly different format by utilizing Markdown [like the Gutenberg plugin](https://plugins.trac.wordpress.org/browser/gutenberg/trunk/readme.txt#L80). I liked the format a lot and it looks nice in the admin when clicking "View Details". It also exposes our GitHub a bit more with links to the PR of each change.
Contains everything added in the [latest milestone](https://github.com/godaddy/coblocks/milestone/13)
This PR also added our POT file into the version bump script on deploy.
=> Updating the readme for 1.14.0

src/blocks/gallery-carousel/block.json, src/blocks/gallery-carousel/edit.js, src/blocks/gallery-carousel/save.js
Tested to ensure the deprecation from 1.13 to 1.14 (today's release) is unaffected, and that we won't need another deprecation for 1.14 to the next release, which will include thumbnail and responsive height support for the Carousel block via #839.
=> Add new attributes for future thumbnails and responsiveHeight options

src/blocks/gallery-carousel/index.js, src/blocks/gallery-masonry/index.js, src/blocks/gallery-stacked/index.js, src/components/block-gallery/shared/transforms.js
This PR adds the functionality to remove margin top and bottom from the gallery blocks. Opting into `coBlocksSpacing ` adds the toggles to the Advanced panel within the Settings Sidebar.
=> Add coBlocksSpacing to galleries

src/blocks/share/edit.js, src/blocks/share/index.php
- Related to #850.
- No deprecation needed on server-side rendered blocks
- Tested with and without Gutenberg plugin.
- Tested in FireFox, Chrome, and IE11.
=> convert Share block to use alignment classnames

src/blocks/alert/deprecated.js, src/blocks/alert/edit.js, src/blocks/alert/save.js
- Related to #850.
- Found that attributes were not being properly imported in deprecated.js.
- Added new deprecated save function to handle blocks with inline style. 
- Tested with and without Gutenberg plugin.
- Tested in FireFox, Chrome, and IE11.
=> convert Alert block to use alignment classnames

src/blocks/click-to-tweet/deprecated.js, src/blocks/click-to-tweet/edit.js, src/blocks/click-to-tweet/index.js, src/blocks/click-to-tweet/save.js
- Related to #850.
- Added new deprecated save function to handle blocks with inline style.
- Tested with and without Gutenberg plugin.
- Tested in FireFox and Chrome.
=> convert Click-to-Tweet block to use alignment classnames

src/blocks/row/column/deprecated.js, src/blocks/row/column/edit.js, src/blocks/row/column/save.js
- Related to #850.
- Added new deprecated save function to handle blocks with inline style.
- Tested with and without Gutenberg plugin.
- Tested in FireFox, Chrome, and IE11.
=> convert Row block to use alignment classnames

src/blocks/row/styles/editor.scss
- Closes #891.
- Change seems to be related to structure changes with the default editor inserter with Gutenberg 6.5.
- This proposed change handles the display in FireFox, Chrome, IE11 and Edge.
=> Update Row block CSS to hide default appender

src/blocks/gallery-carousel/index.js
This was left over from block.json refactors. Pull request for code cleanup.
=> Remove category setup from Carousel settings

src/blocks/logos/index.js
- Closes #919 
- Add icon for Logos & Badges block to index exports.
=> Add icon to Logos & Badges block placeholder

README.md
Extra spacing left within the bullet list resulted in unexpected styles. 
Pull request to resolve this issue.
=> Remove extra spacing on README

src/blocks/food-and-drinks/inspector.js
This PR tweaks the UX of the Styles panel within the Food & Drinks block, to follow Gutenberg core's updated patterns. Instead of the Styles panel opening by default, it's closed.
=> Make the Styles panel on Food & Drinks block not open on default

src/blocks/map/index.js
The PR updates the Map block description from `Add an address and drop a pin on a Google map.` to `Add an address or location to drop a pin on a Google map.` to reflect the ability to simply search for a location - instead of needing an address. 🗺
=> Tweak Map block description

src/blocks/icon/deprecated.js, src/blocks/icon/edit.js, src/blocks/icon/index.js, src/blocks/icon/save.js
This PR finishes up the work for #850, which replaces the inline style alignments with `.has-text-align-{value}`. Deprecation has been added to the Icon block.
=> Convert Icon block to use alignment classes

.dev/tests/phpunit/includes/admin/test-coblocks-getting-started-page.php, includes/admin/class-coblocks-getting-started-page.php
Pull request to remove redirect action which occurs during plugin activation. We have had a number of support requests arise related to this getting started page. Removing the redirect should be a first step until we can add more value to the getting started page. 
**Related support request**
https://wordpress.org/support/topic/fails-with-wordpress-5-3-beta1-46334/
=> Remove redirect action when activating CoBlocks

src/blocks/author/styles/editor.scss, src/blocks/author/styles/style.scss, src/blocks/features/styles/style.scss, src/blocks/media-card/styles/style.scss, src/blocks/row/styles/editor.scss, src/blocks/row/styles/style.scss
This PR resolves #398 which originally was added before color settings used color classes, which add enough specificity to not need inherit fallback - which in itself caused a bunch of style issues.
=> Remove inherit colors fallback

package-lock.json, package.json
Closes: #915 
Using [husky](https://www.npmjs.com/package/husky) to define our `pre-commit` hook and utilizing [lint-staged](https://www.npmjs.com/package/lint-staged) which allows us to run eslint and jest tests only on staged files.
=> Run eslint and jest tests pre-commit

.dev/bin/update-po.sh
From what I can tell, the `declare` statement doesn't serve any purpose in the `update-po.sh` script. This PR removes it, which also conveniently avoids a build warning on macOS, where `-A` is not a supported argument.
=> i18n: Remove unnecessary `declare` statement.

src/blocks/alert/deprecated.js, src/blocks/alert/test/__snapshots__/save.spec.js.snap, src/blocks/alert/test/deprecated.spec.js, src/blocks/alert/test/save.spec.js
Provides deprecation tests for the Alert block as part of #854. 
```
Tests:       59 passed, 59 total
Time:        2.504s
```
=> Improve Alert block stability through block validation testing

.dev/bin/deploy-plugin.sh
Resolves #905 
Create a tag directory on WordPress.org SVN during plugin deployments.
=> Tag each release of CoBlocks on the WordPress.org SVN during deployment

.github/CODEOWNERS
This file basically recommends each of us as a reviewer when a PR is submitted. Right now when we've been submitting PRs, we've had to search for each person to request a review from. With this change we will display right in the suggested reviewers section with "Request" links.
=> Add a CODEOWNERS file for GitHub to provide better reviewer suggestions

src/sidebars/block-manager/deprecated.js, src/sidebars/block-manager/index.js
We had a minor regression after merging #948 that is causing our custom Block Manager to load even if we detect the Block Manager exists in Core. The issue surrounds the conditional around checking for this existence before loading our plugin.
This PR fixes that conditional and improves its detection slightly.
**NOTE** This regression was not deployed to users but needs to be resolved before the next release.
=> Prevent the Block Manager from loading in WordPress 5.2+

src/blocks/accordion/accordion-item/test/__snapshots__/save.spec.js.snap, src/blocks/accordion/accordion-item/test/save.spec.js, src/blocks/accordion/test/__snapshots__/save.spec.js.snap, src/blocks/accordion/test/save.spec.js
This block did not have deprecations. Instead I added a basic test on the save function to detect when we need to write a deprecation. Related to #853.
```
Snapshots:   2 passed, 2 total
Time:        2.402s
```
=> Improve Accordion block stability through block validation testing

src/blocks/author/test/__snapshots__/save.spec.js.snap, src/blocks/author/test/deprecated.spec.js, src/blocks/author/test/save.spec.js
Provides deprecation tests for the Author block as part of #855.
```
Tests:       38 passed, 38 total
Snapshots:   1 written, 1 total
Time:        3.293s
```
=> Improve Author block stability through block validation testing

src/blocks/buttons/test/__snapshots__/save.spec.js.snap, src/blocks/buttons/test/deprecated.spec.js, src/blocks/buttons/test/save.spec.js
Provides deprecation tests for the Button block as part of #856. 
```
Tests:       21 passed, 21 total
Time:        2.751s, estimated 3s
```
=> Improve Button block stability through block validation testing

src/blocks/click-to-tweet/test/__snapshots__/save.spec.js.snap, src/blocks/click-to-tweet/test/deprecated.spec.js, src/blocks/click-to-tweet/test/save.spec.js
Provides deprecation tests for the Click to Tweet block as part of #857. 
```
Tests:       31 passed, 31 total
Time:        2.409s
```
=> Improve Click to Tweet block stability through block validation testing

src/blocks/dynamic-separator/test/__snapshots__/save.spec.js.snap, src/blocks/dynamic-separator/test/save.spec.js
This block did not have deprecations. Instead I added a basic test on the save function to detect when we need to write a deprecation. Related to #858.
```
Snapshots:   1 written, 1 total
Time:        2.339s
```
=> Improve Dynamic Separator block stability through block validation testing

src/blocks/features/feature/test/__snapshots__/save.spec.js.snap, src/blocks/features/feature/test/save.spec.js, src/blocks/features/test/__snapshots__/save.spec.js.snap, src/blocks/features/test/save.spec.js
This block did not have deprecations. Instead I added a basic test on the save function to detect when we need to write a deprecation. Related to #859.
```
Snapshots:   1 written, 1 passed, 2 total
Time:        3.839s
```
=> Improve Features block stability through block validation testing

src/blocks/gallery-masonry/test/__snapshots__/save.spec.js.snap, src/blocks/gallery-masonry/test/deprecated.spec.js, src/blocks/gallery-masonry/test/save.spec.js
Provides deprecation tests for the Masonry Gallery block as part of #863.
```
Tests:       317 passed, 317 total
Time:        4.653s
```
=> Improve Masonry Gallery block stability through block validation testing

src/blocks/gallery-carousel/test/__snapshots__/save.spec.js.snap, src/blocks/gallery-carousel/test/deprecated.spec.js, src/blocks/gallery-carousel/test/save.spec.js
Provides deprecation tests for the Carousel Gallery block as part of #862.
```
Tests:       610 passed, 610 total
Time:        4.867s
```
=> Improve Carousel Gallery block stability through block validation testing

src/blocks/map/inspector.js
Resolves #950 
- Updated the 'Height in pixels' slider to a number input, to follow Gutenberg's UX pattern.
- Also, Shifted the 'Height in pixels' control above the 'Zoom Level' settings, as this looked better than having the number input in between the two slider controls.
- Removed `max` attribute from height input, so the input field width better adheres to Gutenberg's UX pattern.
________________
=> Convert map height slider control to number input

includes/class-coblocks-block-assets.php, src/blocks.js, src/formats/index.js, src/formats/uppercase/index.js
Resolves #980.
Works with and without Gutenberg active. Setting `in_footer` to `false` and adding `wp-editor` and `wp-rich-text` as dependencies to the `dist/blocks.build.js` registered script solved it.
=> Resolve missing text format controls because of missing script dependencies

.dev/bin/update-po.sh, languages/coblocks-da_DK.po, languages/coblocks-de_DE.po, languages/coblocks-el.po, languages/coblocks-es_ES.po, languages/coblocks-fi.po, languages/coblocks-fr_FR.po, languages/coblocks-hi_IN.po, languages/coblocks-id_ID.po, languages/coblocks-it_IT.po, languages/coblocks-ja.po, languages/coblocks-ko_KR.po, languages/coblocks-mr.po, languages/coblocks-nb_NO.po, languages/coblocks-nl_NL.po, languages/coblocks-pl_PL.po, languages/coblocks-pt_BR.po, languages/coblocks-pt_PT.po, languages/coblocks-ru_RU.po, languages/coblocks-sv_SE.po, languages/coblocks-th.po, languages/coblocks-tr_TR.po, languages/coblocks-uk.po, languages/coblocks-vi.po, languages/coblocks-zh_CN.po, languages/coblocks-zh_TW.po, languages/coblocks.pot, package.json
- Rebuild the translations.
- Remove `npm run babel:json` since the generated `.json` files were not used.
- Run `npm run babel:build` when we tag a new version to Github (`npm version major|minor|patch`). This will generate a new .pot file, merge the changes into each .po file and commit them back up to Github.
=> Fix .pot/.po translations, add i18n generation to build process

src/sidebars/block-manager/components/modal.js, src/sidebars/block-manager/components/options/disable-blocks.js, src/sidebars/block-manager/deprecated.js
This PR updates the soon to be deprecated `wp.data.select( 'core/editor' ).getBlocks()` to `wp.data.select( 'core/block-editor' ).getBlocks()` that's within the CoBlocks Block Manager.
=> Fix deprecation for the CoBlocks Block Manager

src/blocks/gallery-carousel/controls.js, src/blocks/gallery-collage/controls.js, src/blocks/gallery-masonry/controls.js, src/blocks/gallery-stacked/controls.js, src/utils/helper.js
Resolves #983 
Fixes image URLs getting stripped when a gallery is updated.
=> Fix image links being erased when a Gallery block is updated

src/blocks/icon/block.json, src/blocks/icon/edit.js, src/blocks/icon/index.js, src/blocks/icon/inspector.js
- Closes #899 
- Removed `iconRand` attribute.
- Set icon default to `''` (unset).
- Static icon used for style previews.
* I chose aperture because this style shows the difference between filled and outlined well. 
- No deprecation needed from my testing.
=> Ensure style previews of the Icon block display the selected icon

src/blocks/row/controls.js
=> Do not show layout styles toolbar until a layout is selected

src/blocks/map/inspector.js
Closes #918
Added `componentDidMount` function to reassign the state for the `apiKey`. This makes it so that the input field is autofilled with the 'saved' `apiKey` whenever the inspector is opened.
=> Improve the Map block Google Maps API key UX

src/blocks/accordion/accordion-item/edit.js, src/blocks/accordion/accordion-item/styles/style.scss
This PR fixes #888, which was caused by limited the kind of blocks that could be placed within an Accordion Item block. The limitation has been lifted and I added a slight style tweak to ensure that fullwidth images don't flow out of the bounds of the Accordion Item.
=> Remove allowedBlocks limitation from the Accordion Item

src/blocks/gif/test/__snapshots__/save.spec.js.snap, src/blocks/gif/test/save.spec.js
This block did not have deprecations. Instead I added a basic test on the save function to detect when we need to write a deprecation. Related to #865.
```
Time:        1.75s, estimated 2s
```
=> Improve Gif block stability through block validation testing

src/blocks/gist/deprecated.js, src/blocks/gist/test/__snapshots__/save.spec.js.snap, src/blocks/gist/test/deprecated.spec.js, src/blocks/gist/test/save.spec.js
Provides deprecation tests for the Gist block as part of #866.
```
Tests:       28 passed, 28 total
Time:        2.708s
```
=> Improve Gist block stability through block validation testing

src/blocks/logos/test/__snapshots__/save.spec.js.snap, src/blocks/logos/test/save.spec.js
This block did not have deprecations. Instead I added a basic test on the save function to detect when we need to write a deprecation. Related to #868.
```
Time:        2.85s, estimated 3s
```
=> Improve Logos block stability through block validation testing

src/blocks/map/test/__snapshots__/save.spec.js.snap, src/blocks/map/test/deprecated.spec.js, src/blocks/map/test/save.spec.js
Provides deprecation tests for the Map block as part of #869.
```
Tests:       125 passed, 125 total
Time:        3.111s
```
=> Improve Map block stability through block validation testing

src/blocks/media-card/test/__snapshots__/save.spec.js.snap, src/blocks/media-card/test/save.spec.js
This block did not have deprecations. Instead I added a basic test on the save function to detect when we need to write a deprecation. Related to #870.
```
Time:        2.962s, estimated 3s
```
=> Improve Media Card block stability through block validation testing

src/blocks/pricing-table/pricing-table-item/test/__snapshots__/save.spec.js.snap, src/blocks/pricing-table/pricing-table-item/test/save.spec.js, src/blocks/pricing-table/test/__snapshots__/save.spec.js.snap, src/blocks/pricing-table/test/deprecated.spec.js, src/blocks/pricing-table/test/save.spec.js
Provides deprecation tests for the Pricing Table block as part of #870.
```
Test Suites: 3 passed, 3 total
Tests:       110 passed, 110 total
Snapshots:   2 passed, 2 total
Time:        2.795s, estimated 3s
```
=> Improve Pricing Table block stability through block validation testing

includes/admin/class-coblocks-getting-started-page.php
In 5.3 Beta, WordPress core has introduced a new parameter to be used when adding menu pages. Warnings were thrown until a parameter was properly passed into this function. 
Works on 5.2.3 and 5.3 Beta. Works with and without Gutenberg.
Resolves WordPress.org support requests:
https://wordpress.org/support/topic/add_submenu_page-call-uses-a-string-for-position/
https://wordpress.org/support/topic/activating-the-plugin-on-5-3-beta3-produces-php-warnings/
=> Resolve PHP warnings with WordPress 5.3 Beta

src/blocks/hero/block.json, src/blocks/hero/deprecated.js, src/blocks/hero/test/__snapshots__/save.spec.js.snap
Resolves #729 
Removing the default value for the hero is the simplest approach to resolving #729 . When you clear a color value, it's set to `undefined`. During the save routine, in core, if the value is `undefined` and a `default` setting exists, it falls back to that.
Without introducing additional login and checks, removing the default value from the background color for the hero block is the easiest approach. @richtabor @jrtashjian @paranoia1906 Do you think this is our best approach?
=> Fix the block validation error when the Hero block background color is removed

src/blocks/services/service/edit.js, src/blocks/services/service/styles/editor.scss, src/blocks/services/service/styles/style.scss
Resolves #847.
We were missing a className on the `MediaPlaceholder` component which prevented styles being shared between the placeholder and the actual `figure` markup. An additional padding override was necessary as well.
**After**
=> Ensure image placeholders maintain aspect ratio of the selected style

src/blocks/services/styles/editor.scss
This PR removes the excess padding on the Services block image placeholders, which is added by Gutenberg.
**Before:** 
**After:**
=> Remove excess padding from Services placeholders

includes/class-coblocks-block-assets.php
Removes the `time()` version param in favor of `COBLOCKS_VERSION`
=> Use COBLOCKS_VERSION when registering scripts

src/blocks/services/service/test/__snapshots__/save.spec.js.snap, src/blocks/services/service/test/save.spec.js, src/blocks/services/test/__snapshots__/save.spec.js.snap, src/blocks/services/test/save.spec.js
This block did not have deprecations. Instead I added a basic test on the save function to detect when we need to write a deprecation. Related to #873.
```
Snapshots:   1 written, 1 passed, 2 total
Time:        2.812s, estimated 3s
```
=> Improve Services block stability through block validation testing

src/blocks/shape-divider/deprecated.js, src/blocks/shape-divider/test/__snapshots__/save.spec.js.snap, src/blocks/shape-divider/test/deprecated.spec.js, src/blocks/shape-divider/test/save.spec.js
Provides deprecation tests for the Shape Divider block as part of #874.
```
Tests:       86 passed, 86 total
Time:        2.879s, estimated 3s
```
=> Improve Shape Divider block stability through block validation testing

.dev/tests/phpunit/includes/test-coblocks-body-classes.php, includes/class-coblocks-body-classes.php
This PR adds a the Twenty Twenty default theme to the list of theme names that get appended to the body class if active. This way we can add theme-specific support for default themes.
=> Add Twenty Twenty as an auto-generated theme classes

class-coblocks.php
This PR replaces the "Cheating Huh?" with a less insulting message: "_Something went wrong._" This follows [this change in WordPress](https://core.trac.wordpress.org/ticket/38332) ([trac](https://core.trac.wordpress.org/changeset/42719)).
=> Replace "Cheating Huh?" with a less insulting message

src/blocks/gallery-collage/test/__snapshots__/save.spec.js.snap, src/blocks/gallery-collage/test/save.spec.js
This block did not have deprecations. Instead I added a basic test on the save function to detect when we need to write a deprecation. Related to #1031.
```
Time:        2.601s, estimated 3s
```
=> Improve Collage Gallery block stability through block validation testing

src/styles/style/_columns.scss
This PR scopes recent `.column` styles to the CoBlocks block that needs them, avoiding possible layout changes in theme markup.
This seems the simplest approach for a fix; was the greedy selector intentional because of future plans for other blocks maybe? In that case, something else may be more appropriate.
Fixes: #1033
=> Posts block: Scope column styles to the Posts block.

src/blocks/gallery-collage/styles/editor.scss, src/blocks/gallery-collage/styles/style.scss
Closes #1062.
Pull request add `margin: inherit` to `li` elements scoped for collage block. This change allows correct display in TwentyTwenty. This change still looks correct in TwentyNineteen, TwentySeventeen and Barebones theme (underscores).
=> Fix Collage Block layouts for the TwentyTwenty theme

src/blocks/gist/controls.js
This PR removes the file text input and the meta option icon from the Gist block, maintaining those extraneous only within the block's Settings Sidebar.
=> Clean up Gist block toolbar

src/blocks/author/edit.js
Closes #1049 
Unable to pass `keepPlaceholderOnFocus` prop to `core/button` so the button does not share the behavior. How do we feel about possibly converting to a RichText component instead? Other ideas?
=> Add keepPlaceholderOnFocus prop to Author block text placeholders

src/blocks/form/edit.js
Enable the following core blocks so they can be used within the form block:
Note: All child blocks with the registered parent as `coblocks/form` will automatically be enabled in the `ALLOWED_BLOCKS` array, thus why I've removed the form child blocks from it.
=> Enable certain core blocks in the form block

src/blocks/gif/edit.js, src/blocks/gist/edit.js, src/blocks/gist/gist.js, src/blocks/gist/styles/editor.scss, src/blocks/row/edit.js
Closes #1045 
This request corrects the icon used for Gif and Gist blocks.
**Before:**
**After:**
=> Use BlockIcon component for Placeholder Icons

src/blocks/accordion/accordion-item/styles/editor.scss, src/blocks/accordion/accordion-item/styles/style.scss, src/blocks/accordion/styles/style.scss
This PR tweaks the default background color of the accordion to use a `hsla` value, instead of a hex value. This way, the background color of the accordion displays well regardless of the page background color.
This was originally discovered while reviewing the block within TwentyTwenty. 
I'm using the same background color default we're using for our Pricing Table block.
=> Adjust Accordion block default background color for improved theme compatibility

src/components/visual-dropdown/styles/editor.scss
I have two commits on this branch and am looking for design feedback.
Commit `2f15c96` accomplishes a similar look to WP 5.3. This route give the placeholder a typical look in the editor when viewing in 5.2.4. 
**WP 5.3**
https://prnt.sc/pmpsyk
**WP 5.2.4**
https://prnt.sc/pmpt84
Commit `9b8962b` is using `theme(primary)` to set SVG and border colors for button. This route accomplishes a similar look to WP 5.3  but effects 5.2.4 as well. 
**How it looks in 5.3 and 5.2.4**
https://prnt.sc/pmpsit
=> Allow theme colors in Row block placeholder

src/blocks/shape-divider/index.js
Closes #1043 
Removes the example set for Shape Divider block.
=> Remove block preview example for Shape Divider block

src/blocks/gist/styles/style.scss
Closes #1064.
We can accomplish this by setting the `table-layout` explicit auto. This allows the gist table to render correctly in TwentyTwenty, TwentyNineteen, TwentyEighteen, SoHo, and Barebones theme (underscores).
=> Fix code display styles of the Gist block with the TwentyTwenty theme

package.json
Looks like grunt references this version for the find/replace actions. This change is part of the 5.3 compatibility testing.
=> Bump WordPress Core support to 5.3

src/blocks/gif/edit.js
While testing WP 5.3 RC I found that the Gif block references `$` variable to access `jQuery`. At time of testing 5.3 RC has removed `$` from `window` while `jQuery` variable remains. This change would allow compatibility **with** and **without** WordPress 5.3 and would also follow the best practice that is already used by CoBlocks to reference the `jQuery` variable.
=> Use the jQuery global to avoid script conflicts with Gif block

src/extensions/advanced-controls/styles/style.scss
This PR applies a margin-top and margin-bottom !important property to top-level `.wp-block` classes, where the Advanced spacing controls are adding `mb-0` and `mt-0` classes. 
We don't want our base utilities to override, so this PR addresses only `mb-0` and `mt-0` classes assigned to the top-level block div.
=> Add !important properties for the advanced top/bottom margin

src/extensions/colors/index.js, src/extensions/colors/inspector.js
Gutenberg 5.8 adds support for applying a text color to the the core Heading block. This PR removes our custom Color Settings PanelBody as its not needed any longer.
**Before**
**After**
=> Remove custom Color Settings for the heading block

src/blocks/dynamic-separator/deprecated.js, src/blocks/dynamic-separator/edit.js, src/blocks/dynamic-separator/index.js, src/blocks/dynamic-separator/save.js, src/blocks/dynamic-separator/styles/editor.scss, src/blocks/dynamic-separator/styles/style.scss
This PR closes #1063, fixing the default HR styling TwentyTwenty applies to all `<hr>` elements within `.entry-content`.
Before: 
After:
=> Tweak Dynamic HR styling for TwentyTwenty

src/blocks/gallery-collage/inspector.js, src/blocks/posts/inspector.js
Closes #1053 
Simply wrapping the `ButtonGroup` in a `PanelRow` component puts the `ButtonGroup` on it's own line.
**Collage Gallery Block**
**Posts Block**
=> Fix label position on Gutter and Thumbnail size controls.

composer.lock, includes/admin/class-coblocks-action-links.php, includes/admin/class-coblocks-crop-settings.php, includes/admin/class-coblocks-install.php, includes/class-coblocks-block-assets.php, includes/class-coblocks-form.php, includes/class-coblocks-post-meta.php, src/blocks/post-carousel/index.php, src/blocks/posts/index.php
A new PHPCS rule was added to the WordPress Coding Guidelines:
> Using long array syntax ( array( 1, 2, 3 ) ) for declaring arrays is generally more readable than short array syntax ( [ 1, 2, 3 ] ), particularly for those with vision difficulties. Additionally, it’s much more descriptive for beginners.
> Arrays must be declared using long array syntax.
This PR updates all instances of the short array syntax to its long form syntax.
=> PHPCS: Use full array syntax

src/blocks/post-carousel/index.php, src/blocks/posts/index.php, src/blocks/share/index.php, src/blocks/social-profiles/index.php
This PR resolves an issue where register_block_type() requires strings for block names.
=> Use string name in server side rendered block registration

src/blocks/posts/inspector.js
Closes #1130 
This resolves case where Posts block errors if attempting to set columns higher than `one` with the horizontal style.
=> Fix Posts block render loop when switching to horizontal style

readme.txt
This PR removes some of the 1.17.1 changelog text in the 1.17.2 readme. 
This is for maintaining a history of changes into `master`.
=> Remove 1.17.1 changelog updates

src/blocks/gallery-carousel/inspector.js, src/blocks/map/edit.js, src/components/background/panel.js, src/extensions/advanced-controls/index.js
Four files in CoBlocks are using `__()` function for string translation but do not properly use the text-domain 'coblocks'. This PR adds the necessary domain for these functions.
=> ensure all __() functions use a text domain

.dev/bin/install-wp-tests.sh
Resolves an issue with our CircleCI builds failing due to the following error:
```bash
svn: E205011: Failure occurred processing one or more externals definitions
```
=> Ignore SVN externals in CircleCI

.dev/tests/phpunit/test-class-coblocks.php, class-coblocks.php
This PR simply removes the `COBLOCKS_HAS_PRO` constant that we're not using, nor planning on using.
=> Remove unused constant

src/blocks/highlight/edit.js
Closes #1140 by removing the className generated class, utilizing the actual block classname instead.
=> Allow Alert block to receive custom classes without breaking styles

CONTRIBUTORS.md
In the spirit of supporting contributors and raising awareness of CoBlocks community contributions (#1126), I've created a CONTRIBUTORS.md file (based off of what Gutenberg uses - [link](https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTORS.md)).
Currently it's based off of our [Contributors Graph](https://github.com/godaddy-wordpress/coblocks/graphs/contributors), though I'd like to include contributors who may not have committed code - but languages, mockups, meaningful feedback, etc as well.
=> Add CONTRIBUTORS.md to celebrate our contributors

src/blocks/gallery-carousel/edit.js, src/blocks/gallery-carousel/inspector.js
The Carousel block currently has a minimum height restriction to 200px. This PR will lower the minimum height to 0px which would accommodate images with a height smaller than 200px. 
**Inspired with WordPress.org support request**
https://wordpress.org/support/topic/carousel-block-200px-height-limitation/
=> Remove minimum height limitation on the Carousel block

src/components/block-gallery/styles/style/_lightbox.scss, src/js/coblocks-lightbox.js
Closes #1155
Tested and compatible with Chrome, FireFox, Edge, Safari, and Opera.
Exit lightbox with `Esc` key. 
Scroll left in Lightbox with `Left arrow` or `A` key. 
Scroll right in Lightbox with `Right arrow` or `D` key.
=> Add keyboard shortcuts for navigating images in a lightbox

.circleci/config.yml
This fixes the CircleCI badges from showing as failing because the build was skipped.
[![CircleCI](https://circleci.com/gh/godaddy-wordpress/coblocks/tree/master.svg?style=svg)](https://circleci.com/gh/godaddy-wordpress/coblocks/tree/master)
=> Add a skip i18n flag on translation commits

uninstall.php
Based on https://github.com/godaddy-wordpress/coblocks/blob/add-coblocks-uninstall/uninstall.php
- I excluded a check for `ABSPATH` since accessing uninstall.php directly would cause `WP_UNINSTALL_PLUGIN` to be undefined. No need to check for both.
- I did not check if this was a multi-site install, since we are not storing any options using `update_site_option`.
=> Cleanup CoBlocks options from database on uninstall

src/blocks/media-card/media-container.js
The instructions string for the Media Placeholder is not being localized in non-EN markets. Adding string to our implementation which we can localize as needed.
=> Localize instructions string for MediaPlaceholder

src/components/block-gallery/styles/editor/_gallery-item.scss
This PR adds `pointer-events: none;`  to the absolute positioned 'after' content element on gallery items. This positioned layer was preventing click events from being registered on the underlying figure so captions could not be un-selected, and captions with no content could not be selected.
PR contains minor css change only and has been manually tested.
Before:
After:
Fixes #1143
Fixes https://github.com/Automattic/wp-calypso/issues/37090
=> Fix bug with editing captions with no content

src/blocks/alert/block.json, src/blocks/alert/test/__snapshots__/save.spec.js.snap, src/blocks/alert/test/transforms.spec.js, src/blocks/alert/transforms.js
New Transforms tests for Alert block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/alert/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/alert/test/transforms.spec.js
coblocks/alert transforms
✓ should transform from core/paragraph block (3ms)
✓ should transform to core/paragraph block
✓ should transform to core/paragraph block without content (1ms)
✓ should transform raw html to block (23ms)
Time:        3.188s
```
=> Improve Alert block stability through transforms testing

src/blocks/click-to-tweet/test/transforms.spec.js, src/blocks/click-to-tweet/transforms.js
- New Transforms tests for Click-to-Tweet block. 
- Fix existing transforms function for Click-to-Tweet block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/click-to-tweet/test/transforms.spec.js
```
```javascript
PASS  src/blocks/click-to-tweet/test/transforms.spec.js
coblocks/click-to-tweet transforms
✓ should transform from core/paragraph block (7ms)
✓ should transform from core/pullquote block (1ms)
✓ should transform from core/quote block (1ms)
✓ should transform to core/paragraph block
✓ should transform to core/pullquote block (1ms)
✓ should transform to core/quote block
Tests:       6 passed, 6 total
Time:        3.026s, estimated 4s
```
=> Improve Click-to-Tweet block stability through transforms testing

src/blocks/author/block.json, src/blocks/author/test/__snapshots__/save.spec.js.snap, src/blocks/author/test/transforms.spec.js, src/blocks/author/transforms.js
New Transforms tests for Author block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/author/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/author/test/transforms.spec.js
coblocks/author transforms
✓ should transform raw html to block (38ms)
✓ should transform when ":author" prefix is seen
Time:        3.538s, estimated 4s
```
=> Improve Author block stability through transforms testing

src/blocks/buttons/test/transforms.spec.js
New Transforms tests for Buttons block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/buttons/test/transforms.spec.js
```
```javascript
PASS  src/blocks/buttons/test/transforms.spec.js
coblocks/buttons transforms
✓ should transform when :buttons prefix is seen (1ms)
✓ should transform when ::buttons prefix is seen
✓ should transform when :::buttons prefix is seen
✓ should transform when ::::buttons prefix is seen
Time:        2.99s, estimated 3s
```
=> Improve Buttons block stability through transforms testing

src/blocks/gist/test/transforms.spec.js
New Transforms tests for Gist block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/gist/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/gist/test/transforms.spec.js
coblocks/gist transforms
✓ should transform raw html to block (14ms)
✓ should transform when ":gist" prefix is seen
Time:        3.147s, estimated 5s
```
=> Improve Gist block stability through transforms testing

src/blocks/dynamic-separator/test/transforms.spec.js
New Transforms tests for Dynamic Separator block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/dynamic-separator/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/dynamic-separator/test/transforms.spec.js
coblocks/dynamic-separator transforms
✓ should transform from core/spacer block (2ms)
✓ should transform from core/separator block (1ms)
✓ should transform to core/spacer block
✓ should transform to core/separator block (1ms)
Time:        4.675s
````
=> Improve Dynamic Separator block stability through transforms testing

src/blocks/features/test/transforms.spec.js
New Transforms tests for Features block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/features/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/features/test/transforms.spec.js
coblocks/features transforms
✓ should transform when :feature prefix is seen (2ms)
✓ should transform when :features prefix is seen (1ms)
✓ should transform when ::features prefix is seen
✓ should transform when :::features prefix is seen (1ms)
Time:        4.44s
```
=> Improve Features block stability through transforms testing

src/blocks/post-carousel/index.php
The editor provides full-size images to preview the block but published pages use the thumbnail-sized imaged. This change will bring in full-size images to be used on published pages. The default behavior of `get_the_post_thumbnail_url()` is to retrieve the thumbnail size image for the provided post ID. Here we can pass the string 'full' to retrieve full-size images. 
**Inspired with WordPress.org support request**
https://wordpress.org/support/topic/featured-images-in-post-carousel-low-res/
=> Serve full size images with Post Carousel block

src/blocks/gallery-carousel/styles/editor.scss, src/blocks/gallery-masonry/styles/editor.scss, src/blocks/gallery-offset/styles/editor.scss, src/blocks/gallery-stacked/styles/editor.scss
When a block is selected in the typical editor view, an `is-selected` class is appended to the block. In the case that Spotlight mode is enabled, the class `is-focused` is appended instead. This change adds the correct conditional to hide the placeholder.
=> Fix media placeholder visibility when using Spotlight mode

includes/class-coblocks-block-assets.php
Closes #1215 
This PR resolves a bug in 1.19.0 CoBlocks where a 404 error is displayed.
By setting the default status of the filter to false we can prevent this error.
=> Resolve 404 error for utilities styles

.dev/bin/wporg-glossary-audit
This PR adds a utility script that can be used to audit i18n strings against the WordPress.org Glossary for the given locale. It is meant to be run locally and flag any strings potentially not following the Glossary so a human (preferably a native speaker of the locale in question) can manually review the part of speech (noun, verb, adjective, etc) and whether the translation is OK or not.
This program accepts 2 arguments:
1. Path to a JSON file of English source strings
2. Path to a JSON file of translated Locale strings
**Note: The WordPress.org locale will be determined by the filename of the 2nd argument!**
e.g. `es_ES.json = es` and `es_MX.json = es-mx`
**Example:**
```sh
$ .dev/bin/wporg-glossary-audit languages/coblocks.json languages/es_ES.json
```
^ This will check all `es_ES` …
=> Add utility script that audits i18n strings against a wporg glossary

src/extensions/typography/index.js, src/extensions/typography/styles/style.scss
Resolves #1220 
This PR removes the `has-custom-size` class being added to blocks through the Typography Controls. This class provides zero value and is causing paragraphs with custom font sizes selected. Removing it solves the issue.
=> Remove has-custom-size class from Typography Controls

.circleci/config.yml, .dev/tests/phpunit/test-class-coblocks.php
After issue https://github.com/godaddy-wordpress/coblocks/issues/1215 came up, there was some discussion on how we could prevent issues like this in future.
This PR updates the PHPUnit test suite to now test for all build assets. This will help ensure that when we deploy new releases we're confident that our `js` and `css` assets exist in their intended locations.
Builds will take a little longer to complete, because we now need to install node dependencies and build the plugin inside of the CircleCI job, but this will give us additional confidence in our future releases.
=> Update PHPUnit tests to check for build assets

src/blocks/media-card/test/transforms.spec.js
New Transforms tests for Media Card block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/media-card/test/transforms.spec.js
```
```javascript
PASS  src/blocks/media-card/test/transforms.spec.js
coblocks/media-card transforms
✓ should transform from core/image block (2ms)
✓ should transform from core/video block (1ms)
✓ should transform from core/media-text block (1ms)
✓ should transform to core/image block
✓ should transform to core/video block (1ms)
✓ should transform to core/media-text block (2ms)
✓ should transform when :card prefix is seen
Tests:       7 passed, 7 total
Time:        2.966s, estimated 3s
```
=> Improve Media Card block stability through transforms testing

src/blocks/gallery-offset/deprecated.js, src/blocks/gallery-offset/index.js, src/blocks/gallery-offset/save.js
Closes #1227.
Fix the issue by correctly saving the custom link into post content. The deprecated function allows previously configured blocks to resume working with the set URL.
=> Fix custom links added to images in the Offset Gallery block

.dev/tests/jest/helpers.js, src/blocks/gallery-masonry/test/transforms.spec.js, src/blocks/gallery-masonry/transforms.js
New Transforms tests for Masonry Gallery block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/gallery-masonry/test/transforms.spec.js
```
```javascript
PASS  src/blocks/gallery-masonry/test/transforms.spec.js
coblocks/gallery-masonry transforms
✓ should transform from coblocks/gallery-stacked block (4ms)
✓ should transform from coblocks/gallery-collage block (1ms)
✓ should transform from coblocks/gallery-offset block (1ms)
✓ should transform from coblocks/gallery-carousel block (1ms)
✓ should transform from core/gallery block (1ms)
✓ should transform from core/image block (1ms)
✓ should transform to coblocks/gallery-stacked block (1ms)
✓ should transform to coblocks/gallery-collage block (1ms)
✓ should transform to coblocks/gallery-offset …
```
=> Improve Masonry Gallery block stability through transforms testing

.dev/tests/jest/helpers.js, src/blocks/gallery-collage/test/transforms.spec.js, src/blocks/gallery-collage/transforms.js
New Transforms tests for Collage Gallery block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/gallery-collage/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/gallery-collage/test/transforms.spec.js
coblocks/gallery-collage transforms
✓ should transform from coblocks/gallery-stacked block (4ms)
✓ should transform from coblocks/gallery-masonry block (1ms)
✓ should transform from coblocks/gallery-offset block (1ms)
✓ should transform from coblocks/gallery-carousel block (1ms)
✓ should transform from core/gallery block (1ms)
✓ should transform from core/image block (1ms)
✓ should transform to coblocks/gallery-stacked block (1ms)
✓ should transform to coblocks/gallery-masonry block (1ms)
✓ should transform to coblocks/gallery-offset …
```
=> Improve Collage Gallery block stability through transforms testing

src/blocks/pricing-table/pricing-table-item/test/transforms.spec.js, src/blocks/pricing-table/pricing-table-item/transforms.js, src/blocks/pricing-table/test/transforms.spec.js, src/blocks/pricing-table/transforms.js
New Transforms tests for Pricing Table and Pricing Table Item block.
Test changes with the following:
**Pricing Table**
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/pricing-table/test/transforms.spec.js 
```
**Pricing Table Item**
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/pricing-table/pricing-table-item/test/transforms.spec.js 
```
**Pricing Table Tests**
```javascript
PASS  src/blocks/pricing-table/test/transforms.spec.js
coblocks/pricing-table transforms
✓ should transform raw html to 1 column block (16ms)
✓ should transform raw html to 2 column block (5ms)
✓ should transform raw html to 3 column block (4ms)
✓ should transform raw html to 4 column block (5ms)
✓ should transform when ":pricing" prefix is seen
Test Suites: 1 passed, 1 …
```
=> Improve Pricing Table block stability through transforms testing

src/blocks/map/test/transforms.spec.js
New Transforms tests for Map block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/map/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/map/test/transforms.spec.js
coblocks/map transforms
✓ should transform when :map prefix is seen (2ms)
Time:        3.77s
```
=> Improve Map block stability through transforms testing

src/blocks/post-carousel/test/transforms.spec.js
New Transforms tests for Post Carousel block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/post-carousel/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/post-carousel/test/transforms.spec.js
coblocks/post-carousel transforms
✓ should transform from core/latest-posts block (2ms)
✓ should transform from coblocks/posts block (1ms)
✓ should transform to core/latest-posts block (1ms)
Tests:       3 passed, 3 total
Time:        3.371s, estimated 4s
```
=> Improve Post Carousel block stability through transforms testing 

src/blocks/posts/test/transforms.spec.js
New Transforms tests for Posts block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/posts/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/posts/test/transforms.spec.js
coblocks/posts transforms
✓ should transform from core/latest-posts block (3ms)
✓ should transform from coblocks/post-carousel block (1ms)
✓ should transform to core/latest-posts block (1ms)
✓ should transform when :posts prefix is seen (2ms)
✓ should transform when :2posts prefix is seen (1ms)
✓ should transform when :3posts prefix is seen (1ms)
✓ should transform when :4posts prefix is seen
✓ should transform when :5posts prefix is seen (1ms)
✓ should transform when :6posts prefix is seen
Tests:       9 passed, 9 total
Snapshots:   0 …
```
=> Improve Posts block stability through transforms testing

src/blocks/row/test/transforms.spec.js
New Transforms tests for Row block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/row/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/row/test/transforms.spec.js
coblocks/row transforms
✓ should transform when :row prefix is seen (2ms)
✓ should transform when ::row prefix is seen
✓ should transform when :::row prefix is seen (1ms)
✓ should transform when ::::row prefix is seen
Time:        3.257s
```
=> Improve Row block stability through transforms testing

src/blocks/shape-divider/test/transforms.spec.js
New Transforms tests for Shape Divider block.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/shape-divider/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/shape-divider/test/transforms.spec.js
coblocks/shape-divider transforms
✓ should transform from core/spacer block (2ms)
✓ should transform from core/separator block (1ms)
✓ should transform from coblocks/dynamic-separator block (1ms)
✓ should transform when :divider prefix is seen
Time:        3.344s, estimated 5s
```
=> Improve Shape Divider block stability through transforms testing

src/blocks/share/block.json, src/blocks/share/test/save.spec.js, src/blocks/social-profiles/test/transforms.spec.js, src/blocks/social-profiles/transforms.js
All transforms to and from these blocks are housed in the Social-Profiles block source at transforms.js. Made a minor fix to attribute names that are used in the Share block. This Jest test also tests that localStorage is working as expected.
New Transforms tests for Social-Profiles and Share blocks.
```bash
npx jest --config .dev/tests/jest/jest.config.js ./src/blocks/social-profiles/test/transforms.spec.js 
```
```javascript
PASS  src/blocks/social-profiles/test/transforms.spec.js
coblocks/shape-divider transforms
✓ should transform from coblocks/social (share) block (3ms)
✓ should transform to coblocks/social (share) block (2ms)
✓ should maintain attribute values in localStorage with transforms (2ms)
Tests:       3 passed, 3 total …
```
=> Improve Share and Social-Profiles block stability through transforms testing

src/blocks/features/inspector.js
This PR updated the max column count for the Features block from `3` to `4`. This provides a consistent columns experience across our blocks.
=> Set Features block max count to four

src/blocks/features/inspector.js
This PR adds a new "huge" setting to the Features block gutter control. By doing so, we're allowing consistent gutter sizes across all our blocks that support them.
=> Add huge setting to the Features block gutter control

.circleci/config.yml
- Run a canary build on each commit to master, which is them tagged as a `pre-release` here on Github as a `CoBlocks-canary` release.
- Deploy the CoBlocks-canary build to the CoBlocks staging site for testing.
- Switch the regex on the `deploy` job to run on semantic version tags only.
_(see job https://circleci.com/gh/godaddy-wordpress/coblocks/8089)_
=> Canary release

.circleci/config.yml
* Bundle all language files with the canary package (POT/PO/MO/JED)
* Remove any GlotPress translations from the i18n staging site after deploy
* Append the current commit hash to the end of canary versions
* Add disclaimer to the canary description that is should not be used in production
* Once merged, we can remove the `STAGING_SITE_PLUGIN_PATH` env var from CircleCI
=> Bundle languages in the canary package

README.md, includes/class-coblocks-block-assets.php
Now that #1253 is incoming, and we're working towards potentially using CSS properties to declare spacing utils, we don't need a separate utilities stylesheet. This PR removes the filter and wp_enqueue_style() that we added in preparation.
=> Remove the separate utilities stylesheet

src/blocks/accordion/accordion-item/controls.js
This PR removes the `components-toolbar__block-coblocks-accordion` class, as its no longer being used.
=> Removed unused class from Accordion controls

.dev/tests/cypress/helpers.js, .eslintignore, .eslintrc.json, package-lock.json, package.json, src/blocks/accordion/test/accordion.cypress.js, src/blocks/alert/test/alert.cypress.js, src/blocks/highlight/test/highlight.cypress.js
Refactor tests and helpers to support the expected features of WP 5.4 (or Gutenberg 7.2) and is compatible with and without the Gutenberg plugin active. 
**ESLint**
- Applied ESLint to all tests and `helper.js`.
- Installed `Cypress` ESLint plugin.
- Removed tests from `.eslintignore`
**helper.js**
- Added logic to deprecate `core/nux` into `select( 'core/edit-post' ).isFeatureActive( 'welcomeGuide' )`
- Enhanced selector specificity with `Regex` to click the appropreate elements. 
* Resolves issues where referenced classes have been deprecated.
- Identified and implemented alternate solutions for Cypress changes around `getBlockSlug` function. 
* `Cypress.spec.name` is not as expected in certain scenarios.
*  https://github.com/cypress-io/cypress/issues/3090
****.cypress.js**
- Re-wrote …
=> E2E Compatibility Refactor

src/blocks/highlight/test/highlight.cypress.js
Looks like one of the tests was not properly updated with my #1261 PR. This fix passes the block name to the `addCustomBlockClass` helper function.
=> Pass block name to custom class helper

src/components/block-gallery/gallery-placeholder.js
Closes #1258 
Freshly uploaded images do not possess a caption which resulted in a type error on assertion. Update logic to provide an empty caption if its a freshly uploaded image. 
This resolves the issue with the `offset`, `stacked` and `masonry` gallery blocks.
=> Fix Gallery blocks when uploading images

src/components/typography-controls/index.js, src/extensions/typography/controls.js, src/extensions/typography/index.js
This PR removes the Typography controls from the core Cover block, as the Cover block contains InnerBlocks blocks which already have Type controls.
Closes #947.
=> Remove Typography controls from the core Cover block

src/blocks/features/inspector.js, src/blocks/row/column/inspector.js, src/blocks/row/inspector.js
To ensure a consistent experience, this PR moves the more important `padding` DimensionsControl above the `margin` control. 
This PR only affects InspectorControls so no deprecations are needed.
=> Switch DimensionsControls padding and margin

src/blocks/form/deprecatedTemplates/layouts.js, src/blocks/form/edit.js, src/blocks/form/index.js, src/blocks/form/patterns.js
Related to https://github.com/godaddy-wordpress/coblocks/issues/1226
Gutenberg and soon to be WordPress core have dropped support for `InnerBlocks.__experimentalTemplateOptions` in favor of the `__experimentalBlockPatternPicker` component. This PR will enable support for either component. 
Blocks should **not** require deprecation here. InnerBlocks are maintained across versions.
**Running 5.3.2 + GB 7.3**
**Running 5.3.2 (No Gutenberg)**
=> Fix template selector in the Form block when Gutenberg is active

src/components/typography-controls/index.js
In the same vein as #1259, this PR removes the typography controls from the parent Features block. The controls don't always work within the editor anyhow, as themes' editor styling is too specific for applying fonts to a parent block, and having those styles permeate though to the child blocks.
=> Remove typography controls from Features block

src/blocks/events/index.php
This resolves an notice the following PHP notice.
```
Notice: WP_Block_Type_Registry::register was called incorrectly. Block type names must be strings. Please see Debugging in WordPress for more information. (This message was added in version 5.0.0.) in /var/www/wp-includes/functions.php on line 4986
```
=> Explicitly pass the block type name when registering on the server side

includes/ical-parser/class-coblocks-ical.php
Fixes a WPCS error spotted while deploying version `1.20.1` on [WordPress.com](https://wordpress.com).
=> Fix WPCS error

src/blocks/row/edit.js, src/blocks/row/test/row.cypress.js
This PR removes the one column option from our Row block to make things less confusing. 
Current:
=> Remove one column option from the Row block

src/blocks/icon/styles/editor.scss
This PR tweaks the styling of the Icon block's `Icon Size` reset button, so that it displays properly when "Reset" is translated. 
Before: 
Now:
=> Fix Icon block reset button for improved i18n support

.dev/config/webpack.config.js, includes/class-coblocks-block-assets.php, src/js/coblocks-accordion-carousel.js
Resolves #1307 
Introduce a script to re-initialize the flickity carousel when nested inside of an accordion item and _not_ visible on initial load.
**Note:** We're also going to need to reinitialize the post carousel (slick slider) in a similar fashion to how we're doing it here with flickity.
=> Reinitialize Flickity carousel when used inside an Accordion block

includes/ical-parser/class-coblocks-ical.php
The date strings defined in the iCal parser are never displayed to end-users and only used to convert iCal values to strings that PHP can recognize when calculating `strtotime()`, for this reason they should all map to English.
```php
strtotime( 'first monday of may 2020' ) === 1588550400
strtotime( 'primer lunes de mayo 2020' ) === false // Spanish not recognized
```
Additionally, there was a hardcoded value to represent `PHP_INT_MIN` as a 32 bit integer and the proper way to do this is to call a bitwise `~PHP_INT_MAX` which supports both 32 and 64 bit systems and still works on PHP 5.6.
=> Don't translate date strings in the iCal parser

src/blocks/features/inspector.js, src/blocks/gallery-offset/inspector.js, src/blocks/row/inspector.js, src/blocks/services/inspector.js, src/styles/style.scss
This PR replaces older `ButtonGroup` controls with the `OptionSelectorControl` that we've built to simplify similar experiences across the following blocks: 
- Features
- Row
- Offset Gallery
- Services
Old: 
New:
=> Replace older ButtonGroup controls with OptionSelectorControl

src/blocks/gallery-stacked/index.js
Change "Display multiple images in an single column stacked gallery" to "Display multiple images in a single column stacked gallery."
=> Fix typo in Stacked Gallery description

src/blocks/gallery-carousel/styles/style.scss
This PR tweaks the display of the previous arrow within the Carousel block, ensuring it displays properly.
Before: 
After: 
Bug fix (non-breaking change which fixes an issue), styles only.
=> Fix navigation arrow position on Carousel block

src/blocks/form/edit.js, src/blocks/form/index.js, src/blocks/form/variations.js
Experimental APIs have been pushed to stable in Gutenberg 7.5 and are expected to land in WordPress 5.4. This PR changes the references to these experimental APIs in favor of the stable versions as can be seen in  https://github.com/WordPress/gutenberg/pull/19966 and https://github.com/WordPress/gutenberg/pull/20068
**Using Undo Hotkey**
Maintain backward compatibility for WordPress 5.3.2 as well as support for Gutenberg 7.5 (and likely WordPress 5.4)
Tested with and without Gutenberg 7.5 active and found the Form block template selector functional.
=> Implement blockVariationPicker with Form block

src/blocks/row/edit.js, src/blocks/row/test/row.cypress.js
PR will add back the one column option and related tests to the row block. 
Closes #1359
The Row block has supported the One Column option previously. This change re-introduces the feature.
Passes all block related tests.
=> Add one column option to the Row block

CONTRIBUTORS.md, docs/hooks/settings-panel.md
Added docs for hooks related to the new settings panel in 1.21.0
Text comes from reading the PR that introduced the changes #1313
`coblocks-settings-title` example from https://github.com/godaddy-wordpress/coblocks/pull/1313#issuecomment-585243849
`coblocks_show_settings_panel` example from https://github.com/godaddy-wordpress/coblocks/pull/1313#issuecomment-583119412
=> Add docs for settings panel hooks

includes/class-coblocks-block-assets.php, src/blocks/events/index.php
Currently, the events block unconditionally enqueues slick.js. It is enqueued regardless of whether it is needed.
This PR updates coblocks so slick.js is only enqueued for the editor and for front-end pages that include the events block.
Because slick.js depends on jQuery, this may address #1361, but I haven't been able to confirm yet because something else on my quite simple site is also enqueuing jQuery by default.
Bug fix
Setup:
Open browser dev tools to the network tab and search for slick.js
Testing:
1. On a test site, navigate to a page that does not contain the events block, and observe that slick.js is not requested.
2. Open the block editor to create a new post and note that slick.js is requested.
3. Add an events block, link to an external calendar with more than 5 events, and …
=> Stop unconditionally enqueuing slick.js

src/components/font-family/index.js
Wrap Google fonts in custom filter, allowing users to add additional fonts to CoBlocks typography controls.
N/A
New Feature
Created a custom plugin to test that adding custom fonts works as intended, and renders as expected in the editor and on the front of site.
```js
/**
* Make additional custom Google fonts available
*
* @param {array} fonts Available Google fonts.
*
* @return {array} Filtered Google fonts array.
*/
function filterCoBlocksGoogleFonts( fonts ) {
let customFonts = [
'Trade Winds',
'Odibee Sans',
'Yeon Sung',
'Anton',
];
for ( let i = 0; i < customFonts.length; i++ ) {
fonts.push(
{ value: customFonts[ i ], label: customFonts[ i ] }
);
}
return fonts;
}
wp.hooks.addFilter( 'coblocks.google_fonts', 'coblocks/coblocks.google_fonts', filterCoBlocksGoogleFonts );
```
=> Wrap Google fonts in filter

cypress.json, src/blocks/accordion/accordion-item/edit.js, src/blocks/accordion/edit.js, src/blocks/accordion/styles/editor.scss, src/blocks/accordion/test/accordion.cypress.js
Accordion Items display "closed" unless you are interacting with the Accordion Item block (isSelected) or the Accordion Item is set to display open with the open attribute. The Accordion Item will stay open when interacting with child blocks inside the Accordion Item.
- UX enhancement
Automated end-to-end tests have been created to verify functionality.
Closes #1377
=> Persist Accordion block open state when editing a post

src/blocks/food-and-drinks/block.json, src/blocks/food-and-drinks/controls.js, src/blocks/food-and-drinks/edit.js, src/blocks/food-and-drinks/food-item/block.json, src/blocks/food-and-drinks/food-item/edit.js, src/blocks/food-and-drinks/test/food-and-drinks.cypress.js, src/blocks/highlight/test/highlight.cypress.js, src/components/heading-toolbar/index.js
This PR introduces Heading Toolbar controls to the Food and Drinks and Food Item blocks. Changes allow for hierarchical attribute propagation to inner blocks. Controls added to Food-Item blocks as well for more fine-grained control.
Adds Heading Toolbar controls for Food and Drink and Food Item blocks. This PR also adds a new E2E test for the Heading Toolbar integration.
Tested with WP 5.3.2 with and without Gutenberg 7.6.
Tested and updated E2E tests for the changed blocks.
=> Control Food Item block headings from the parent Food and Drinks block

.circleci/config.yml
`scp` commands in the deployments were intermittently prompting the user for a password during the deployments to the i18n staging site.
This PR points to the `id_rsa` file so that we are not prompted for a password.
=> Specify key file in scp during deployment to staging site

src/blocks/row/styles/editor.scss
Add margins to the button wrappers to fix Row block placeholder layout. Closes #1362 
Minor CSS change.
Tested using responsive viewport.
=> Fix Row block placeholder spacing

CONTRIBUTORS.md, changelog.txt, readme.txt
Updating the readme and changelog for the 1.22.0 release.
=> Updating the readme for 1.22.0

src/components/font-family/index.js, src/components/typography-controls/index.js
Resolves #1374 
Fix the typography controls font family dropdown value not displaying the selected value. Additionally, changing the font family no longer closes the typography controls panel.
This PR fixes the incorrect way to set the selected value in the font family typography controls component. Additionally, changing the font family no longer closes the typography controls panel.
=> Fix selected font family option in the typography controls

includes/class-coblocks-block-assets.php, src/blocks/icon/edit.js, src/blocks/icon/svgs.js
Resolves #1394, #1405
Introduce a new filter to disable the bundled icons that ship with CoBlocks. This allows users who implement custom icons to remove the excess icons that they may not ever use.
**New filter:** `coblocks_bundled_icons_enabled`
**Note:** I named the filter this way to match the syntax of the typography controls filter, `coblocks_typography_controls_enabled`.
```php
add_filter( 'coblocks_bundled_icons_enabled', '__return_false' );
```
=> Introduce a filter to disable the CoBlocks bundled svg icons

src/extensions/coblocks-settings/coblocks-settings.cypress.js
Add tests for the CoBlocks settings panel. These tests ensure that the basic functionalities of the CoBlocks Settings control work as expected.
Enhancing stability of CoBlocks by adding tests for plugin extensions.
Tested changed in WordPress 5.3.2 as well as 5.4beta-2. Tested with and without Gutenberg plugin active.
=> Introduce E2E tests for CoBlocks Settings panel

includes/class-coblocks-form.php, src/blocks.js, src/blocks/form/fields/text/edit.js, src/blocks/form/fields/text/icon.js, src/blocks/form/fields/text/index.js, src/blocks/form/fields/text/test/__snapshots__/save.spec.js.snap, src/blocks/form/fields/text/test/save.spec.js
The form block allows for a number of custom inputs but lacks the basic text box input mechanism. This PR adds the capability to add a text field to a Form block allowing for custom responses/input from users.
Add a new child block scoped for the Form block. Basic save test for new block save function. Still requires new icon.
Wrote a test for the new inner block. 
Tested and working with the Gutenberg Plugin.
Tested and working with WP 5.3.2 and WP 5.4RC.
=> Add Form block Text field

src/components/block-gallery/styles/style/_lightbox.scss, src/js/coblocks-lightbox.js
Resolves #1099 
Display gallery image captions in the light box.
=> Show gallery image captions in light box

src/js/coblocks-lightbox.js
Resolves #1383 
Clicking on a gallery caption opens the light box with the respective image.
https://cldup.com/mMRvkNRjn4.gif
=> Clicking captions opens the light box

src/blocks/gallery-carousel/styles/editor.scss, src/blocks/gallery-carousel/styles/style.scss
Resolves #1432 
I've removed the `height: 100%;` declaration from the `.coblocks-gallery` item on the front of site, as it is not needed.
I've added the height back inside of the editor, so things still render correctly.
Manually, visually. The end to end tests also passed, but not sure that tests for any issues like this.
=> Remove 100% height from gallery carousels on front of site

src/blocks/events/index.php, src/blocks/features/inspector.js, src/blocks/gallery-collage/inspector.js, src/blocks/gallery-offset/inspector.js, src/blocks/posts/inspector.js, src/blocks/row/inspector.js, src/blocks/services/inspector.js, src/utils/gutter-options.js
Remove duplicate `gutterOptions` throughout the blocks, and add a `gutter-options.js` utility.
Refactor existing code base - non-breaking change
Manual checks.
=> Unify gutterOption values and remove duplicate code

includes/class-coblocks-accordion-ie-support.php, includes/class-coblocks-block-assets.php, includes/class-coblocks-font-loader.php, includes/class-coblocks-generated-styles.php, includes/class-coblocks-google-map-block.php, includes/class-coblocks-register-blocks.php, includes/class-coblocks-settings.php
Enables plugins to remove the action added in `__contstruct()`.
Returns the instance of `CoBlocks_Settings` after it was registered.
Enhancement
Tested locally.
=> Settings: Return instance on register

src/blocks/icon/styles/style.scss
Closes #1428.
**Before**
**After**
Minor CSS change. This properly sets icon spacing when using links with your icons.
Chrome and Firefox.
5.5beta with and without GB.
=> Fix Icon block spacing when using custom links

src/blocks/events/index.php, src/blocks/map/edit.js, src/blocks/map/styles/editor.scss
Closes #1439 
PR changes the markup used for the placeholder for the Map block in the edit.js file. Using a form and a general input element similar to the markup used for the core Embed block.
Minor change adjusts layout of Map block placeholder. No deprecation needed.
Tested with and without Gutenberg.
Tested with 5.5beta.
=> Fix Map block placeholder styles

src/extensions/coblocks-settings/index.js
If the `coblocksSettings` var is undefined then we should not register the CoBlocks settings menu item at all. Such is the case when executing this extension directly, outside of PHP, where `wp_localize_script()` never runs.
N/A
Bug fix
=> Do not register if coblocksSettings is undefined

readme.txt
Inspired by WP.org request.
https://wordpress.org/support/topic/mention-of-gutenberg/
With the release of WordPress 5.4, we are now well ahead of a position where we should be recommending use of the Gutenberg plugin. Altered FAQ wording to suggest WordPress 5.0 or higher but removed the reference to the Gutenberg plugin. 
Minor wording change.
=> Update WP.org FAQs

src/blocks/hero/edit.js, src/components/grid-control/index.js, src/js/deprecations/deprecate-coblocks-buttons.js
PR to set inner block button alignment with Hero block. 
Closes #1460.
Add Select and Dispatch HOC to Grid component to allow setting of inner block attributes. 
Tested in 5.4 with and without the Gutenberg plugin.
=> Propagate alignment to Hero block inner buttons

src/js/coblocks-masonry.js
Removes the `transitionDuration` for the Masonry block. May resolve #1370 as well.
=> Try removing masonry transition

.circleci/config.yml, .dev/bin/install-mailhog.sh, .dev/mailhog.php, includes/class-coblocks-form.php, src/blocks/form/test/form.cypress.js
This PR introduces a Cypress e2e test which submits the form and confirms that an email was sent and received.
It also adds a test to test that custom subject line is set when `wp_mail()` fires and tests that the `[email]` and `[name]` link keywords are added to the subject line in the block editor and then replaced in the subject line when sent.
I have run the tests a number of times locally and on CircleCI.
=> Add form block e2e test to confirm emails are being sent

includes/class-coblocks-block-assets.php
Resolves a bug that was introduced in 1.26.0 where the variable $post_content may not be defined.
Simplifying the conditional prevents the possibility of the notice.
Resolves #1474 
Resolves #1475 
Manual tests and our unit tests pass.
=> Remove a condition where a variable may not be defined

includes/class-coblocks-form.php
Render a submit button if not found in the block content.
Forms added to a post/page in CoBlocks 1.23.0 and earlier are missing the button on the theme side when upgrading to 1.24.0 and later.
Closes #1472 
Created a form with CoBlocks 1.23.0 and upgraded to 1.24.0, 1.25.0, and 1.26.0. All were missing the button until this fix. PHPUnit tests coming shortly.
=> Render a submit button if not found in the block content

src/blocks/map/edit.js, src/blocks/map/test/map.cypress.js
Adding custom classes for the map block with in the editor. Resolves: https://github.com/godaddy-wordpress/coblocks/issues/1332
I've added the className from props to the render. Using the `classnames` method.
- While in the editor, I selected the map block and went to the "Advanced" settings on the sidebar. - Then added `my-own-class`. 
- Finally, confirmed using the dev tools that the class is in place.
I set the class on the same places as other blocks do.
=> [Fix] Add custom classes for Map block within the editor.

src/layout-selector/index.js, src/layout-selector/style.scss
Tweaks the display of the + button by using the same + as used in Gutenberg.
Before:
With this PR:
=> Tweak display of + button in layout selector

.dev/tests/phpunit/includes/test-coblocks-block-assets.php, .dev/tests/phpunit/test-class-coblocks.php, includes/class-coblocks-block-assets.php, includes/class-coblocks-body-classes.php
This PR builds upon #1454 which attempted to conditionally load CoBlocks scripts and styles only when needed. This attempt was great but in the end broke some other conditions we didn't test for.
The `has_block` method in WordPress Core as well as the custom check for blocks in the `coblocks/` namespace only work on singular (`is_singular()`) pages. Two conditions we missed related to any non-singular page with CoBlocks rendered (#1490 & #1496) and CoBlocks used within a reusable block that is inserted into a page (#1491).
Currently it's impossible to easily determine if a specific block is loaded anywhere on the page (in any WP_Query loop) or if they exist in a reusable block (because it's saved as a `core/block` type). To solve those two problems will take some thought to take care of …
=> Improve conditional loading of scripts and styles

docs/hooks/settings-panel.md, docs/hooks/typography-controls.md
The description was saying `PHP` when it is actually a `JavaScript` filter, and can be misleading.
Only a small change in the docs.
=> Update typography hooks docs.

src/components/block-gallery/styles/editor/_gallery-item-menus.scss
=> Fix gallery block image selector UI

.prettierrc.js, src/extensions/advanced-controls/index.js, src/extensions/advanced-controls/styles/editor.scss
Closes #1513
Gutenberg has made [changes](https://github.com/WordPress/gutenberg/pull/21822) with V8.2.1 that add an alignment wrapper to blocks that allow alignment. This has negatively impacted the advanced spacing controls extension from CoBlocks.
This PR uses a mutation observer to watch the editor and update margins using inline styles where appropriate. Styles are properly applied to the Front-end as is.
Changes to the `addEditorBlockAttributes` HOC.
Tested manually with and without Gutenberg running. Tested in Go, and TwentyTwenty.
=> Fix advanced block spacing with Gutenberg plugin

.prettierrc.js
The `.prettierrc.js` file is not needed as the configuration is already defined in the project `.eslintrc.js` file. PR to remove this file which is a regression and unintended.
Remove file to revert a regression on the master branch. 
Tested manually. `.eslintrc.js` file is properly extending `plugin:@wordpress/eslint-plugin/recommended-with-formatting`.
=> Remove .prettierrc.js file from repository

src/extensions/advanced-controls/index.js
A few blocks such as group and shape divider were not having spacing properly applied either in the editor or within the layout selector. Made some changes to the logic which applies the spacing in this PR.
There are two parts to the layouts. The exisitng layouts from Go require a minor tweak to attributes for the desired layouts. <del>Those tweaks will be coming in on the Go repository.</del> Looks like @richtabor made the changes here: https://github.com/godaddy-wordpress/go/pull/524/commits/29883ea6217d12673bc39a67e0ef6558a79a926c
Minor logic change.
Tested manually and with the layout selector.
=> Fix advanced spacing in the Layout Selector and Editor

CONTRIBUTORS.md, src/extensions/typography/apply-style.js
The latest version of Gutenberg includes typography settings which already exist in CoBlocks. This PR doesn't fully harmonise those settings, but it stops CoBlock from disabling the core settings.
Using `line-height` as an example: if the line height was unset in CoBlocks, then `applyStyle()` would set the inline style to `null`. This means that if core Gutenberg had set it's own line height then it would get nulled out. As shown in #1500 this caused the line height to be removed on the front end and could cause invalid block errors.
This PR only sets an inline typography style if one has been set in CoBlocks, otherwise it leaves it alone. This means the CoBlocks setting takes precedent over the core Gutenberg setting on the front end. Maybe it should be the other way round, but this at …
=> Fix overwriting existing line height style when none has been set in CoBlocks

src/blocks/gallery-collage/styles/editor.scss, src/blocks/gallery-stacked/styles/editor.scss, src/components/block-gallery/styles/editor/_gallery-item-link.scss, src/components/block-gallery/styles/editor/_gallery-item-menus.scss, src/components/block-gallery/styles/editor/_gallery-item.scss
Closes #1503 
Gallery blocks use overlapping DOM elements when rendering the user interface. Certain conditions may be met which essentially results in a hidden caption input box. Utilizing conditional CSS selectors we may move the caption box within view when necessary to do so.
This fix works for both core WordPress 5.4.1 as well as with Gutenberg plugin active 8.2.1. This PR also fixes the display of the custom URL input box when Gutenberg is active. 
Minor CSS changes to gallery components.
Tested manually with and without the Gutenberg plugin active.
=> Enable gallery caption editing when using custom links

src/extensions/typography/apply-style.js
Used incorrect import target. Minor change to use the correct import target for lodash.
=> Fix import target for typography controls lodash

src/blocks/social-profiles/block.json, src/blocks/social-profiles/index.php, src/blocks/social-profiles/inspector.js, src/blocks/social-profiles/test/social-profiles.cypress.js
Adding a general option for the social profiles block to open links in new tab. It should partially fix https://github.com/godaddy-wordpress/coblocks/issues/1360
I thought that experience wise, either you choose all links to open in a new tab, or not. That's why I took this approach. And because it doesn't lock "us" to implement on a link basis in the future.
*Note*: I'm building a new site using coblocks and I found it more useful this way.
*Note 2*: I want to add GitHub to this block. Maybe this is more a note to myself. I'll probably open a new issue.
I added a new block setting for the *Social Profiles* block. Used the same naming as WP does for this, to keep it consistent.
Finally, edited the block template to reflect the changes in the setting.
- Added the social profiles block.
- …
=> Social profiles: Open links in new tab

src/components/responsive-tabs-control/index.js, src/components/responsive-tabs-control/styles/editor.scss, src/components/size-control/index.js
=> Fix primary/secondary buttons in custom components with Gutenberg active

src/blocks/shape-divider/styles/editor.scss
The Shape Divider block can be difficult to use when the block has an is-selected outline around the block. The outlines interfere with the resizable box handles and make the block harder to use. This PR removes the new outline added by the Gutenberg plugin.
Minor CSS changes.
Tested manually with and without the Gutenberg plugin active. The outline is only present and removed when the Gutenberg plugin is activated.
=> Remove selected block outline from Shape Divider block

src/extensions/advanced-controls/index.js
PR https://github.com/godaddy-wordpress/coblocks/pull/1521 introduced a mutation observer to handle document changes needed to properly apply advanced margins. This PR is using lifecycle methods instead of mutation observers with significant performance benefits.
This screenshot shows the layout selector in use with markedly enhanced performance. 
Using simple document methods to watch the document and apply advanced margins where applicable. 
Tested manually with and without the Gutenberg plugin active.
=> Fix editor performance relating to advanced margins

src/blocks/accordion/edit.js, src/blocks/accordion/test/accordion.cypress.js
Accordion block appender had been using `onClick` listener to handle the creation of new children. I found that changes within the DOM upon `mouseDown` event were causing the `onClick` event to cease bubbling thus resulting in a failure to execute the callback. 
By using `onMouseUp` listener we can circumvent the bubbling issue and react to user interaction.   
Minor changes to event listener attached to the block appender.
Tested manually with and without the Gutenberg plugin active. Tested with Go and Twenty Twenty.
=> Fix Accordion children block appender

src/components/block-gallery/gallery-placeholder.js
A number of conditions may exist which can result in the loss of user-set captions and custom linked URLs. These have been reported in #1320 #1290 and #1478. 
Closes #1478
JavaScript changes to the logic used to preserve captions and links. These gallery attributes tend to vary from String and Integer if its an ID or a String and Array if its a caption. Used some logic to minimize the attribute mutations which solves this issue. 
Tested manually with and without the Gutenberg plugin running.
=> Fix gallery captions and custom links disappearing

src/extensions/advanced-controls/index.js
Recent PR #1543 introduced methods to attach to component lifecycle methods. While the PR 1543 was perfectly acceptable for use with the Layout Selector, it did not solve the issue for when the editor first loads, and before components update. 
This PR includes logic to use both `componentDidMount` and `componentDidUpdate` lifecycle methods to more consistently apply advanced margins within the editor.
**Bugged**
**Fixed**
Tested manually in the browser with and without the Gutenberg plugin active.
=> Improve consistency of advanced margin propagation

src/blocks/alert/test/__snapshots__/save.spec.js.snap, src/blocks/alert/test/save.spec.js
Adding tests for the alert block, on save. 
Closes #854
- No changes besides the tests. Just being sure that on save, the block saves correctly the different attributes.
- Running tests locally for this block.
=> Add tests for the `alert` block save.

src/utils/block-helpers.js
Unit tests on master branch are failing due to use of `wp.blocks...` API as opposed to properly importing components `import { getCategories } from '@wordpress/blocks';`. This PR switches to import and resolves test failures.
Tested locally. Tests now pass.
=> Fix unit tests by importing getCategories

src/extensions/advanced-controls/index.js
Recent PRs  #1518 #1548 and #1543 made changes to the advanced margin controls. These methods worked but rely on an outdated method of hooking into React lifecycle that has now been replaced with integrated methods.
This PR makes the change of using newer React Hooks. In this case, we are using useEffect to hook into `componentDidMount` and `componnetDidUpdate` and are passing in the props `[ noBottomMargin, noTopMargin ]` which cause `useEffect` to execute when argument props update.
Major JavaScript non-breaking changes. This is an improvement in code quality, readability, and performance.
Tested locally with and without the Gutenberg plugin active.
=> Use React hooks to improve Advanced Margins feature

src/extensions/layout-selector/editor.scss
I can't identify why exactly, but Gutenberg recently changed how multi-selected blocks display (with some opaque).
=> Fix multi-selected layout issue

src/blocks/accordion/accordion-item/test/__snapshots__/save.spec.js.snap, src/blocks/accordion/accordion-item/test/save.spec.js
Adds Jest unit tests to the Accordion block. These are the final tests to close our the [Jest Unit Test Coverage project](https://github.com/godaddy-wordpress/coblocks/projects/13).
Closes #853 
Ran the suite, all tests passed and snapshots created.
=> Accordion block save function tests

CONTRIBUTORS.md, src/js/coblocks-lightbox.js
Only extracts plain text and converts html code (e.g. &amp;) into text before injecting it into lightbox captions.
Only `textContent` instead of `rawHTML` [here](https://github.com/godaddy-wordpress/coblocks/blob/master/src/js/coblocks-lightbox.js#L103).
However, that means that no html code can be used in said captions, e.g. bold, italics. I have been looking for a way to achieve that, maybe that could be implemented in the future.
Implemented it on the website I'm currently working on.
- [x ] My code is tested
Closes #1558
=> Allow HTML formatted text within Lightbox captions

.dev/bin/setup-test-specs.sh, src/extensions/coblocks-settings/test/coblocks-settings.cypress.js, src/extensions/colors/test/apply-style.spec.js, src/extensions/colors/test/classes.spec.js, src/extensions/colors/test/transform.spec.js, src/extensions/lightbox-controls/test/lightbox-controls.cypress.js, src/extensions/padding-controls/test/padding-controls.cypress.js, src/extensions/replace-image/test/remove-image.cypress.js, src/extensions/typography/test/apply-style.spec.js
This updates our `.dev/bin/setup-test-specs.sh` script to also check for modified files within the `src/extensions` directory when setting up specs for CI.
=> Detect modified code in extensions when setting up test specs

src/blocks/hero/edit.js
Resolves #1550 
Manually tested the changes.
=> Fix errors in hero block resize

src/blocks/click-to-tweet/styles/editor.scss
This PR is a quick style fix to adjust the SVG within the "via" toolbar component in the Click to Tweet block. Tested with core WP and Gutenberg 8.5.1
Before: 
After:
=> Fix Click to Tweet inline toolbar via SVG

src/blocks/post-carousel/block.json, src/blocks/post-carousel/edit.js, src/blocks/post-carousel/inspector.js, src/blocks/posts/block.json, src/blocks/posts/edit.js, src/blocks/posts/inspector.js
Post and Post carousel blocks use core component QueryControls. The QueryControls component has changed over time and backward compatibility had not been properly implemented. [This diff](https://github.com/WordPress/gutenberg/commit/e17d104ee3fe6eb8d81373226ab73096f59f9ba3?diff=unified#) shows where the onChange prop associated with CategorySelect had been moved to the proposed replacement component FormTokenField. This removal of props without backward compatibility had been reported on Gutenberg [Here](https://github.com/WordPress/gutenberg/issues/23285). [This PR here](https://github.com/WordPress/gutenberg/pull/23419) has been merged and is reported to fix the issue yet the fix failed to replace the original onChange function.
This failure in maintaining backward compatibility …
=> Fix Post and Post Carousel blocks compatibility across versions

docs/hooks/settings-panel.md, src/extensions/coblocks-settings/coblocks-settings-modal.js, src/extensions/coblocks-settings/coblocks-settings-slot.js
Refactor of CoBlocks settings modal to use SlotFill components. All existing modal components are now Fill components. Helper function has been created to enable developers to easily extend the CoBlocks settings modal with complete react components.
Docs have been updated in this PR to show how to use the new helper function. Please review docs for example.
JavaScript changes.
Tested locally within CoBlocks plugin with and without the Gutenberg plugin active.
=> Enable extensibility of Settings panel using SlotFill component

src/blocks/gallery-collage/styles/style.scss, src/blocks/gallery-masonry/styles/style.scss, src/blocks/gallery-offset/styles/style.scss, src/blocks/gallery-stacked/styles/style.scss
Removes the list style/padding/margin that 5.5 RC and Gutenberg 8.3+ applies, from our gallery blocks. 
Was originally in https://github.com/godaddy-wordpress/go/pull/555 but moved and tested here instead.
=> Remove editor list styles from gallery blocks

src/components/heading-toolbar/icon.js
Update the HeadingLevel Icon to match Gutenberg.
Update the height/width of the SVG.
https://raw.githubusercontent.com/WordPress/gutenberg/47ae410fc4bff9e5d6b0796480b28257c9e1705e/packages/block-library/src/heading/heading-level-icon.js
=> Update the HeadingLevel Icon to match Gutenberg

src/extensions/lightbox-controls/styles/style.scss
The lightbox control displays, even if the "Image settings" panel is closed.
Style fixes
=> Fix lightbox extension display for core blocks

src/extensions/image-crop/index.js
CoBlocks added a Crop-Settings utility for use with `core/image` block. With the imminent release of WP 5.5 the image block now has crop controls provided by Core. This PR removes support for `core/image` from the Crop Settings utility.
The Crop-Settings utility still exists in its original state with support only for `core/cover`.
Minor JavaScript change.
Tested locally with and without the Gutenberg plugin active.
=> Remove core/image support from Crop Settings utility

src/blocks/gallery-carousel/inspector.js, src/blocks/gallery-collage/inspector.js
Gallery controls are out of order across blocks. This PR re-arranges UI controls for all CoBlocks gallery blocks for a more consistent experience.
Simple JavaScript changes.
Minor ESLint fix.
Tested locally within the editor.
=> Move Gallery UI controls within the interface for consistency

src/blocks/media-card/styles/editor.scss
Media Card block uses the ResizableBox component from Core WordPress. Due to [changes in markup](https://github.com/WordPress/gutenberg/pull/21822) within the editor, a number of overriding styles for the editor had not been activating. 
This PR introduces the necessary CSS changes to correctly apply in the case of WordPress 5.4.2 as well as 5.5.
Fixes to block CSS.
Tested manually and E2E.
Tested with WP 5.4.2 and 5.5.
Tested with and without the Gutenberg plugin active.
=> Fix Media Card resize capability

src/js/coblocks-lightbox.js
The CoBlocks Lightbox works by adding `click` event listeners to document elements. Previous iterations of Lightbox worked by adding a click listener to the `img` elements which were arguably at the bottom of the document hierarchy. Because the event listener was near the bottom of hierarchy we made it possible for events to fire on elements that reside above our selected target. As a result of this bug, the Lightbox for Go theme when using the Carousel Gallery block would not function. 
This PR changes the listener target from the lowest `img` element to the parent `figure` element of each respective image. This allows the event bubbling to function as expected even if theme styles result in click events firing on the Figure or the Img elements. 
Minor JavaScript change to use `.closest( …
=> Fix Lightbox use with Go theme and Carousel Gallery block

.dev/bin/setup-test-specs.sh, src/extensions/advanced-controls/index.js
Closes #1364
The `advanced-controls` extension for CoBlocks had been inadvertently adding an `InspectorAdvancedControls` where it should not be. This PR adds logic to exclude the `InspectorAdvancedControls` component when necessary.
Tested manually within the editor.
Tested with and without the Gutenberg plugin active.
=> Prevent empty Advanced panel from showing on blocks

src/blocks/accordion/edit.js, src/blocks/author/controls.js, src/blocks/author/styles/editor.scss, src/blocks/events/appender.js, src/blocks/events/styles/editor.scss, src/blocks/food-and-drinks/appender.js, src/blocks/food-and-drinks/food-item/edit.js, src/blocks/food-and-drinks/food-item/styles/editor.scss, src/blocks/food-and-drinks/styles/editor.scss, src/blocks/form/fields/coblocks-option.js, src/blocks/form/fields/multi-field.js, src/blocks/gallery-collage/edit.js, src/blocks/gif/controls.js, src/blocks/logos/controls.js, src/blocks/media-card/media-container.js, src/blocks/row/edit.js, src/blocks/services/service/edit.js, src/components/background/controls.js, src/components/block-gallery/gallery-image.js, src/components/crop-settings/index.js, src/components/grid-control/toolbar.js, src/components/typography-controls/index.js, src/components/typography-controls/styles/editor.scss
Replace all instances of IconButton with core Button component.
JavaScript changes to deprecate IconButton component in favor of Button component.
Tested manually in the browser and e2e.
No deprecations needed for this change.
=> Deprecate IconButton in favor of Button component

src/extensions/coblocks-settings/test/coblocks-settings.cypress.js
Failing tests on the master branch for these tests. This PR will fix failing tests on master for the CoBlocks settings controls. 
Selector used within .cypress.js file.
Tested manually and e2e
=> Fix test selectors used for the CoBlocks Settings E2E tests

src/blocks/shape-divider/deprecated.js, src/blocks/shape-divider/test/shape-divider.cypress.js
Closes #1594 
The shape divider block at one point generated content with differing class names assigned by default. This is likely due to changes within the Advanced Controls extension over time. 
By using an array of attribute strings that are injected from the Advanced Controls extension we are able to iterate through possible values easily while reusing significant portions of code and improving readability. 
```javascript
[ 'noTopMargin', 'noBottomMargin' ]
```
JavaScript.
Tested manually using markup from #1594
=> Introduce Shape Divider deprecations related to extensions

src/blocks/food-and-drinks/food-item/deprecated/deprecatedIcons.js
Fixes #1595. The Food & Drinks deprecation was failing on the icons because we are using an upgraded version of the `@wordpress/primitives` package and those functions have changed. The fix involved pulling in the old functions from this package into the `deprecatedIcons.js` file.
I don't really like how this is done but it works. It would be nice to pull in the package at the specific version so this file can use it directly.
=> Fix SVG icon deprecation in the Food and Drinks block

src/blocks/food-and-drinks/styles/style.scss
Fixes #1629. The block properly deprecated but column styles were overriding the list-style css.
=> Fix list styling of Food and Drinks block when column classes exist

src/extensions/coblocks-settings/styles/style.scss
Styles added to fix the alignment of descriptions in the editor settings modal
Bug fix
Inspected visually.
=> Fix alignment of descriptions in the editor settings modal

src/blocks/icon/styles/editor.scss
Remove unecessary CSS to fix Icon block style previews.
Bug fix
Inspected visually.
=> Fix Icon block style previews

src/blocks/post-carousel/block.json, src/blocks/post-carousel/deprecated.js, src/blocks/post-carousel/index.js, src/blocks/post-carousel/index.php, src/blocks/posts/block.json, src/blocks/posts/deprecated.js, src/blocks/posts/index.js, src/blocks/posts/index.php
Closes #1632 
Following the lead of the Gutenberg team, this PR introduces measures that will allow proper migration/deprecation from previously configured and published blocks into a working state using modern interface and features. 
In this case, the `core/latest-posts` block had a number of breaking changes related to the implementation of a tokenized category selector. The new selector requires new logic and a new attribute schema.
This change is inspired by this [PR in Gutenberg](https://github.com/WordPress/gutenberg/blob/d0ca2551fdaa460d1ce4dc0a3bf0125ea4dbdba2/packages/block-library/src/latest-posts/index.php#L50). This PR resolves a bug with migration from old-style `coblocks/posts` and `coblocks/post-carousel` attributes.
This can be replicated using old markup:
```
OR
``` …
=> Introduce Posts and Post Carousel block deprecations

src/js/coblocks-lightbox.js
Remove gallery lightbox arrows when only one image is used in a gallery.
Resolves #1601 
Manually. Created one gallery of each type with only one image. Each gallery had the `lightbox` property turned on.
=> Remove arrows from lightbox in single image galleries

src/blocks/form/styles/editor.scss
Remove the box-shadow from the selected form field.
Manually
=> Remove box shadow from selected form field

.dev/tests/phpunit/includes/test-coblocks-form.php, includes/class-coblocks-block-assets.php, includes/class-coblocks-form.php, src/blocks/form/edit.js, src/blocks/form/index.js, src/blocks/form/test/form.cypress.js
This PR introduces a custom Success Text field for the form block, allowing users to display a custom message back to the user once the form has been submitted.
Resolves #1519 
Manually tested. We need to include Cypress tests for this feature.
=> Introduce ability to define a custom 'Success Message' setting in the form block

src/blocks/form/variations.js, src/blocks/row/variations.js
Variations in our Row and Form blocks are not displaying the labels associated with each variation. Upon investigation, I uncovered that each variation's label should be defined with a `title` key, instead of label. 
=> Fix variation titles for Row and Form blocks

src/blocks/accordion/accordion-item/controls.js, src/blocks/row/column/icon.js, src/blocks/row/column/index.js, src/blocks/row/edit.js, src/blocks/row/index.js
This PR addresses a few small follow-up icon fixes for the G2 styling that came in WordPress 5.5  for the Row, Accordion, and Column blocks.
=> Minor icon fixes

src/blocks/accordion/accordion-item/edit.js, src/blocks/accordion/edit.js, src/blocks/author/edit.js, src/blocks/features/edit.js, src/blocks/features/feature/edit.js, src/blocks/food-and-drinks/edit.js, src/blocks/form/edit.js, src/blocks/hero/edit.js, src/blocks/media-card/edit.js, src/blocks/pricing-table/edit.js, src/blocks/services/edit.js
This PR adds support for the `__experimentalCaptureToolbars` InnerBlocks prop, which was introduced in WordPress 5.5. This makes the parent block inherit the child blocks' toolbars, as to keep the interface a bit cleaner. 
I've added it to the following blocks: 
New feature (non-breaking change which adds functionality) 
We need to ensure this does not cause issues in < WordPress 5.5.
=> Add support for __experimentalCaptureToolbars

src/blocks/pricing-table/controls.js
Fixes #1670
Use ToolbarGroup instead of Toolbar to render Pricing Table controls correctly. This fixes a bug that's present when CoBlocks are used with Gutenberg >=8.8.0. This solution is based on how the [Gutenberg's alignment toolbar is implemented](https://github.com/WordPress/gutenberg/blob/v8.9.3/packages/block-editor/src/components/block-alignment-toolbar/index.js#L69-L86).
| Before | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/1451471/92619797-41383000-f2c2-11ea-94e1-bdd4430eef53.png) | ![image](https://user-images.githubusercontent.com/1451471/92619855-4eedb580-f2c2-11ea-8ddf-f86d7a9c027d.png) |
Confirmed happening with activated Gutenberg plugin v8.8.0 and later.
=> Pricing Table: Use ToolbarGroup to render controls correctly

includes/class-block-patterns.php, src/extensions/block-patterns/index.js
CoBlocks has implemented components that are bundled natively with WordPress 5.5 but which are not bundled with 5.4.2 resulting in editor crash when editing or adding a new post.
Closes #1666.
This PR adds new logic to conditionally load Block-Patten extension.
Logic to PHP and JavaScript to conditonally load block patterns extension.
Tested manually using WordPress 5.4.2 as well as 5.5.
=> Fix editor crash when running CoBlocks and WordPress 5.4.2

includes/class-coblocks-form.php
There was a bug with the output of the required text, which should be hidden on initial load. Because we were passing the HTML through `esc_html()` the markup was not properly parsed on the front of site. This PR switches things to use `wp_kses_post()`  which parses the HTML as expected.
=> Fix required checkbox/radio hidden message escaped markup

.circleci/config.yml, src/extensions/layout-selector/index.js, src/extensions/layout-selector/test/layout-selector.cypress.js
Fixes #1664
Bug fix
Manually and E2E test included.
=> Prevent layout selector on posts saved as a draft

src/blocks/form/fields/checkbox/transforms.js, src/blocks/form/fields/date/transforms.js, src/blocks/form/fields/hidden/transforms.js, src/blocks/form/fields/name/transforms.js, src/blocks/form/fields/phone/transforms.js, src/blocks/form/fields/radio/transforms.js, src/blocks/form/fields/select/transforms.js, src/blocks/form/fields/text/transforms.js, src/blocks/form/fields/textarea/transforms.js, src/blocks/form/fields/website/transforms.js
This PR builds on #1676 by adapting the transformed field label to it's original label. For example, if transforming a Date block into a Website block, the label "Date" becomes "Website".
=> Transform Form fields with with proper labels

src/blocks/gallery-collage/styles/style.scss
Add `margin: 0` to collage gallery captions.
This prevents theme styles from introducing a margin to gallery
captions.
Fixes https://github.com/Automattic/themes/issues/2374
**Varia theme**
Before:
After:
Apply the styles and confirm in browser.
=> Collage block: Add caption margin zero

src/components/heading-toolbar/index.js
Use ToolbarGroup instead of Toolbar to render HeadingToolbar controls correctly. This fixes a bug that's present when CoBlocks are used with Gutenberg >=8.8.0. This solution is based on how the Gutenberg's alignment toolbar is implemented.
Before: 
After:
Confirmed happening with activated Gutenberg plugin v8.8.0 and later - and with core WordPress.
=> HeadingToolbar: Use ToolbarGroup to render controls correctly

src/components/form-label-colors/label-color-control.js
I had a realization that I was using a superfluous block exclusion here where it is not required. This behavior is already handled here - except for cases where the same attribute schema exists regardless of defined block supports.
https://github.com/godaddy-wordpress/coblocks/blob/4db325197106746692240a29d64818adcb9b4fe6/src/components/form-label-colors/index.js#L7-L11
Because we might end up altering attributes of children blocks that do not have explicit form label support, this component has been modified to allow attribute propagation to only blocks with defined supports. (form child blocks)
This change prevents colors from being set on a child paragraph block within the Form block.
Exclude blocks without defined support.
Remove and replace JavaScript logic. This change will use …
=> Tweak Form label color controls

src/blocks/gallery-carousel/edit.js
E2E failures were missed for the Gallery Carousel block. This PR fixes the edit function to properly import the Icon component for use within the editor. Also made changes for eslint to the Edit function. 
JavaScript
Tested manually. E2E
=> Resolve errors around icon imports

src/blocks/author/controls.js, src/blocks/events/edit.js, src/blocks/gist/controls.js, src/blocks/logos/controls.js, src/blocks/map/controls.js, src/blocks/post-carousel/edit.js, src/blocks/posts/edit.js
Update icons in certain blocks to utilize `@wordpress/icons` edit icon
Update to icons, non-breaking change.
=> Update icons to utilize @wordpress/icons edit icon

package.json, src/blocks/gallery-carousel/styles/editor.scss, src/blocks/gallery-collage/styles/editor.scss, src/blocks/gallery-masonry/styles/editor.scss, src/blocks/gallery-masonry/styles/style.scss, src/blocks/gallery-masonry/test/gallery-masonry.cypress.js, src/blocks/gallery-offset/styles/editor.scss, src/blocks/gallery-stacked/styles/editor.scss, src/components/block-gallery/gallery-image.js, src/components/block-gallery/styles/editor/_gallery-item-menus.scss, src/components/block-gallery/styles/editor/_gallery-item.scss, yarn.lock
CoBlocks galleries but specifically Masonry gallery block are affected by a bug which results in un-wanted margins being applied to the markup causing undesirable aesthetics. This change introduces some new styles to handle the changes in margin from core styles.
I suspect there may be more instances where superfluous margins are being applied but I cannot locate those areas.
SCSS changes. 
Tested manually with all CoBlocks galleries. Fixed all areas that have been identified to include superfluous margins from core styles.
=> Add styles to fix appearance of Gallery blocks

src/blocks/share/styles/editor.scss
Block alternate style previews and the associated CSS styles have changed over time. The style changes have resulted in a broken user interface for selecting styles where a user cannot properly preview the alternate styles. Changes in this PR fix the appearance of the block style previews so a user may properly preview the alternate block styles.
**Before**
**After**
CSS changes that apply to both Share and Social Profiles blocks.
Tested manually, E2E, with Go and TwentyTwenty as well as running the Gutenberg plugin.
=> Enhance social block style previews

src/blocks/row/controls.js
This PR changes the component used within the Row block from Toolbar to ToolbarGroup. This change allows for proper use of the toolbar controls while in the editor.
**before**
**after**
Tested manually within the editor and using Gutenberg plugin.
=> Fix appearance of Row block column spacing controls

src/blocks/post-carousel/styles/editor.scss, src/blocks/post-carousel/styles/style.scss
Fix the post carousel arrows in the editor and front end, and fix the text align in the post carousel block in an RTL environment.
Manually tested in an RTL environment.
=> Fix post carousel arrows/text-align when in an RTL environment

src/blocks/click-to-tweet/edit.js, src/blocks/click-to-tweet/test/click-to-tweet.cypress.js, src/blocks/food-and-drinks/food-item/edit.js, src/blocks/food-and-drinks/food-item/test/food-item.cypress.js, src/blocks/form/fields/submit-button/edit.js, src/blocks/pricing-table/pricing-table-item/edit.js, src/blocks/pricing-table/pricing-table-item/test/pricing-table-item.cypress.js
Fix the console warning being thrown due to `formattingControls` being deprecated in favor of `allowedFormats`.
Manually tested each block for any regressions, ran related jest tests and checked that the console warnings are now gone.
=> Fix formattingControls console warnings

src/blocks/gallery-carousel/styles/style.scss, src/blocks/gallery-carousel/test/gallery-carousel.cypress.js
Fix the carousel arrows in an RTL environment.
***Note:*** I changed the arrow button background to black in the DOM for the screenshot so the arrow icons were easier to see.
Manually tested in an RTL environment.
=> Fix carousel arrows in an RTL environment

src/blocks/events/edit.js, src/blocks/form/edit.js, src/blocks/icon/inspector.js, src/blocks/map/edit.js, src/blocks/map/inspector.js, src/blocks/post-carousel/edit.js, src/blocks/posts/edit.js, src/blocks/row/edit.js, src/components/crop-settings/index.js, src/components/size-control/index.js, src/extensions/layout-selector/index.js
The Button component provided by core had deprecated the prop `isLarge` over time. CoBlocks has a number of instances of the use of this deprecated prop resulting in warning notices within the browser console. This PR will remove all un-needed references to unused props to resolve these notices.
Reviewed all instances where this property has been removed in both 5.5.1 as well as 5.4.2 and have decided there are no aesthetic changes between these versions. These properties should be safe to remove without issues. 
Tested manually. Editor UI components only.
=> Remove deprecated isLarge prop from button componnets

src/blocks/gallery-collage/test/gallery-collage.cypress.js
Working this PR I found a bug with the Gallery Collage block and its parsing of caption attribute when transforming. Bug report for that issue here: https://github.com/godaddy-wordpress/coblocks/issues/1707
Minor test changes to properly focus on the text inputs.
Tested manually and E2E.
=> PR to allow Gallery Collage tests to pass

src/blocks/gallery-stacked/test/gallery-stacked.cypress.js
This PR introduces fixes to the Stacked Gallery block tests to allow for properly setting caption inputs on all tested browsers.
Minor JavaScript change to tests.
Manually and E2E.
=> Allow Stacked Gallery tests to pass

.dev/tests/cypress/helpers.js, src/blocks.js, src/components/media-filter-control/index.js, src/components/media-filter-control/test/media-filter-control.cypress.js, src/extensions/image-filter/index.js
Introduce image filters to the core/image block.
Note: Currently the gallery block filter changes _all_ images. It's not possible to change the filter of individual images, with this current implementation. I am going to revisit this in the morning.
TBA
Manually tested. May need to introduce jest tests.
=> Introduce image filters to core image block

src/components/media-filter-control/index.js
Display a preview of the image filter when hovered.
Manually. Probably needs tests.
=> Introduce an image filter preview to the media-filter-control component

src/blocks/media-card/index.js
Remove keyword search terms from the Media Card block. Reducing searchability for the Media Card block but not yet making the block un-insertable.
Note: Since the name of the block is a searchable token, I would suggest registering Media Card block without the ability to insert if that behavior is desired. 
https://github.com/godaddy-wordpress/coblocks/blob/31938b07cf68b0910f408c5972ac794b5163e795/src/js/deprecations/deprecate-coblocks-buttons.js#L9-L25
Minor JavaScript change.
Tested manually
=> Remove search keywords from Media Card block

src/components/block-gallery/styles/style/_lightbox.scss
The Lightbox required minor style tweaks to ensure that an image would center on the screen while a lightbox is in use. In the case of extra long captions, the images would set to align with the left of the container.
**Before**
**After**
Minor style updates
Tested manually within the browser.
=> Fix image alignment within Lightbox when long captions exist

src/blocks/gallery-carousel/test/transforms.spec.js, src/blocks/gallery-carousel/transforms.js, src/blocks/gallery-collage/test/transforms.spec.js, src/blocks/gallery-collage/transforms.js, src/blocks/gallery-masonry/test/transforms.spec.js, src/blocks/gallery-masonry/transforms.js, src/blocks/gallery-offset/test/gallery-offset.cypress.js, src/blocks/gallery-offset/test/transforms.spec.js, src/blocks/gallery-offset/transforms.js, src/blocks/gallery-stacked/test/transforms.spec.js, src/blocks/gallery-stacked/transforms.js, src/components/block-gallery/shared/transforms.js
Changes over time in the way that transforms are registered by core has resulted in duplicate instances of registered block transforms. This PR removes duplicate transform registrations as well as removes some of the older deprecated transforms from gallery blocks. 
Working this PR I discovered a few Gallery transform bugs that should be addressed in scoped pull requests. 
https://github.com/godaddy-wordpress/coblocks/issues/1719 - Transformed galleries result in invalid gutter content.
https://github.com/godaddy-wordpress/coblocks/issues/1707 - Transformed galleries result in invalid caption content.
JavaScript changes.
Tested manually and with Jest.
=> Fix duplicated and remove deprecated gallery transforms

src/components/block-gallery/styles/editor.scss
This PR introduces SCSS fixes to allow for a proper UX with the media placeholder. 
SCSS changes.
Tested manually within the editor.
=> Fix Gallery placeholder UX across blocks

src/extensions/typography/index.js
Row block and Typography controls have integrated API using a utility function called `applyStyle`. The integrated controls ultimately result in increased confusion around the functionalities of both the Row block as well as the Typography controls. These controls should eventually be separated to avoid future situations where debugging either functionality is necessary.
This PR includes a logic fix to allow for properly applying both Row styles as well as Typography styles. Original logic introduced in https://github.com/godaddy-wordpress/coblocks/pull/1515 as a fix at the time.
JavaScript
Tested manually. 
Tested with 5.4.2 & Gutenberg 9.1.0. 
Tested with 5.5.1 & Gutenberg 9.1.0.
=> Fix Row block and Typography Controls 

src/blocks/features/edit.js, src/blocks/features/inspector.js, src/blocks/features/test/features.cypress.js
The columns count controls had a few situations which could result in either `undefined` or a number > 4 being set for the columns attribute. This caused a number of strange behaviors most notably broken classnames. Another bug is that the inner-block count is not tied to the column count as it has been in the past. This is due to changes with core InnerBlocks component over time. 
This PR includes fixes for both of the bugs described above.
JavaScript changes. Should not require any deprecations.
E2E. Manually. With Gutenberg. Tested with 5.4.2 as well as 5.5.1.
=> Fix Features block column count controls

src/components/block-gallery/shared/transforms.js
Preserve gallery animations whenever you transform between blocks.
Manually tested by adding an animation to a gallery block and transformed it to other blocks.
=> Preserve gallery animations on transform

.dev/tests/jest/setup-globals.js, package.json, src/extensions/layout-selector/index.js, src/extensions/layout-selector/test/layout-preview.spec.js, yarn.lock
Adds a filter named `coblocks.layoutPreviewBlocks` that allows the filtering of the blocks passed into the layout block preview within the layout selector.
New feature
=> Filter the blocks passed into layout block preview

.circleci/config.yml
Currently we've only tested with Composer v1 and until we test against v2 (for which builds are currently failing), we need to force v1.
=> Define which version of composer to use within CI jobs

src/blocks/share/styles/editor.scss
In an attempt to fix style previews for the Shape Divider and Social blocks, we've introduced a bug that affects all other style previews. This reverts those misapplied styles.
Before:
After:
=> Fix broken style previews

src/components/info-popover/index.js, src/components/info-popover/styles/editor.scss, src/extensions/block-patterns/modal.js, src/extensions/block-patterns/styles/style.scss
Adds an icon button to the heading of the "Save Design Pattern" modal which displays a popover with helpful information on hover and on click.
This new icon button with popover has been added as the `InfoPopover` component so that it can be reused across CoBlocks.
Enhancement
Manually
=> Add hint to the "Save Design Pattern" modal

src/extensions/layout-selector/index.js, src/extensions/layout-selector/store.js
We need to save the Layout Selector visibility in its store
=> Define Layout Selector visibility in store

src/blocks/click-to-tweet/deprecated.js, src/extensions/typography/index.js
Add logic to deprecate Typography controls from Click-To-Tweet block. Invalid block content will occur unless the typography attributes are registered with a deprecated save function.
**Configured Typograhy Controls**
**Disabled Controls**
**Deprecated Controls**
JavaScript and new logic changes around click-to-tweet block deprecation.
=> Add logic to deprecate typography controls from Click-To-Tweet block

src/blocks/media-card/test/transforms.spec.js, src/blocks/media-card/transforms.js
Simple changes here to remove transform functions as well as corresponding jest tests for those transforms. With the imminent deprecation of the Media-Card block, this change will ensure that users cannot unexpectedly use a Media-Card block.
JavaScript changes.
Jest tests correctly failed when transforms are removed. This is the expected behavior for the tests. The tests have now been removed and behavior has been manually tested.
=> Remove ability to transform into Media Card block

src/blocks.js, src/blocks/media-card/test/media-card.cypress.js, src/js/deprecations/deprecate-coblocks-media-card.js
Add logic to deprecate CoBlocks media-card block by preventing common block insertion. Since the block is still registered a user is allowed to duplicate or copy existing media-card blocks without issue. Another thing to consider here is that the media-card does not automatically transform to a media-text block as does happen from the `coblocks/buttons` -> `core/buttons` deprecation. 
JavaScript changes to allow for block deprecation of the media-card block.
Tested manually
=> Add logic to prevent insertion of Media Card block

package.json, src/blocks/hero/test/hero.cypress.js, src/blocks/share/test/share.cypress.js, src/blocks/social-profiles/test/social-profiles.cypress.js, src/extensions/layout-selector/test/layout-selector.cypress.js, src/extensions/padding-controls/test/padding-controls.cypress.js, yarn.lock
This PR is focused on both upgrading Cypress to the latest version which includes numerous bug-fixes and also addressing failed tests within the CI pipeline. 
Cypress upgraded to 5.6.0.
One test skipped - Hero block has a bug which has been identified here: https://github.com/godaddy-wordpress/coblocks/issues/1762
Updated yarn package and yarn.lock.
JavaScript.
Tested manually and E2E. `npx cypress open`
=> Cypress E2E Testing Updates

.circleci/config.yml
This PR changes the PHP image used for E2E jobs in the CoBlocks CI-CD pipeline.
**Original**
`- image: circleci/php:latest-node-browsers`
**Changed to**
`- image: circleci/php:7.3.23-node-browsers`
Configuration changes for Circle Ci
Tested in the CI pipeline
=> Use a static php container in E2E pipeline

.circleci/config.yml
Simple change and optimization of install job in CI pipeline. Instead of copying the plugin files, we should create a symlink to those files.
Configuration changes.
Tested in the CI-CD pipeline.
=> Use a symlink instead of copy

includes/class-coblocks-block-assets.php, src/js/coblocks-lightbox.js
The Lightbox had been missing `aria-labels` for the interactive buttons on screen. This PR introduces the needed `aria-labels` for the `left`, `right`, and `close` buttons.
```html
<button class="coblocks-lightbox__close" aria-label="Close Gallery"></button>
...
<div class="arrow-left" aria-label="Previous"></div>
...
<div class="arrow-right" aria-label="Next"></div>
```
Minor changes in Lightbox Markup. No deprecation needed. 
Tested manually in the browser.
=> Add aria-labels to the CoBlocks Lightbox utility

src/components/size-control/index.js
Closes https://github.com/godaddy-wordpress/coblocks/issues/1783
Refactor SizeControl component to use the existing shared `OptionSelectorControl` component. This required minimal changes and allows SizeControl use with existing blocks as well as improves the visual consistency compared to `GutterControls`.
Changes to shared components for improvements to visual consistency.
Tested manually in the editor.
=> Refactor SizeControl component for improved visual consistency

.dev/tests/cypress/helpers.js, src/components/block-gallery/styles/style/_lightbox.scss, src/extensions/lightbox-controls/test/lightbox-controls.cypress.js, src/js/coblocks-lightbox.js
Fixes #1782 
Aligned images are not working as expected with the CoBlocks lightbox. This PR introduces a fix to allow aligned images and captions to be displayed in the Lightbox.
JavaScript changes. Improvements to readability.
New e2e tests written to test against aligned gallery blocks with Lightbox.
=> Allow aligned images in CoBlocks Lightbox

src/extensions/padding-controls/index.js, src/extensions/padding-controls/padding-wrapper.js, src/extensions/padding-controls/test/padding-controls.cypress.js, src/styles/style/has-padding.scss
Modified Padding Controls extension to add custom controls.
Added styles and apply style variables to group elements.
JavaScript and styles changes.
No Deprecations needed.
Tested manually in the editor.
E2E.
=> Introduce custom padding controls to core/group block

src/extensions/animation/index.js, src/extensions/layout-selector/index.js, src/extensions/layout-selector/layout-selector-results.js, src/extensions/layout-selector/store.js, src/extensions/layout-selector/test/layout-preview.spec.js, src/extensions/layout-selector/test/layout-selector.cypress.js
A "most used" section has been added to the sidebar of the layout selector. This section works similar to how the most used blocks section of the block inserter
Unit tests.
=> Add "most used" section to the layout selector.

src/extensions/layout-selector/store.js, src/extensions/layout-selector/test/layout-selector.cypress.js
This PR removes a lot of the conditionals we used to determine when the layout selector is shown and simply checks the post's `isCleanNewPost` state.
The only downside to this currently is that there is no way to "reset" the page or show the layout selector again. With our old inconsistently behaving conditions, we attempted to display the layout selector if the post was unpublished and the undo states were removed (undo action was performed until no more were available).
I do think this wasn't a great experience because you could never perform a redo action if you mistakenly hit undo. The only way to close the layout selector was to use a "blank" layout changing the edit states permanently. If it makes sense we might want to think around this experience.
- Bug fix
Manual and E2E tests
=> Ensure layout selector modal is shown only when creating new pages

.dev/config/webpack.config.js, includes/class-coblocks-block-assets.php, src/extensions/layout-selector/editor.scss, src/extensions/layout-selector/hooks/useCategories.js, src/extensions/layout-selector/hooks/useComputedLayouts.js, src/extensions/layout-selector/index.js, src/extensions/layout-selector/index.php, src/extensions/layout-selector/layout-selector-results.js, src/extensions/layout-selector/store.js, src/extensions/layout-selector/test/layout-preview.spec.js, src/extensions/layout-selector/test/layout-selector.cypress.js
This PR introduce several mecanism to defer parsing of blocks to prevent the event loop from staling other procedures (as animation for instance).
- Uses new hook called useComputedLayouts to memoized blocks based on categories being showed. 
- On page load, process a queue of the "most-used" blocks on requestIdleCallback with timeout of 1s.
- Implement parsing of new category block as a side effect of changing a category (which is now in the redux store)
=> Use hooks for computed layout

src/blocks/gallery-carousel/edit.js
Resolves https://github.com/godaddy-wordpress/coblocks/issues/1773
The first carousel image is hidden on initial load. Related:
It looks like the final image is being placed at the end of the carousel, and not in the proper location before the first. When a new image is added, or the developer console is brought up, the carousel reinitializes and the issue fixes itself.
Without re-initializing the carousel again, the easiest fix is to set the `initialIndex` in `flickityOptions` resolves the issue. However, this means that the second selected image will now be the first image shown in the carousel on initialization.
Manually checked.
=> Fix initial image hidden on carousel initialization

src/js/coblocks-animation.js
Resolves #1737 where animations failed if IntersectionObserver was not available in older browsers.
Bug fix
Manually with iOS Simulator based on reproduction steps provided in the bug report.
=> Disable animations when IntersectionObserver is not detected

package.json, src/extensions/coblocks-settings/coblocks-settings-modal.js, src/extensions/coblocks-settings/coblocks-settings-slot.js, src/extensions/layout-selector/editor.scss, src/extensions/layout-selector/index.js, src/extensions/layout-selector/layout-selector-slot.js
I should be able to use the layout selector on my mobile device
=> Layout Selector Mobile friendly

src/blocks/logos/styles/style.scss
Try switching from `em` based CSS to `vw`. This should allow the element size to be based on viewport size.
Closes #1808
Minor CSS change. Should this be `%`, `vmax` or `vmin` instead? 
Tested manually within the responsive viewport browser.
=> Allow Logos & Badges block to behave responsively

src/extensions/layout-selector/editor.scss
Some buttons on the Layout selector have a barely visible `:focus` state. Accessibility can be improved by mirroring existing button component `:focus` styles.
Minor CSS changes.
Tested in Firefox and Chrome.
=> Try new focus styles for the Layout Selector

src/blocks/gist/edit.js, src/blocks/gist/styles/editor.scss
Tweak Gist block styles to more closely resemble the ShortCode block. Identified and fixed a bug with editor width when setting the Gist block to wide width and when Gist content is wide.
Style changes. JS Markup changes - no deprecation needed.
Tested manually
=> Update Gist block styles to resemble ShortCode block

includes/class-block-patterns.php
Resolves #1775 
Remove the limit we have inside of `load_block_patterns()`.
=> Remove unintentional limit on block patterns

src/blocks/author/edit.js, src/blocks/author/styles/editor.scss
Author block had template lock in place preventing removal of Button block. This lock has been removed allowing adding and removal of button block.
CSS and minor JavasScript changes.
Tested manually in the editor. No deprecation needed.
=> Fix Author block button removal and image placeholder alignment

class-coblocks.php, src/blocks/posts/block.json, src/blocks/posts/edit.js, src/blocks/posts/index.php, src/blocks/posts/styles/style.scss, src/components/gutter-control/gutter-wrapper.php, src/utils/utils.php
Closes #1728 
API changes introduced in https://github.com/godaddy-wordpress/coblocks/pull/1576 caused an unintentional change in property syntax. Minor change within the `edit.js` file to allow images to properly render and controls along with them.
In addition to the syntax error when accessing properties, the `coblocks/posts` block also has a failure to properly apply gutter attributes and styles from the `Gutter Controls` component. 
Changes here properly apply attributes, styles, and classes to the `coblocks/posts` SSR block.
=> Fix Posts block layout

.dev/tests/cypress/helpers.js, src/blocks/gallery-carousel/test/gallery-carousel.cypress.js, src/blocks/gallery-collage/test/gallery-collage.cypress.js, src/blocks/gallery-masonry/test/gallery-masonry.cypress.js, src/blocks/gallery-offset/test/gallery-offset.cypress.js, src/blocks/gallery-stacked/test/gallery-stacked.cypress.js, src/components/block-gallery/gallery-image.js
Closes #1717 
This bug was originally introduced in this PR: https://github.com/godaddy-wordpress/coblocks/pull/1687
Changes here allow for gallery captions to be clicked and for the RichText typography options toolbar to remain present for user interactions.
Minor JavaScript change.
Tested manually within the editor.
=> Fix Gallery captions focus

.dev/tests/jest/helpers.js, src/extensions/layout-selector/layout-selector-results.js, src/extensions/layout-selector/test/layout-preview.spec.js
Remove animations from Layouts Selector
=> WPEX-1022 Remove animations from Layouts Selector

src/blocks/highlight/test/highlight.cypress.js
Closes #1832 
This PR Re-enables a skipped test around the use of FontSizes control.
E2E
=> Close FontSizes bug that exists with WP 5.6.1 but fixed with 5.6.2

.dev/bin/setup-test-specs.sh, src/components/media-filter-control/test/media-filter-control.cypress.js
JavaScript loops within these component tests are causing unexpected conditions in the CI environment.
Change here will properly reset between tests so that this test can pass.
Tested in E2E pipeline.
=> Fix E2E tests for Media Filter component

.dev/tests/phpunit/includes/test-coblocks-body-classes.php, includes/class-coblocks-body-classes.php, src/blocks/services/styles/editor.scss
Closes #1813 
When TwentyTwentyOne theme is active the services block image height overflows outside of the container. This PR adds a `is-twentytwentyone` admin body class and then tweaks then sets the height of the services block image back to `100%`.
Manually tested with and without TwentyTwentyOne active.
=> Fix services block image height in TwentyTwentyOne

includes/class-coblocks-form.php
Add a `From:` header to the form emails. This value is set to the name field, and if one is not set then it falls back to the site title.
New feature (non-breaking change which adds functionality).
Manually tested locally running MailHog. I was having some issues locally, so I will need to double check this is working as intended on a live site.
=> Add a from: header to the form emails.

includes/class-coblocks-body-classes.php, src/extensions/animation/styles/style.scss
Originally reported on WordPress.org, [here](https://wordpress.org/support/topic/coblocks-animations-not-working-with-amp/). This PR adds a `amp` class when the front of site is loaded via AMP, and then sets `opacity: 1;` on all `.coblocks-animate` elements. This was the simplest solution with the least amount of code.
It is worth noting that some of the galleries are not laid out properly due to AMP not loading any JS. Here is a masonry gallery, as an example.
Manually, locally, with the official AMP plugin. After installing, you can add `?amp` to the URL and it will force load via amp.
=> Set opacity to 1 on .coblocks-animate when in AMP

CONTRIBUTORS.md, src/blocks/accordion/edit.js, src/blocks/accordion/test/accordion.cypress.js
This is a proposed fix for #1768 
Bug fix
The automated test was only triggering the onMouseUp event. When you change it to a full click event in the test, it reproduce the error in the issue.
I have changed the onMouseUp event in the component to on MouseDown and it fixes the test and the behavior, from what I see.
=> Fix for the fact that sometimes too much accordion items were added

src/blocks/logos/save.js
When the Logos & Badges block is used and the image width is not configured by the user, the existing block logic will automatically determine the widths for the images. When the save function fires, there was an improper logic that did not properly determine the widths of images based on row count. Fixes here allow for proper render of Logos & Badges after saving and editor reload.
This change does **not** require a deprecated save function. The issue was around where attributes had been improperly parsed upon _initial_ save for unconfigured images. This condition cannot be met again after the initial save, thus no block validation errors will occur.
Closes #1811 
Minor save function change.
=> Fix Logos & Badges block sizing behavior

src/blocks/food-and-drinks/test/food-and-drinks.cypress.js
Fix Food & Drink block test reliability by using helpers to select the block.
Minor test changes. 
E2E
=> Improve Food & Drink block test reliability

src/blocks/hero/controls.js, src/blocks/hero/test/hero.cypress.js, src/components/background/controls.js
Hide the media flow popup menu when upload modal is visible
fixes - https://github.com/godaddy-wordpress/coblocks/issues/1580
Bug fix
wrote cypress test
=> Issue 1580

src/extensions/padding-controls/padding-wrapper.js, src/extensions/padding-controls/test/padding-wrapper.spec.js
Remove addition of child className to parent in PaddingWrapper
fixes #1862 
Bug fix
wrote unit test
=> Issue 1862

src/blocks/hero/deprecated.js, src/blocks/hero/save.js, src/blocks/hero/test/hero.cypress.js
~This test had been skipped because of issue #1762 . However, now it seems to pass and I am not able to reproduce the problem in Go and TwentyTwenty.~
This is a suggested fix for #1762. I have now found the problem. See later in the thread.
~Add a test~
Bug fix
=> Bug fix for text color in Hero block

src/components/block-gallery/styles/editor/_gallery-item.scss
An existing PR on Gutenberg has been merged: https://github.com/WordPress/gutenberg/pull/29860
This PR mirrors the fix and acts as a temporary fix when running 5.7.0 without the Gutenberg plugin.
Minor SCSS change.
Tested manually in Go, TwnetyTwenty, and TwentyTwentyOne.
=> Fix image replace flow for core gallery block

src/extensions/animation/styles/editor.scss
Fix the width of images in the image filter preview window. The preview is still about 3px taller than the image, so there is a small "tail" of background color beneath the image. The height of the parent container, holding the image, is auto generated, so I'm not sure the best way to set that.
=> Fix width of images in image filter previews

src/extensions/layout-selector/editor.scss
Fix layouts jumping around within the Layout Selector in Safari. I had to remove the spinner in Safari, there's a known bug with `column-count` that we can't fix.
=> Fix layouts jumping around within the Layout Selector in Safari 

src/blocks/posts/styles/style.scss, src/extensions/animation/styles/editor.scss
In Safari and IE, the posts block content height was incorrect. This PR fixes that issue.
Manually tested this in Safari. Confirmed no regressions were introduced in other browsers.
=> Fix posts block margin in Safari and IE

src/styles/editor.scss, src/styles/editor/preview.scss
The stacked gallery bottom margin was incorrect in the block preview window. This PR resolves the excessive bottom margin.
Manually.
=> Fix stacked gallery preview margin

src/blocks/gallery-carousel/inspector.js, src/blocks/gallery-stacked/inspector.js, src/components/responsive-tabs-control/index.js
The Masonry, Carousel and Stacked gallery blocks gutter value wasn't set in the `RangeControl` component inside of `ResponsiveTabsControl`, so the value wasn't displaying on initial loads and page reloads.
Bug fix (non-breaking change which fixes an issue) 
Manually.
=> Fix gallery gutter values not set

src/blocks/form/test/form.cypress.js
Sometimes in the E2E environment, the screen viewport does not center on the inputs thus we can receive errors. This PR forces the type event even if the input is out of view.
Test changes. Forced Inputs.
Tested in the E2E pipeline.
=> Force typing form inputs in E2E environment

.circleci/config.yml, src/extensions/layout-selector/index.js
Display a snackbar notice when a layout is selected from the layout picker.
=> Show a snackbar notice when a layout is added to a page

src/blocks/gallery-collage/edit.js
Fix invalid value being set for gutter prop in the layered collage.
Manually tested, converting existing collage to layered collage.
=> Fix invalid value passed to layered collage

src/blocks/gallery-collage/edit.js
Remove the shadow class from the collage image placeholders.
=> Remove the shadow from collage gallery placeholders

src/blocks/gallery-offset/deprecated.js, src/blocks/gallery-offset/index.js, src/components/gutter-control/gutter-control.js
Try reducing the spacing between the example images on the Offset Gallery block.
This PR also changes the new default gutter for the Offset Gallery block to be 'small' instead of 'medium'. This change requires deprecation.
JavaScript. Changes require new block deprecation.
=> Try using 'small' default gutter value for Offset block example

src/blocks/accordion/accordion-item/styles/style.scss
Styles for the accordion block were being overridden when background colors were set, fixed in style.scss. In reference to this issue: https://github.com/godaddy-wordpress/coblocks/issues/1902
Minor - scss update to increase scope
Locally, in editor
=> Fix excess padding on Accordion block

src/blocks/gallery-collage/edit.js, src/blocks/gallery-collage/styles/style.scss
When `image-2` is selected in the layered gallery, the image now pops to the front so the upload/replace/x buttons are all visible to the user.
=> Bring the farthest back image to the front when it's selected in the layered gallery block

docs/dev/release.md
1. Moved the release.md file to the devs folder, since those procedures are most relevant for those with dev access. 
2. Added a new section for preparing the milestone in GitHub and the processes associated with that, since it is performed on each release.
- Markdown doc update
=> Improve release documentation.

src/blocks/services/service/edit.js
Adds the href attribute to the image within the services block
Fixes #1901 
Visually
=> Fix image link controls for Services block

src/blocks/accordion/accordion-item/styles/style.scss
Changes the css selector for accordion-item title to no longer include `.has-background`.
Resolves #1918.
CSS style change of scope. Reverts to the version in CoBlocks 2.11.1
Locally in editor
=> Fix background color of Accordion Items taking precedence over user selection

readme.txt
Youtube account which owned the display video on the readme.txt was closed and the video no longer worked. This PR removes the video from the readme.txt file.
Fixes #1921 
Bug Fix
visually
=> Issue 1921 - remove youtube video from readme.txt

src/blocks/accordion/accordion-item/edit.js, src/blocks/accordion/accordion-item/styles/editor.scss, src/blocks/accordion/styles/style.scss
Add caret icons to display open state of accordion items
Fixes #1914 
https://user-images.githubusercontent.com/18115694/121074131-6ef2cc80-c7a1-11eb-98f8-50bf11aa82ab.mov
Adds Icon tied to open state within the AccordionItem component
Visually
https://user-images.githubusercontent.com/18115694/121074131-6ef2cc80-c7a1-11eb-98f8-50bf11aa82ab.mov
=> Issue 1914 - add caret icons to accordion items within editor

src/blocks/post-carousel/edit.js, src/blocks/posts/edit.js
Remove the `isLarge` attribute from the post and post carousel blocks. Apparently [this was removed](https://github.com/WordPress/gutenberg/issues/16541#issuecomment-645336060) from core and was throwing a console warning in the editor.
Non-Breaking change.
Added a post and post carousel block to the page to make sure there were no regressions.
=> Remove the isLarge button attribute from post and post carousel

package.json, src/blocks/accordion/styles/editor.scss, yarn.lock
Changing the version of `trim-newlines` to 3.0.1 to fix the css job on CircleCI. Should be merged (if possible) before the next coblocks release.
Version change, yarn && yarn build.
Locally, circleci
=> Bump trim-newlines down to 3.0.1 

class-coblocks.php, package.json, readme.txt
Update `"tested_up_to"` in package.json from 5.7 to 5.8, then run grunt version.
Version compatibility fields in class-coblocks.php, readme.txt and package.json
Locally
=> Update all compatibility versions for WP 5.8

src/blocks/share/edit.js, src/blocks/share/index.php, src/blocks/share/styles/style.scss, src/blocks/share/test/share.cypress.js, src/blocks/social-profiles/edit.js, src/blocks/social-profiles/index.php, src/blocks/social-profiles/styles/editor.scss, src/blocks/social-profiles/test/social-profiles.cypress.js
This PR applies the block size classnames that are set within the editor on the resulting front end class names.
Fixes #1926 
Bug Fix
=> Fix button size controls on Share and Social Profiles blocks

src/blocks/share/index.php, src/blocks/social-profiles/index.php
Assertions made on the `className` attribute result in undefined index errors. We can prevent this by first checking `isset` on the object property.
=> Fix Social block undefined index

src/blocks/post-carousel/edit.js, src/blocks/posts/edit.js
This PR will filter the current post from the posts that are passed into the Posts block  . 
Bug Fix
visually
=> filter posts by removing the current post from the list

src/blocks/gist/edit.js
Refactor the Gist Edit component from React class to React hooks. It was needed because `withState` is now deprecated, so we need to use `useState`
The unit and Cypress tests for that component still pass.
=> Convert Gist Edit component to React hooks

includes/class-coblocks-block-assets.php, src/blocks/author/inspector.js, src/blocks/click-to-tweet/inspector.js, src/blocks/gallery-stacked/inspector.js, src/blocks/highlight/controls.js, src/blocks/highlight/edit.js, src/blocks/highlight/inspector.js, src/blocks/highlight/test/highlight.cypress.js, src/components/fontsize-picker/index.js, src/utils/helper.js
Closes #1945. [Due to a bug in 5.8 release](https://github.com/WordPress/gutenberg/issues/33653), the `withFontSizes` HOC is conflicting with the `FontSizePicker` component. Changes here fix logic used with the `FontSizePicker` to allow use in 5.7.2 as well as 5.8.
New CoBlocks shared component where we utilize `FontSizePicker` with improved logic.
This was tested manually by switching versions 5.7.2 and 5.8.
=> Fix Font Size controls in WordPress 5.8

src/extensions/colors/settings-modal-control.js
Fixes #1935 
When settings the editor settings, keep the default structure of the __experimentalFeatures object.
Bux fix
visually
=> Keep default experimental features object structure within editor settings

includes/class-coblocks-block-assets.php
In FSE when a block isn't contained in the post content, the assets do not load. This PR queries the `` psot type and determines if they contain any CoBlocks blocks in their content. If it does, the assets are loaded.
Related issue #1911 
New functionality (non-breaking change)
Tested against #1911 to ensure the assets load when a CoBlocks block is added to the footer of a page.
=> Load CoBlocks assets when wp_template_part post type contains a CoBlocks block

src/extensions/animation/index.js
Fixes #1941 
If an animation (coblocks extension) is added to a block, and the coblocks plugin is deactivated, block validation will fail and block recovery will remove the animation attribute, however the classname `coblocks-animate` will be kept. If coblocks is re-activated , as the animation is undefined and the className is set, an opacity of 0 is set to the block. This PR attempts to add a block filter to remove this class name in the event of an undefined animation attribute.
Bug fix
visually
=> Fix invisble block states enabled by animation class

src/blocks/gist/controls.js, src/blocks/gist/edit.js, src/blocks/gist/gist.js, src/blocks/gist/inspector.js, src/blocks/gist/test/gist.cypress.js
Fixes #1331 
When there was a Gist URL for a specific file in it 
(ex : https://gist.github.com/olafleur/260e1f1c09284e6b257348b0be706a6a#file-hello_world-html )
which had a capital letter in it, it didn't work.
Additional changes allow users to pass in URI varieties with a forward-slash suffix that previously would fail.
- https://gist.github.com/AnthonyLedesma/7d0352e8bc50a8a009c2b930f23d110d/#file-gistblocktest-text
- https://gist.github.com/AnthonyLedesma/7d0352e8bc50a8a009c2b930f23d110d/
Bug fix
The Gist tests still pass.
=> ISBAT render a Gist with a file that has a capitalized letter in the name

src/blocks/alert/deprecated.js, src/blocks/alert/save.js, src/blocks/alert/test/__snapshots__/save.spec.js.snap
Add `aria-label` for the Alert block, specifying to screen readers what's the block purpose
See #1951 #1927
=> Improve accessibility for Alert block - Issue #1951

.circleci/config.yml, cypress.json
A valid but unexpected bash syntax was causing the reversed output within an if statement. This was preventing lint tests from running.
Fix bash syntax located in the config.yml file.
Tested within the CI pipeline.
=> Fix `run-all-tests` feature to also run php and css linting

src/extensions/colors/settings-modal-control.js
closes #1978
Due to some oversights in type-checking, there are conditions that allow the saved color palette to be an empty array. Due to improper type-checking, we failed to discard the empty array for the theme-defined values.
Changes here will fix any issues where users have empty palettes by freshly fetching those settings on page load.
JavaScript
=> Properly save and parse local storage Color Palette values

.circleci/config.yml, src/blocks/services/edit.js, src/blocks/services/service/edit.js, src/blocks/services/service/inspector.js
This block already implements a functional component architecture. This PR is to remove the Fragment components from within the Services block and related components.
=> refactor services block to use react hooks

src/components/block-gallery/shared/transforms.js
Adds optional chaining operator to image array in gallery transform to prevent editor crash when transforming from [new core gallery block refactor](https://github.com/WordPress/gutenberg/pull/25940) which does not have an image attribute by default.
Before:
After:
Addition of optional chaining operator to for the core gallery image attribute array.
Tested on local dev install with build of Gutenberg Gallery refactor branch also installed.
=> Fix issue with transforming to refactored core gallery

src/blocks/services/service/edit.js
Add a 'Replace' button to the service image block.
=> Add a 'replace' button to the service image

src/blocks/post-carousel/edit.js, src/blocks/post-carousel/inspector.js, src/blocks/posts/edit.js, src/blocks/posts/inspector.js
This PR handles the use case of a custom category entered into the feed settings for both the Posts and Post Carousel block. If an unrecognized, custom category is entered then no action is taken and no block error will be thrown.
Fixes #1974 
Bug fix
=> WPEX-1459 - do not throw error on custom entered category for post carousel and posts block

src/blocks/hero/edit.js, src/blocks/shape-divider/edit.js
A performance issue is that the `getBlock` and `getBlocks` selectors are slow. [This is identified in this PR on the Gutenberg repo](https://github.com/WordPress/gutenberg/pull/33974). The language used makes me think that ideally, we should try to find a way to avoid using these selectors all together. Because we reference the props pulled from `getBlock(s)` selectors in a few blocks it makes removal of this logic complicated.
Another change identified in this PR is simply a different way of accessing the `getBlock(s)` APIs essentially directly as opposed to within a callback.
Both the Hero block and the Shape-Divider blocks have been refactored to remove the use of `getBlock(s)` selectors. All other uses of `getBlock(s)` are needed to reference the `innerBlocks` prop. 
I wonder if this …
=> Try using getBlocks selectors directly to check performance gain

src/blocks/gif/styles/editor.scss
Improve Gif block previews, mainly using 100% container width and keeping aspect ratio
Visual changes
=> Improve Gif block previews

src/blocks/logos/logos.js, src/blocks/logos/styles/editor.scss
Logos block resizable handles can overlap the image when the screen is zoomed in. We do a padding calculation on the resize container in order to allow proper spacing between logos block images and we attempt to compensate for that padding by setting explicit `right` CSS. 
Unfortunately, that solution was not complete due to the edge case of browser zoom. In order to compensate for a slight variation on spacing with various zoom settings, this PR alters the resize handles to be slightly apart from the image edge. This allows for a more consistent UX.
I also modify the way that we utilize the ResizableBox to match core standards with `forwardRef`.
**Old**
**New**
JS. CSS.
Tested manually at various zoom settings.
=> Fix the resizable block handles for the Logos and Badges block

src/blocks/gallery-stacked/styles/editor.scss, src/components/responsive-tabs-control/index.js
Setting the gutter to "0" should remove any spacing between images. This is not reflected when editing the page but is rendered properly to site visitors.
Additionally, when a gutter is applied (greater than zero), a setting to set the rounded corner size is available. The rounded corner settings should be reset or removed if the gutter is set to zero.
Manually
=> Remove stacked gallery margin when gutter is set to 0

src/blocks/alert/edit.js
This PR fixes the `useEffect` logic so that the user may properly apply custom colors to the Alert block.
[There is an ancillary issue that should be closed in concert](https://github.com/godaddy-wordpress/go/pull/696) in order to properly resolve this issue.
The linked issue on the Go repo prevents colors from properly applying on the front-end.
JavaScript changes.
=> Fix custom colors on Alert block

src/js/coblocks-google-recaptcha.js
Another task in #1365 
Refactor
Manually, by making sure that the Recaptcha script is still called when using a form.
=> Remove jQuery from Recaptcha script

.circleci/config.yml
I just added a condition to not lint the JS files when there is no files changed because when doing PRs like #2134 where there is no JS file modified, it will lint everything (and fail because of the 5k+ linting errors due to ordering).
=> Don't lint the files if there is no files found

.circleci/config.yml
- Run all the Cypress tests always
- Use more parallelization so that it does not slow the build
=> Run all Cypress tests but with more parallelization to make it faster

.dev/bin/comment-on-pr.sh
There is a small bug where the bot overwrites the last comment left. This PR adds a check for latest comment by the godaddy WordPress bot, that does not contain "Code Coverage" in it. The Cypress bot currently uses the same github key to leave comments.
If you push multiple times on your first commit, there may be multiple comments because the github API hasn't updated to reflect the last comment by the bot. This usually takes a few minutes. Once one comment is left, the same comment should be updated for each push.
=> Filter comments to return godaddy bot comments only

src/js/coblocks-accordion-polyfill.js, src/js/coblocks-checkbox-required.js
It seems to have been removed as a warning, at least for pure JS files.
=> @wordpress/no-global-event-listener disable is not needed anymore

.circleci/config.yml
Fix the `aggregate` job, by not running the job on `master` or `develop` branches. 
https://app.circleci.com/pipelines/github/godaddy-wordpress/coblocks/7772/workflows/33689bef-f795-4944-aff8-15308a05462f/jobs/35982
=> Add a check in the aggregate_perf_test_results build

.circleci/config.yml, .dev/bin/comment-on-pr.sh, package.json, yarn.lock
The build was failing for two reasons : 
1. When commenting for the first time on the PR, the exit code was 1 (error) instead of 0
2. The perf tests were failing because node-fetch was updated to version 3 which is ESM-only (but we are not calling the dependency to be able to use it that way yet).
=> Fix build failing

.dev/tests/cypress/helpers.js, src/extensions/advanced-controls/index.js
This is essentially a PR to remove dead code : 
- In the first if, we remove the condition that was used before WP 5.4 (we now support > 5.5 and test only > 5.7)
- In the getBlockSlug it is only a simplification of the code
- After that, it's just removing unused functions
- The last line modified in index.js it's using `select( 'core/block-editor' )` instead of `select( 'core/editor' )`, which is deprecated (there was a warning message about it).
=> Cleanup helpers.js + remove a warning

.circleci/config.yml
For the moment, these tests are broken and don't provide value, while breaking our build.
=> Disable perf tests temporarily

src/components/media-filter-control/test/media-filter-control.cypress.js
Fix tests that were failing in WP 5.9 beta 2 because of the changes in the way the Gallery is working.
By running Cypress tests on WP 5.9 beta 2
=> Fix Media Filter Controls Cypress tests in WP 5.9

includes/class-coblocks-form.php
Resolves #1969 and #2148
Remove the "From" header when the form block sends an email address. This is to help mitigate the issue of email providers marking the emails as spam. In this solution we are leaving all default `wp_mail()` headers, except we are setting a custom `Reply-To` header.
=> Remove the From header in the form block

.dev/tests/jest/jest.config.js
Disable coverage report for old masonry v1 block.
=> Remove coverage from masonry block v1

.circleci/config.yml, .dev/tests/cypress/helpers.js, src/blocks/icon/test/icon.cypress.js, src/blocks/posts/test/posts.cypress.js, yarn.lock
Fix tests that started failing after #2206 was merged. There were errors because sometimes the controls were not loaded properly when Cypress was searching for them.
=> Fix Cypress tests that were sometimes failing because of lazy loading

src/components/typography-controls/index.js
This PR fixes an issue where in some cases the global variable `typographyControlsEnabled` was being found as undefined which would cause the Typography controls to render in some cases but not in others. By virtue of being able to access the editor, users should be able to edit typography controls (as long as this variable is set to true).
https://user-images.githubusercontent.com/18115694/146565874-6a977b00-ae6e-4604-9235-eb52e410ba8d.mov
Fixes #2103 
Bug fix
visually, testing with different user roles
=> Check global CoBlocks data to determine if typography controls are enabled

src/blocks/gist/index.js, src/blocks/gist/index.php
Gist embed seemed to have an issue embedding when any files were specified within the Gist URI. Similar to previous Gist solutions we need a custom solution to load files that include uppercase.
There was another issue where `isActive` was being evaluated as true regardless of `providerNameSlug`. This means that if a user were to select the `core/embed` block from the inserter, that the Gist variation would show regardless. Changes here allow for Gist variation to show when inserting `coblocks/gist`.
New PHP logic and minor change to JS.
Tested manually in the browser using test Gists.
https://gist.github.com/AnthonyLedesma/33ad1a8cd86da3b6bddbdefa432cb51d
https://gist.github.com/AnthonyLedesma/7d0352e8bc50a8a009c2b930f23d110d
=> Fix Gist file embed

src/blocks/events/styles/editor.scss, src/blocks/faq/faq-item/styles/editor.scss, src/blocks/faq/styles/editor.scss, src/blocks/faq/test/faq.cypress.js, src/blocks/pricing-table/pricing-table-item/styles/editor.scss, yarn.lock
Refactor customer Appender CSS to be compatible with 5.9. Backport 5.9 style into our own for 5.8.
Event block
Pricing block
FAQ block
=> Change CSS of customer appender for 5.9 compat

package.json, yarn.lock
The `postcss` resolution broke the linting, so at least, I removed the security vulnerability from our stylelint-config (this is why I am updating it here).
But it means that we will have to find another way to resolve the postcss security vulnerability which is present in `@wordpress/scripts`.
We can expect the Gutenberg team to fix `@wordpress/scripts` eventually, I guess ;)
=> Update @godaddy-wordpress/stylelint-config and revert postcss resolution

.circleci/config.yml
Added an update to the list of packages so that PHP installs properly when building `canary` .
For the moment, this is the situation : 
After this PR, the step is running properly and PHP is installed.
=> Add a sudo apt update so that PHP installs properly in canary

.dev/performance/index.js, .dev/performance/utils.js
The perf tests sometimes fail for a mysterious reason. Instead of making the build pipeline fail, we take what data has been calculated and show it on the PR (when it fails, it is always the second time it calculates the value, so there are already some calculated values).
So, basically, we allow the execution of the performance tests to fail on the pipeline, because it does not represent a failure of our product.
=> Don't make the build pipeline fail if the perf tests fail

includes/class-coblocks-block-assets.php
Fixes #2233 
Not sure if this is the proper way to fix it, but it seems to solve the 404 error on `coblocks-extensions.css` (which should be `style-coblocks-extensions.css`).
=> Fix path to coblocks extensions CSS

package.json, yarn.lock
These upgrades are to prevent security vulnerabilites.
=> Update node-fetch and nanoid

src/blocks/form/styles/editor.scss
Form inputs that are disabled were applying the default "disabled" styles when viewed inside the editor making them hard to see.
Although we want them to not be actionable, we want them to look like they would on the front-end. Resetting the styles on the editor side resovles this.
=> Remove disabled styles inside editor.

src/extensions/lightbox-controls/index.js, src/js/coblocks-lightbox.js
New selector in the script and logic to check the innerBlocks. This has changed since the old Gallery block had used attributes.images as opposed to innerBlocks. 
JavaScript
Tested Manually in 5.9-RC4
=> Fix Lightbox for Gallery block.

cypress.json, src/blocks/posts/test/posts.cypress.js, src/blocks/row/column/test/column.cypress.js, src/blocks/row/test/row.cypress.js
The condition for if there is a variation picker or not was causing problem because the expected class was not loaded enough quickly to take the right branch of the if.
Now we only test on 5.8 and 5.9, and they both have the variation picker, so this if is not necessary anymore and it resolve the problem with the tests failing in WP 5.9
I also took the opportunity to solidify flaky tests.
Tests fix
Cypress tests run on WP 5.9
=> Fix Row, Column and Posts blocks tests for WP 5.9

.dev/tests/phpunit/includes/test-coblocks-block-assets.php, includes/class-coblocks-block-assets.php, includes/class-coblocks-settings.php
Move from init to enqueue_block_editor_assets to enqueue our scripts.
=> Change editor asset from init to enqueue_block_editor_assets

src/blocks/social-profiles/test/social-profiles.cypress.js, src/extensions/lightbox-controls/test/lightbox-controls.cypress.js, src/extensions/media-text-styles/test/media-text-styles.cypress.js
- Removed a colors test in Social Profiles, because the colors were Go-specific
- Fixed Lightbox tests (align wide is the default, so the class is not there when align is wide)
- Fixed a Media Text styles test
Tests fixes
=> Fix some tests in Twenty Twenty-Two

src/js/coblocks-lightbox.js
The Lightbox uses event listeners to navigate. Changes here remove the listener when the lightbox is closed.
JavaScript. Refactor from using deprecated standard `.keyCode` to using `.code` property.
=> Fix Lightbox being opened with improper keypress

src/components/swiper/style.scss
- Fix `.icon` scoping
- Fix missing background color on arrows
Visual
Visually tested
=> Fix .icon scoping from Swiper component

readme.txt
Simple formatting change here. This should allow the CoBlocks changelog to reside under the development section of the WP.org page.
=> Update readme formatting to fix Changelog

.circleci/config.yml, src/blocks/icon/deprecated/svgsv1.js, src/blocks/icon/svgs.js
Fix custom icons crashing the Icons block.
See: https://github.com/godaddy-wordpress/coblocks/issues/2251
Bug fix
Manually tested. @olafleur we should find a way to cover custom icons in our tests :)
=> Fix custom icons not loading

src/blocks/faq/styles/style.scss
Safari adds a marker that conflicts visually with the default marker we add for the FAQ items list. This removes it.
Before:
After:
=> Add styling to hide Safari default marker on FAQ items

.circleci/config.yml, .gitignore
Enhance the CircleCI config to build and test E2E against the final build.
This change makes it so that we no longer activate the CoBlocks plugin dev version and instead run `coblocks-testing` which is a clone of the final build produced by `grunt build`.
CI changes. Minimal Bash and WP-CLI.
In CI.
=> Try to run E2E on final build

includes/class-coblocks-block-assets.php
A user mentioned getting a flicker of a blank page on the admin dashboard here : https://wordpress.org/support/topic/undefined-array-errors-after-updating-to-2-21-6/
It seems that these were notices before, but are now warnings in PHP 8.
=> Add isset to $_GET['post']

.dev/tests/cypress/helpers.js, src/blocks/dynamic-separator/test/dynamic-separator.cypress.js, src/extensions/colors/test/settings-modal-control.cypress.js
This PR refactors the `setColorSetting` helper function to be compatible with the updated color UX.
Refactor/Bug fix
=> WPEX-1829 refactor color settings helper function to be compatible with 5.9.1

includes/class-coblocks-block-assets.php
Removes unnecessary slash within the script path for wp_enqueue_script function for the tiny swiper package
Bug fix
=> Fix superfluous slash with enqueued scripts

src/blocks/events/event-item/example.js, src/blocks/events/event-item/index.js, src/blocks/events/index.js
This PR adds a preview to the event and event-item blocks 
Bug fix / enhancement
=> WPEX-1661 - add preview for event and event-item

src/blocks/features/feature/edit.js, src/blocks/opentable/test/opentable.cypress.js
This PR allows the Spacer block to be used within the Feature block.
Fixes #2032
new feature / enhancement
Visually
Allow for Spacer block to be used within the Feature block.
=> WPEX-1663 allow spacer block as an inner block of feature block

.circleci/config.yml
The results of this test have been to reduce total cache consumption yet to persist a necessary minimal cache to each respective job.
We do have a minimal increase in build time of about ~2 minutes as caches are not quite as robust. In the face of around ~25 minutes for a run of a full test suite, this should be a satisfactory tradeoff of reduced stored cache for a small increase in computing.
Ci config changes.
Tested in CI.
Not a clear AC. The reason for this PR is that we have a stored cache in Circle Ci that is seemingly ever-increasing in size and cost. This is an effort to reduce stored cache and trade for additional computing.
=> Try removing .lock caches from CI config

src/blocks/form/fields/field-label.js, src/blocks/form/variations.js
Tweak the styles of the form block in the editor.
Manually inspected the spacing in the editor/frontend.
- The spacing between email/phone fields and services fields is inconsistent. It should be inline with name and email fields.
- The asterix (`*`) in the terms and condition section should be next to privacy policy. currently it is after AND.
- There should be a period after privacy policy.
- The fonts particularly in the services section and text field beneath the T&C section (I have read and agree to the terms and conditions and privacy policy.) don't match with Go theme fonts.
=> Tweak form block styles

.circleci/config.yml
Presently in CI the cache is not being updated because of the nature of read-only cache storage in Circle CI. This enhancement will ensure that any missing or superfluous dependencies are updated on the fly as part of the restore cache job.
This change requires having Node and Yarn pre-installed in the container before installation.
Minor Ci changes.
Tested in CI.
This should ensure that `yarn install` is run against the present package.json regardless of cache status.
=> enhance restore cache to also install missing deps

src/blocks/gallery-carousel/styles/style.scss
The issue is with the Offset block rendering issue and maybe old Masonry galleries too.
Before
After
SCSS change.
Should resolve display issue from style bleed.
=> Resolve issue with style bleed

src/utils/helper.js
I am pretty sure this will fix the issue with the blocks list on WordPress.org. I based the fix based on the [plugin details page for another popular plugin.](https://wordpress.org/plugins/ultimate-addons-for-gutenberg/) I was not able to find any docs elsewhere to explain the requirements. Based on the aforementioned plugin details we know that three of the blocks are setup to display as expected.
[What the three blocks have in common are strings processed by the translation function. ](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/blob/df0108b4e1d7116505e2d521baecbe424d0f0c80/src/blocks/advanced-heading/block.js#L16)
[All other blocks of this plugin are setup to use strings that are not translated.](https://github.com/brainstormforce/ultimate-addons-for-gutenberg/blob/ …
=> try using translation function with registerBlockType

src/blocks/accordion/accordion-item/deprecated.js, src/blocks/accordion/accordion-item/save.js, src/blocks/accordion/accordion-item/test/__snapshots__/save.spec.js.snap
This PR resolves an issue for keyboard users where the opened accordion would focus on the accordion body in the front end. As the area is not editable, it is unecessary.
Fixes #2304 
Bug fix
manually
Should not be able to tab focus the accordion body on the front end
=> issue-2304 remove tab index from accordion item content div on front end

src/blocks/accordion/accordion-item/block.json, src/blocks/accordion/block.json, src/blocks/alert/block.json, src/blocks/counter/block.json, src/utils/helper.js
This is take-two at attempting to fix the WordPress.org plugin details page for CoBlocks.
The #Meta team in WordPress slack has identified that this block.json property is one that is required for block registration. Going to give a shot at specifying both paths and slugs to check if there is a difference.
Removing a [previous modification here](https://github.com/godaddy-wordpress/coblocks/pull/2332) that adds a translation function.
This will need to be deployed in a versioned release in order to test this proposed fix.
The AC should be resolving the issue with improper block names on the plugin details page. Unfortunately, we will need to test this by releasing a version of CoBlocks.
=> Try new editorScript property in block.json

src/blocks/gist/index.php
Any URL that was used with the gist block that included a hyphen would error out because the regex to determine the valid link within the Gist block was not considering hyphens. This PR fixes that regex
bug fix
manually
Should be able to to include a gist URL that has a hyphen with the Gist block
=> WPEX-1921 - change gist block regex to account for hyphens in the link

src/blocks/gallery-carousel/styles/style.scss
Originally reported in https://wordpress.org/support/topic/carousel-image-caption-not-loading/ the carousel captions were not displaying properly. This PR fixes the placement of the captions so they show up at the bottom of each image in the carousel.
During my testing I noticed that the carousel also had a 50% padding beneath it, which was throwing off the navigation buttons. Removing this padding go the carousel displaying properly again with the captions.
Manually tested with a few different carousel settings.
Captions display properly beneath each image in the carousel.
=> Tweak carousel bottom padding and fix captions

src/blocks/opentable/block.json
The correct capitalization for this restaurant reservation service is OpenTable.
=> Fix OpenTable typo

includes/class-block-patterns.php, includes/class-coblocks-block-assets.php
This PR resolves an issue within the WP admin Widget editor which displays an error message in the admin header. The issue was caused by wp-editor scripts being loaded and conflicting with the widget editor scripts.
Fixes #2291 
Bug fix
manually
Error message should not be shown on the widget editor screen
=> WPEX-1927 remove WP error showing within the Widget editor 

.dev/tests/phpunit/src/blocks/gist/test-index.php, includes/class-coblocks-block-assets.php, src/blocks/gist/index.php, src/js/coblocks-gist.js, webpack.config.js
This PR fixes an issue with the Gist block which (within the editor) any links within the Gist iframe will open within the iframe itself rather than the window. These changes disable the links within the editor and include a script on the front end to re-enable the links. 
Fixes #2326 
Bug fix
manually
Links should not be clickable/openable within the editor.
=> WPEX-1922 - disable links in editor, enable gist links in front end

src/blocks/events/event-item/styles/style.scss, src/blocks/events/index.php, src/blocks/events/styles/editor.scss, src/js/coblocks-events.js
Previously the events block did not support multi day events. Additionally, timed events which were not "all day" would show incorrect times for the events. 
Fixes #2302 
Fixes #2301 
Bug fix
manually
Multi day events should be supported, correct times should be shown
=> WPEX-1926 - handle multi day events in the events block

src/blocks/alert/test/alert.cypress.js, src/blocks/author/test/author.cypress.js, src/blocks/highlight/test/highlight.cypress.js, src/extensions/animation/test/settings-modal-control.cypress.js, src/extensions/typography/test/settings-modal-control.cypress.js
This is to make some tests pass with WP 6.0 RC1 : 
- Alert
- Author
- Typography extension
- Animation extension
- Highlight
=> Fix some Cypress tests in WP 6.0 RC1

src/blocks/click-to-tweet/test/click-to-tweet.cypress.js, src/blocks/dynamic-separator/test/dynamic-separator.cypress.js, src/blocks/logos/test/logos.cypress.js, src/extensions/colors/test/settings-modal-control.cypress.js
This time, I am fixing tests for these blocks/extensions : 
- Click to Tweet
- Dynamic Separator
- Logos
- Colors extension (settings modal)
=> Fix more Cypress tests for WP 6.0 RC1

src/blocks/accordion/accordion-item/styles/style.scss
adjusts the outline color of the summary tag within the Accordion block for better visibility to keyboard users.
fixes #2303 
Before:
After:
bug fix / css change
visually
=> WPEX-1925 - adjust focus color on accordion block

CONTRIBUTORS.md, src/blocks/gallery-carousel/test/transforms.spec.js, src/blocks/gallery-collage/test/transforms.spec.js, src/blocks/gallery-masonry/test/transforms.spec.js, src/blocks/gallery-offset/test/transforms.spec.js, src/blocks/gallery-stacked/test/transforms.spec.js
This change reintroduces tests that were skipped due to breaking-changes in data structuring caused by dependency updates in #2379. Tests are no longer skipped and the proper fields are validated in the transformed block. Additionally, gallery transform test files now fully pass the linter `yarn lint:js`.
- Reformatting to pass linter (non-breaking).
- Refactoring of skipped unit tests.
Run `npm test:js`: Passes all tests, including the tests that this PR revises.
- Reintroduced tests pass linter.
- Reintroduced tests properly validate transformations from CoBlocks gallery blocks to Core blocks.
=> Issue-2115: Reintroduce transformation unit tests for CoBlocks Galleries to Core 

src/blocks/gist/index.php
=> Check for WP_Error in wp_remote_get; fixes #2386

.circleci/config.yml
There seems to be a bug that sometimes make the Firefox tests fail when it is headless. So, adding the `--headed` flag to make these pass. There does not seem to be a noticeable time difference.
Also making the verification before the run, which is a little bit quicker than doing it at the `cypress run` call.
=> Run Cypress tests headed

src/components/common/styles/edit-post.scss
Resolves #2421 
Fix the incorrect button order in the editor.
Bug fix (non-breaking change which fixes an issue) 
Tested this with and without Gutenberg active.
=> Fix button order in editor header

.circleci/config.yml
=> Update Go from 1.16 to 1.19 for deploy and canary

.circleci/config.yml
In Go 1.18, the command changed from `go get` to `go install` to install packages.
=> Change command from go get to go install

.dev/tests/cypress/helpers.js
The old version was looking for the first class only, the correct looks for the presence of the class in the list of classes. It is better, because we cannot guarantee that the `branch-6-1` (for example) is the first class named.
=> Fix conditional to determine if we are using a WP version >= WP 6.1 in the tests

class-coblocks.php, package.json, readme.txt
We're nearing the end of our modifications and tests for WP 6.1, so our next release will be tagged as supporting WP 6.1
=> Bump 'Tested up to' to WP 6.1

.dev/tests/cypress/helpers.js, .dev/tests/cypress/support/commands.js
A few tweaks (with a lot of trial and error ;) ) to make the Cypress tests pass with WP 6.1 by fixing the last problem we have for the moment : the welcome guide showing up unexpected and making our tests fail :)
=> Make sure that the Welcome Guide does not show in the Cypress tests

includes/class-coblocks-site-design.php, src/extensions/site-design/component.js
This PR is a measure to resolve issues with cascading styles. 
Companion PR on Go theme for style consistency.
https://github.com/godaddy-wordpress/go/pull/814
The summary of the overall issue is this: 
Styles on-load are persisted by PHP into the header element where we generate a custom style tag. After a user interacts with the Site Design component we previously modified this custom style element which resides in the header. An issue with this approach is that other styles used for the Site Design component live in the body and thus have higher specificity.
To fix this issue we use the same `useEffect` call that modified our custom style element to relocate the element into the proper hierarchal order thus allowing styles to cascade as expected. 
JavaScript. Also included with this …
=> Relocate styles used for Site Design controls.

.circleci/config.yml
With the release of WP 6.1 came a new default theme : Twenty Twenty-Three
https://wordpress.org/themes/twentytwentythree/
We always want to make sure that CoBlocks is compatible with the current default theme, that is why we're switching from TT2 to TT3.
=> Switch build pipeline from Twenty Twenty-Two theme to Twenty Twenty-Three

includes/class-coblocks-site-design.php, src/extensions/site-design/component.js
Reverts godaddy-wordpress/coblocks#2442
This caused an issue in prod where the chosen selector may not be present. Reverting as a temp fix.
=> Hotfix Site Design controls selector

.dev/tests/cypress/helpers.js, .dev/tests/cypress/support/commands.js, package.json, src/extensions/layout-selector/store.js, src/extensions/layout-selector/test/layout-selector.cypress.js, src/extensions/site-content/post-type-panel.js, yarn.lock
The Template Selector should show only when it is a new page or when the current page is empty.
https://user-images.githubusercontent.com/85255688/202632436-18117d78-a78f-477f-b675-d824d9f0ccd7.mp4
Bug fix
Cypress test and manually
=> Fix how/when the Template Selector shows

.github/workflows/validation-coding-standards.yml
Introduce `validation-coding-standards.yml` workflow file for linting PHP, CSS and JS files.
Add github actions workflow to lint PHP, CSS and JS files.
=> Introduce validation-coding-standards.yml

.dev/tests/phpunit/includes/test-coblocks-form.php, includes/class-coblocks-form.php, src/blocks/form/fields/submit-button/block.json, src/blocks/form/test/form.cypress.js, src/extensions/button-styles/styles/style.scss
Resolves #2218 
The form block submit button class attribute name changed from `` to ``, but was not updated in the .php file that renders the button, so the form button styles did not reflect selected style on the front of site. The button would always show as the default 'filled' style, and not have the proper classes assigned to it.
Master:
PR:
Updated `$atts['submitButtonClasses']` to `$atts['className']` when the submit button is rendered.
Originally reported in #2218
=> Update form button class attribute name

.circleci/config.yml
This is needed to use the GH_AUTH_TOKEN var in the CircleCI context.
=> Add CircleCI context for Canary and Deploy

src/blocks/form/fields/submit-button/edit.js, src/extensions/button-styles/styles/style.scss
Closes #2460
The original approach using styles did not work because there are other situations where the style would bleed. Change here fixes the bleed reported in #2460 and keeps the original bug resolved by ensuring the form block submit button does not apply default colors to its color component but instead inherits from the theme.
Remove style changes. Allow form block submit button to inherit colors from stylesheets.
Tested manually with TwentyTwentyThree and with Go theme.
This should resolve the color bleed reported in the linked issue. It should also continue to resolve the originally attempted fix. Original bug behavior can be seen here: https://github.com/godaddy-wordpress/coblocks/pull/2449
=> fix form button colors and fix color bleed

includes/class-coblocks-generated-styles.php
Originally reported in https://wordpress.org/support/topic/small-mistake-in-class-coblocks-generated-styles-php/
In WordPress 6.1 and PHP 8.1, there is a PHP warning when a null value is passed to `wp_add_inline_style`.
=> Add a null check in class-coblocks-generated-styles.php

.github/workflows/deploy-create-artifact.yml, .github/workflows/deploy-create-release.yml, .github/workflows/deploy-wordpress.yml, .github/workflows/test-e2e.yml, README.md
Due to [restrictions in Actions](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow), we moved the job of the action to the release workflow, while also adding a manual trigger for deploying a new version to wp.org as well.
=> Fix issues with deploying to wp.org from another workflow.

src/extensions/coblocks-labs/coblocks-labs-slot.js, src/extensions/coblocks-settings/coblocks-settings-slot.js
Fixes https://github.com/godaddy-wordpress/coblocks/issues/2474
Fix a regression where the `Editor settings` and `CoBlocks Labs` modals render empty for Gutenberg versions >=14.3.0. The breaking change was introduced in https://github.com/WordPress/gutenberg/pull/44642). 
1. Checkout this branch,
2. `wp-env start && yarn start`,
3. Make sure the Gutenberg plugin is not installed (the trunk version is active),
4. Go to a new post page,
5. Click the three dots menu in the top right corner,
6. Click `Editor settings` and `CoBlocks Labs` and make sure they render correctly,
| Editor settings modal | CoBlocks Labs modal |
| ------------- | ------------- |
| <img width="376" alt="Screenshot 2023-01-25 at 12 45 50" …
=>  Make Labs and Settings modals compatible with Gutenberg >=14.3.0

.dev/tests/phpunit/includes/admin/test-coblocks-action-links.php, .dev/tests/phpunit/includes/admin/test-coblocks-install.php, .dev/tests/phpunit/includes/block-migrate/test-coblocks-block-migration.php, .dev/tests/phpunit/includes/test-class-register-blocks.php, .dev/tests/phpunit/includes/test-coblocks-accordion-ie-support.php, .dev/tests/phpunit/includes/test-coblocks-block-assets.php, .dev/tests/phpunit/includes/test-coblocks-body-classes.php, .dev/tests/phpunit/includes/test-coblocks-font-loader.php, .dev/tests/phpunit/includes/test-coblocks-form.php, .dev/tests/phpunit/includes/test-coblocks-generated-styles.php, .dev/tests/phpunit/includes/test-coblocks-google-map-block.php, .dev/tests/phpunit/includes/test-coblocks-post-meta.php, .dev/tests/phpunit/src/blocks/alert/test-index.php, .dev/tests/phpunit/src/blocks/author/test-index.php, .dev/tests/phpunit/src/blocks/gist/test-index.php, .dev/tests/phpunit/src/blocks/post-carousel/test-index.php, .dev/tests/phpunit/src/blocks/posts/test-index.php, .dev/tests/phpunit/src/blocks/shape-divider/test-index.php, .dev/tests/phpunit/src/blocks/social/test-index.php, .dev/tests/phpunit/src/extensions/layout-selector/test-index.php, .dev/tests/phpunit/test-class-coblocks.php, .github/workflows/test-e2e.yml, .github/workflows/test-php.yml, includes/class-coblocks-form.php
Introduce jobs to test both unit testing and e2e while in a PHP 8.2 environment.
Changes only affect CICD testing. A few minimal changes to code for quality reasons.
Minimal and simple. Few syntax changes around string interpolation and adding types to test functions. 
Tested through CICD pipelines and manually.
All tests should pass with 8.2 active both PHPUnit and e2e testing.
=> Add jobs to test against 8.2 php

includes/class-coblocks-block-assets.php
Originally reported [here](https://wordpress.org/support/topic/the-method-has_masonry_v1_block-produces-a-fatal-error-on-php-8-0-22-and-above/).
Swapping out `get_the_content()` for `$post->post_content`.
Tested with PHP 7.4 and PHP 8.2.
Resolve erroneous fatal error when a v1 masonry block is on the page.
=> Swap get_the_content() for $post->post_content in has_masonry_v1_block()

includes/class-coblocks-site-design.php
As reported, when on PHP 8, and having the WooCommerce + WooCommerce Subscriptions plugins installed, the WooCommerce system status fatal errors and is inaccessible.
This was manually tested against PHP 7.4, and PHP 8. I tested with a few variations of plugins installed/activated and was consistently able to reproduce the issue with only PHP 8, CoBlocks, WooCommerce and WooCommerce Subscriptions.
Ensure that the WooCommerce system status is accessible and no fatal error exists.
=> Update CoBlocks_Site_Design:short_circuit_check to prevent fatal error on WooCommerce system status page on PHP8

includes/admin/class-coblocks-crop-settings.php, includes/class-coblocks-block-assets.php, includes/class-coblocks-form.php, includes/class-coblocks-site-design.php
PHP 8.1 deprecated `FILTER_SANITIZE_STRING`. As per the PHP docs, this can be replaced with `htmlspecialchars()`.
Manually testing the plugin to ensure functionality.
Remove all usage of `FILTER_SANITIZE_STRING`, where used.
=> Remove FILTER_SANITIZE_STRING

includes/block-migrate/class-coblocks-block-migration.php, includes/block-migrate/loader.php, includes/class-coblocks-block-assets.php
Add short-circuit for cases where the `get_current_screen` is undefined.
Minor logic changes to introduce short-circuit.
Should short-circuit if the function `get_current_screen` is not defined.
=> Add short-circuit to loader around screen logic

.dev/tests/a11y/pa11y.js, .eslintrc.js, src/blocks/accordion/accordion-item/edit.js, src/blocks/accordion/accordion-item/inspector.js, src/blocks/features/edit.js, src/blocks/features/feature/test/save.spec.js, src/blocks/features/test/save.spec.js, src/blocks/food-and-drinks/edit.js, src/blocks/form/fields/coblocks-option.js, src/blocks/gallery-carousel/edit.js, src/blocks/gallery-collage/edit.js, src/blocks/gallery-collage/inspector.js, src/blocks/gallery-collage/save.js, src/blocks/hero/test/save.spec.js, src/blocks/logos/edit.js, src/blocks/media-card/edit.js, src/blocks/opentable/opentable.js, src/blocks/row/test/save.spec.js, src/blocks/social-profiles/edit.js, src/extensions/block-patterns/modal.js, src/extensions/site-content/post-menu-actions.js, src/extensions/site-design/font-advanced.js
Remove some of the temporary linting rules by fixing the rules in the project.
=> Remove temporary linting rules

src/extensions/layout-selector/editor.scss, src/extensions/layout-selector/layout-selector-results.js
The block preview component has had major changes between 6.1.1 and 6.2 release of WP. One of the changes is related to the mechanism where the iframe is produced. We now need an extra wrapper for the preview container so we can apply margins and spacing.
**Bugged**
**Fixed**
=> Fix Layout Selector styles in WP 6.2.

.dev/tests/phpunit/includes/block-migrate/test-coblocks-block-migration.php, includes/block-migrate/class-coblocks-alert-migration.php, includes/block-migrate/class-coblocks-block-migration.php
Here is the originally reported issue: https://github.com/godaddy-wordpress/coblocks/pull/2470#issuecomment-1514766020
Some of the logic that parsed existing content did not accommodate some special characters.
Fixes here allow parsing and migration of special characters.
Test case added to ensure that special characters continue to migrate.
PHP logic changes around content preservation.
Tested manually with special chars. See image. 
Added PHPUnit test case for logic.
Should have test-case.
Should resolve issues where special characters to not migrate.
=> Add fix for migrating blocks with special characters

src/blocks/author/index.js, src/blocks/author/test/author.cypress.js
The `core/button` block once was stand-alone but now should be a child of `core/buttons`. Changes here properly wrap the button inside of buttons and applies it to the migration.
Added test logic to check for the presence of `core/buttons`.
**Before**
**After**
Simple JS changes to wrap an extra `core/buttons` in the markup.
Tested manually and also added new logic to e2e test.
Should have a test.
Should wrapper core/button with core/buttons block.
=> Add logic so that we use core/buttons instead of core/button

.dev/tests/jest/setup-globals.js, includes/class-coblocks-block-assets.php, includes/class-coblocks-site-design.php, src/extensions/site-design/data/actions.js, src/extensions/site-design/test/design-preview.spec.js
We performed sanitization on the request params and had a check for the Go theme but we did not have a nonce in place nor a user capabilities check on the `wp_ajax_site_design_update_design_style` request. This PR adds both a nonce check and user capabilities check.
=> Validate Site Design nonce and capabilities

src/blocks/form/index.js, yarn.lock
Update the form block `save` for WordPress 6.3 compatibility.
- Manually tested a migration from 6.2 with an existing form to 6.3 with the same form.
- Manually tested setting up a new form in both 6.2 and 6.3.
- Form should load in the editor without any validation errors, and show up on the front of site.
- No visible changes between WordPress 6.2 and 6.3.
=> Update form block save for WordPress 6.3

package.json, yarn.lock
The only change here is to update wp-env to ^8.1.1
Confirmed that PHP Unit tests 8.1 + 8.1 are passing.
Package updates for test failures.
Pipelines.
Should allow PHP Unit tests to pass for 8.1 + 8.2
=> Try to resolve php unit test issues - WP-ENV 8.1.1

.dev/tests/cypress/helpers.js
Update the Form block selector so that tests pass as expected.
Simple selector fix here for backward compatibility with old selectors.
Tested in E2E.
The tests for Form block should pass with 6.2.2 and with 6.3
=> Update the Form block test selector

changelog.txt, class-coblocks.php, readme.txt
=> Bump the `Requires at least` value for CoBlocks to 6.2

includes/class-coblocks-form.php
Fix the form block radio field not setting the field label properly. This effects the output in the email and what is displayed back to the user after form submission.
Ensure that radio fields have a label and no PHP warnings are displayed.
=> Fix the radio label not being set properly

includes/class-coblocks-form.php
Ensure that the first and last name field display properly. (`lastname, firstname`).
Manually tested with the first/last name fields.
=> Fix the name field display/email order

includes/class-coblocks-block-assets.php, src/blocks/counter/block.json, src/blocks/counter/test/counter.cypress.js, src/blocks/events/block.json, src/blocks/events/test/events.cypress.js, src/blocks/gist/block.json, src/blocks/gist/test/gist.cypress.js, src/blocks/post-carousel/block.json, src/blocks/post-carousel/test/post-carousel.cypress.js
Some files scripts were missed or not properly registered. Those have been resolved here. Added e2e tests that will catch if this case ever happens in the future. 
Enqueued scripts. 
E2E tests added.
Tested manually and with Cypress.
Should always enqueue the registered scripts from block.json.
=> Enqueue the registered scripts from block.json

includes/block-migrate/loader.php
This should solve this warning message : https://wordpress.org/support/topic/php-error-612/
=> Check null getcurrentscreen

src/extensions/apply-extensions.js
Coblocks extends all blocks (through the `editor.BlockListBlock` filter) with a `withSelect` HoC, subscribing _all_ blocks to the currently selected block. This means that on typing, the selected block updates, and _all_ blocks on the page re-render because they are all subscribed to changes to the selected block.
I went through all functions in `addAllEditorProps` to which `props` is being passed to, but none of them seem to be using `props.selected`, so it looks like this subscription can be removed without further changes. 
Use the React Dev Tools and enable highlight on re-render. Type in a block and watch all blocks re-render.
=> [Urgent] Performance: don't subscribe all blocks to selected block

.wordpress-org/blueprints/blueprint.json
Introduce a `blueprint.json` file that is a template for a live preview on WordPress.org.
- Same file as the one currently on WordPress.org, so when this PR is merged it won't overwrite the existing one.
- https://plugins.svn.wordpress.org/coblocks/assets/blueprints/
- The live preview is currently only visible to logged in plugin committers. It can be enabled publicly from the WordPress.org plugin page advanced tab.
We can import a `.wxz` file. Maybe we setup a number of CoBlocks blocks so that when the page loads there are a number of blocks on the page already?
`Test Preview` link on the [WordPress.org plugin page](https://wordpress.org/plugins/coblocks/).
- Add a `blueprint.json` file so users can test out CoBlocks before …
=> Introduce a blueprint for WordPress preview

src/blocks/gallery-carousel/block.json, src/blocks/gallery-collage/block.json, src/blocks/gallery-offset/block.json, src/blocks/gallery-stacked/block.json
Fixes #2571 
Not all galleries properly listed the 'Lightbox' script to load under the 'viewScript' block.json property. Adding the script allows the Lightbox to function as expected with all CoBlocks galleries. 
Change here to block.json to allow for proper loading of the 'lightbox-script'.
Should allow the Lightbox on all CoBlocks galleries if only that single gallery is present on the page or all of them. Each block now ensures the script is loaded.
=> enable the lightbox script to load for all CoBlocks galleries

src/js/coblocks-lightbox.js
Fixes #2582 
Enhance the Lightbox script logic to allow for Lightbox with A3 Lazy Load plugin. 
Source the image from `data-src` attribute if the `src` contains 'lazy-load'.
Lightbox JavaScript changes.
Tested manually. 
Should allow Lightbox to function when A3 Lazy Load is enabled.
=> Enable Lightbox compatibility with Lazy Loading

src/blocks/icon/index.php
Escape icon block `href` attribute.
=> Escape the icon href attribute

.github/workflows/test-e2e-cypress.yml, .github/workflows/test-e2e.yml, .github/workflows/test-php-unit.yml, .github/workflows/test-php.yml, .github/workflows/test-wp-next.yml
=> Try PHP 8.3 compatibility

src/extensions/site-design/component.js
The Site Design component has some logic that is responsible for moving Style elements. Changes in versions of WordPress over time had made the previous logic incompatible. 
**Before**
**After**
Changes here to selectors. This change should prevent the same error from occurring in the future.
Tested manually in Managed WordPress hosting.
Should resolve the error with Site Design in the post editor.
=> Resolve error with Site Design failing DOM operations.

includes/class-coblocks-site-content.php, src/extensions/site-content/index.js
Prevent the `coblocks-site-content` plugin from loading outside of `post-new.php` pages.
=> Only load the coblocks-site-content plugin on post-new.php

src/blocks/events/index.php
Tested by running `nc -l 127.0.0.1 9000`. Adding a `Events` block to the page, ticking off `Link a calendar` and adding the URL `http://127.0.0.1:9000` to the calendar URL and ensuring an error is returned.
=> Sanitize the iCal URL before initializing

src/blocks/services/block.json, src/blocks/services/edit.js, src/blocks/services/inspector.js, src/blocks/services/service/block.json, src/blocks/services/service/edit.js, src/blocks/services/service/inspector.js, src/blocks/services/service/test/__snapshots__/save.spec.js.snap, src/blocks/services/service/test/save.spec.js, src/blocks/services/test/__snapshots__/save.spec.js.snap, src/blocks/services/test/save.spec.js, src/blocks/services/test/services.cypress.js
Removed 'Display button' toggle from the services and service blocks.
[Link to issue WPEX-3677](https://godaddy-corp.atlassian.net/browse/WPEX-3677?atlOrigin=eyJpIjoiNGMzM2ZkZWZiOWRlNDk5NWJlYWM1MjFlNTAzZjNlOTQiLCJwIjoiaiJ9)
Manual regression testing
'Display button' toggle should be completely removed after deciding to allow users to place buttons within the inner blocks if they choose.
=> Fix disappearing buttons inside of Services blocks

class-coblocks.php, package.json, readme.txt
Bump tested up to values to 6.6, in preparation for the WordPress 6.6 release on 7/16/2024.
Non Breaking change
Tested CoBlocks with WordPress 6.6
=> Bump tested up to values to 6.6

.dev/tests/cypress/helpers.js, .github/workflows/test-e2e.yml, .github/workflows/test-php.yml, package.json, src/blocks/features/test/features.cypress.js, src/blocks/form/test/form.cypress.js, src/blocks/gif/test/gif.cypress.js, src/blocks/hero/test/hero.cypress.js, src/blocks/post-carousel/post-item.js, src/blocks/post-carousel/test/post-carousel.cypress.js, src/blocks/posts/edit.js, src/blocks/posts/test/posts.cypress.js, src/blocks/pricing-table/pricing-table-item/test/pricing-table-item.cypress.js, src/blocks/row/test/row.cypress.js, src/blocks/services/service/test/service.cypress.js, src/blocks/shape-divider/test/shape-divider.cypress.js, yarn.lock
Ensure that the excerpts inside of the posts and post carousel blocks are properly escaped.
Additionally fixed the e2e tests for WordPress 6.6. (Merged changes from `WP66-beta1` branch here.
Bug fix (non-breaking change which fixes an issue) 
Tested using various HTML markup in the excerpt of posts.
=> Escape the HTML in the editor of the posts and post carousel blocks

.dev/tests/cypress/helpers.js, .github/workflows/test-e2e.yml, .github/workflows/test-php.yml, includes/block-migrate/loader.php, package.json, src/blocks/features/test/features.cypress.js, src/blocks/form/test/form.cypress.js, src/blocks/gif/test/gif.cypress.js, src/blocks/hero/test/hero.cypress.js, src/blocks/post-carousel/post-item.js, src/blocks/post-carousel/test/post-carousel.cypress.js, src/blocks/posts/edit.js, src/blocks/posts/test/posts.cypress.js, src/blocks/pricing-table/pricing-table-item/test/pricing-table-item.cypress.js, src/blocks/row/test/row.cypress.js, src/blocks/services/index.js, src/blocks/services/service/test/service.cypress.js, src/blocks/services/test/services.cypress.js, src/blocks/shape-divider/test/shape-divider.cypress.js, yarn.lock
Resolves #2617 
Introduce a bail check when missing DOMDocument. 
Simple change to bail block migrations when missing dependency.
=> Introduce bail check when missing DOMDocument

.github/workflows/test-e2e.yml, .github/workflows/test-php.yml, package.json
Update the readme and workflows to test against WordPress 6.7.
**Note:** This should not be merged until on or after November 12th, 2024.
non-breaking change
=> Update workflows and readme with 6.7 changes

includes/admin/class-coblocks-crop-settings.php, includes/class-coblocks-block-assets.php
Enhance nonce validation and permission checks for crop settings, ensuring only authorized users can access and modify images. Additionally, conditionally include nonce values in localized script data.
=> Improve nonce handling and permissions in crop settings API
